### PR TITLE
Fix performance issue in MLB 2k games with profiler funcs

### LINKED ISSUE #17623: Unusual slowdown in the MLB 2k games
Reported by Brahmadath through e-mail, that it slows down in specific situations between games.

Curiously, according to the screenshot, the game spends a TON of time in `sceKernelReferGlobalProfiler`. Possibly this call should take a lot more simulated time, maybe it's in a tight loop around it for some reason? We've seen similar things before. Or we return bad data confusing the game - which may clearly be the case since we have a stub implementation that just returns 0, currently.

Screenshot_20230626-012051_PPSSPP (1)

### PR DESCRIPTION
**Pull request by hrydgard**
The function `sceKernelReferGlobalProfiler` are spammed by this game between matches. So let's reduce logging to DEBUG and delay the response by a tested number of ms. And do the same for its sibling function, sceKernelReferThreadProfiler.

Fixes #17623

Here's the pspautotest I wrote, though not a good idea to check in the timing checks:

```cpp
#include "shared.h"
#include "string.h"

int main(int argc, char *argv[]) {
	checkpointNext("sceKernelReferThreadProfiler");
	u64 before = sceKernelGetSystemTimeWide();
	PspDebugProfilerRegs *regs = sceKernelReferThreadProfiler();
	checkpoint("regs: %08x", regs);
	u64 timeTaken = sceKernelGetSystemTimeWide() - before;
	checkpoint("timeTaken: %llu", (unsigned long long)timeTaken);
	if (regs) {
		// TODO: Inspect the data here, but we don't seem to get any.
	}

	checkpointNext("sceKernelReferGlobalProfiler");
	before = sceKernelGetSystemTimeWide();
	regs = sceKernelReferGlobalProfiler();
	checkpoint("regs: %08x", regs);
	timeTaken = sceKernelGetSystemTimeWide() - before;
	checkpoint("timeTaken: %llu", (unsigned long long)timeTaken);
	if (regs) {
		// TODO: Inspect the data here, but we don't seem to get any.
	}
	return 0;
}
```
and the output:
```
[x] sceKernelReferThreadProfiler
[x] regs: 00000000
[x] timeTaken: 55

[x] sceKernelReferGlobalProfiler
[x] regs: 00000000
[x] timeTaken: 54
```

It should be noted though that this doesn't really confirm that the functions don't take a parameter, only that they return 0. But I've chosen to just follow https://pspdev.github.io/pspsdk/group__ThreadMan.html#ga8fd30da51b9dc0507ac4dae04a7e4a17 . It does seem assymetrical with `sceKernelReferSystemStatus` though...

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm just gonna go for this one. Seems safe enough.

**Comment by unknownbrackets** [comment]
There's an option for the tests `CHECKPOINT_ENABLE_TIME = 1;`, which will show the time since last checkpoint automatically on each.  Also, I've usually run the func 8 times in a row to avoid overheads.

That said, I doubt exactness is that important here, as long as we're in the right area.

-[Unknown]

File: Core/HLE/sceKernel.cpp [hunk 1]
```diff
@@ -678,23 +679,23 @@ struct DebugProfilerRegs {
...
+static u32 sceKernelReferThreadProfiler() {
+	// This seems to simply has no parameter:
+	// https://pspdev.github.io/pspsdk/group__ThreadMan.html#ga8fd30da51b9dc0507ac4dae04a7e4a17 , 
+	// And in testing it just returns null in 55 usec (which is surprisingly long).
+
+	// So, we log only if debug logging is enabled, and sleep for a bit.
+	DEBUG_LOG(SCEKERNEL, "0=sceKernelReferThreadProfiler()");
+
+	// The delay has been measured, 53-56 us.
+	hleEatMicro(55);
```
Comment (unknownbrackets) [inline Core/HLE/sceKernel.cpp:691]: Probably not important, but I usually use hleEatCycles for things that get faster when you set the PSP clock speed faster.  This is probably (but not certainly) one of those cases.

-[Unknown]

**Comment by hrydgard** [comment]
It has turned out that implementing the function like this makes MLB 2K11 run incredibly slowly. So I think there's more to this function. Maybe the function signature in the pspsdk is simply wrong, and it does write a structure to the first parameter. I'll investigate soon.

And yeah, you're right that hleEatCycles should be more appropriate here.
