### PR TITLE
Modify Hack for Crash Tag Team Racing to fix Gundam games

### LINKED ISSUE #7136: Gundam Battle Universe Crash
game
crash after this screen

debug
ppsspp-v0.9.9.1-1061-gea63719

I'm sorry
I can't explain well

### LINKED ISSUE #9003: Gundam Battle Chronicle freeze on mission exit
Battle Chronicle freezes **every** time after mission end or exiting to menu from mission. Testing on latest 1.3-7.
That's what I have in console when that happens:

```
39:19:526 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:414 Creating FBO for 00000000 : 480 x 272 x 1
39:19:614 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1922 Decimating FBO for 00044000 (480 x 272 x 1), age 6
39:19:679 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1922 Decimating FBO for 00000000 (480 x 272 x 1), age 6
39:19:915 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 43 fs 44
39:19:916 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 30 fs 34
39:21:322 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 38 fs 14
39:23:351 user_main    W[G3D]: Common\FramebufferCommon.cpp:886 Inter-buffer block transfer 04000000 -> 04044000
39:23:384 user_main    I[HLE]: HLE\scePower.cpp:369 scePowerSetClockFrequency(222,222,111)
39:23:550 user_main    E[G3D]: GPUCommon.cpp:251 sceGeListEnqueue: can't enqueue, stack address 09EEB508 already used
39:23:550 user_main    E[G3D]: GPUCommon.cpp:251 sceGeListEnqueue: can't enqueue, stack address 09EEB508 already used
39:23:869 ATRAC3 play  I[ME]: HLE\sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(0)
39:23:869 ATRAC3 play  I[KERNEL]: HLE\sceKernelThread.cpp:2151 sceKernelExitDeleteThread(0)
```

Issue is not recent, 2 reports with GTS250 are mine http://report.ppsspp.org/game/ULJS00122_1.02 Note that I put 1 star for gameplay only for reason you can't complete missions because of this issue, there's no issues in gameplay itself besides that, but it alone prevents from progressing.
The purpose of second report was in showing those settings on reports with "Perfect" not solving it.

### LINKED ISSUE #9007: Gundam Battle Royale _kinda_ freezes when ace appears
Well, mostly aces pilots, but sometimes happens with regular mechas I remember it happened at A Baoa Qu fortress plenty of times(triggering the switch to open door appearing enemies can cause the issue). Some times could be avoided by entering and exiting pause menu right before that or just turning, but than may happen during ace's mecha explosion, when locking on ace or while using SP attack. Other way to avoid issue is to reload game, than issue will not happen.
What I stated previously "Also FastMemory prevents it from even starting and Multithreading doesn't affects said issue." is rubbish, game works with FastMemory.
That's log for it:

```
58
54:07:431 idle0        I[G3D]: GLES\ShaderManager.cpp:165 Linked shader: vs 40 fs 36
54:09:386 ATRAC3 play  I[ME]: HLE\sceAtrac.cpp:1671 0=sceAtracReleaseAtracID(0)
54:09:387 ATRAC3 play  I[KERNEL]: HLE\sceKernelThread.cpp:2151 sceKernelExitDeleteThread(0)
54:09:440 idle0        W[FileSys]: FileSystems\ISOFileSystem.cpp:515 Reading beyond end of file, clamping size 1228800 to 757428
54:09:461 user_main    I[ME]: HLE\sceAtrac.cpp:1910 0=sceAtracSetDataAndGetID(09cc4b04, 000b8eb4): atrac3+ stereo audio
54:09:461 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:1975 496=sceKernelCreateThread(ATRAC3 play thread, 08889b6c, 00000010, 32768, 00000000, 00000000)
54:09:462 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2064 0=sceKernelStartThread(496, 16, 09df8b3c)
54:09:928 user_main    E[G3D]: GPUCommon.cpp:251 sceGeListEnqueue: can't enqueue, stack address 09EA7C48 already used
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000048
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000030
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000028
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000034
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 0000002c
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000018
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 0000004c
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000050
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000048
54:09:952 user_main    W[MM]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000008
54:09:953 user_main    W[MM]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000000
54:09:953 user_main    W[MM]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000004
54:09:953 user_main    W[MM]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000014
54:09:953 user_main    W[MM]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000008
54:09:953 user_main    W[MM]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000018
```

Then it spams console like crazy with those invalid address read/write while you hearing ckrackles which supposed to be "greeting" of said ace pilot that appearing. In this case it's 3rd location of federation's route, stage Lhasa. There certain "cursed" stages where it happen and never happen in other stages, Lhasa is one of those, when you beat zakus ace gouf appears and that craziness happens. Screen shifts between 2 frames one with ace standing for introduction and second not from introduction sequence. While it's happening you can hear very small parts of introduction phrase of the ace pilot.

What I also noticed is that issue won't happen until loaded from save state(not in-game save and loading should occur before playing stage). Other note(it's foggy memory of not recent past so be in doubt about it) - once I left game while issue was there and when returned game resolved. If that note indeed is true I think it related to playing of ace's introduction phrase.

P.S. this issue probably unrelated to those of Chronicle and Universe freezes, log is different and symptoms. And game isn't freezing at end/start of a mission.

### PR DESCRIPTION
**Pull request by LunaMoo**
This wasn't tested much yet, I don't even have Crash Tag Team Racing so maybe it's not ok for merging.

 It modifies the hack for CTTR to the other function mentioned in #5468 which turns out to fix Gundam games that is: #7136, #9003 maybe also #9007 /definitely needs more testing, hence why I'm opening this pr.

 So far I tested Gundam Battle Universe and Gundam Battle Chronicle with this, both seems to work, but in place of previous crash they get like 1 glitchy frame, might be caused by this or some other GE function also needing a change in pair with this. Edit: Nvm the glitch is #9275 ;p saw a difference since I updated right before building this heh.
 Edit: Removed custom build as I got CTTR tested which is affected same way as before aka still fixed at least US version from the PS store, but it was potentially affecting different regions differently in the first place?
Fixes #7136, Fixes #9003
Should also fix #9007, but I can't find which Ace units crash it even without this hack, the error from the log posted looks exactly same as from other 2 gundam games through.

### CODE REVIEW

File: Core/HLE/sceGe.cpp [hunk 1]
```diff
@@ -408,6 +408,7 @@ int sceGeListSync(u32 displayListID, u32 mode) {
 
 static u32 sceGeDrawSync(u32 mode) {
 	//wait/check entire drawing state
+	hleEatCycles(500000); //HACK(?) : Potential fix for Crash Tag Team Racing and a few Gundam games
```
Comment (hrydgard) [inline Core/HLE/sceGe.cpp]: Don't like this, this seems like a dangerous change that will affect the timing of many, many games. Of course, eating a small amount of cycles here makes sense, but that big an amount would seem to indicate that the problem really is that we are processing display lists too fast, and the game is buggy and stupidly relies on that.

If we find no other sensible solution, I could accept this behind a compat flag that only turns it on for the affected games.

**Comment by LunaMoo** [comment]
Eating small amounts didn't really helped I actually tried it even before taking value from CTTR hack, so I made it into compat.ini.
 I actually fixed it before with cwcheat hack but it was doing similar thing in very wasteful way ~ by adding a big loop that was just wasting time to slow down following function execution.

**Comment by moura464** [comment]
if (PSP_CoreParameter().compat.flags().DrawSyncEatCycles) <<<<error  Builds What? No

**Comment by moura464** [comment]
Build warning :)

**Comment by LunaMoo** [comment]
Don't really see any warnings, maybe your compiler is racist against braceless statements.;p VS and most other stuff seeing what Travis already built seems to be perfectly happy with it.

**Comment by hrydgard** [comment]
Alright, this is fine. It's clear that we need to improve GPU timings.

**Comment by sum2012** [comment]
@LunaMoo Not sure need include this.
I get report from baidu that SD Gundam G Generation Over World crash in-game

**Comment by LunaMoo** [comment]
Don't know about any crashes in that game, there's even this [english fan translation project](https://gbatemp.net/threads/sd-gundam-g-generation-overworld-english-translation.369219/) where they definitely use ppsspp, even released some HD textures to this game aiming at texture replacement and the only crashing mentioned in their very long thread seems to be related to some HQ texture pack(not the HD one) which replaces files on iso.

 It should be easy enough for any user to just edit compat.ini and add new games for the existing hacks to check if it can affect it or not.
 Althrough I kind of doubt this had the same problem as Gundam Battle games, this one is a tactical 2D game made by different developer and likely runs on completely different engine. Crash could easily be related to some ppsspp options like multithreading, changed psp cpu clock, cheats or be specific to any fan made patch.

**Comment by sum2012** [comment]
It is not easy for edit compat.ini for Android.
Anyway,I will test it when I have time

**Comment by hrydgard** [comment]
yeah, been meaning to make it also read compat.ini from PSP/SYSTEM on the stick if that exists... that would make such tests easier on Android. Though bugs that need compat workarounds are not normally android-only so you can just try on PC.

**Comment by LunaMoo** [comment]
Actually it was already done;p.
 I just tried to make sure, creating new compat.ini on memstrick/PSP/SYSTEM/ makes it read hacks for games which aren't included in compat.ini in the assets folder.

 So it should be easy for android users as well. They just need to create that file manually or copy it from ppsspp github whatever's faster, then add new game ID's under hacks they want to activate.

**Comment by hrydgard** [comment]
Oh yeah, I guess that got done indeed :)

**Comment by unknownbrackets** [comment]
What happens if we remove the hack for Gundam now that #12160 is in?

-[Unknown]

**Comment by hrydgard** [comment]
I'll open a new issue for that.
