### PR TITLE
Resurrect and refactor the AxisSwap feature

### LINKED ISSUE #17292: AxisSwap not working.
### Game or games this happens in

None

### What area of the game / PPSSPP

All Game

### What should happen

Can't Swap Dpad and LeftStick, I saw a lot of code changes and functional failures, but I couldn't find where the error occurred.

### Logs

_No response_

### Platform

Linux / BSD

### Mobile phone model or graphics card

G31

### PPSSPP version affected

9c9df208d38a2af86fd12f1a7634824dfe7e9ea6

### Last working version

534896d2abe0d69ede5ba6becddf5b79b4a1327d

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
It indeed got broken in the big input refactor.

Fixes #17292 , and makes it a little more robust than before (now zero chance of stuck keys on swap).

### CODE REVIEW

File: Core/ControlMapper.cpp [hunk 1]
```diff
@@ -386,6 +423,36 @@ bool ControlMapper::Key(const KeyInput &key, bool *pauseTrigger) {
 	return UpdatePSPState(mapping);
 }
 
+void ControlMapper::ToggleSwapAxes() {
+	swapAxes_ = !swapAxes_;
+
+	// To avoid stuck keys, just reset it all.
+	for (auto &mapping : curInput_) {
+		mapping.second = 0.0f;
+	}
```
Comment (unknownbrackets) [inline Core/ControlMapper.cpp:432]: Hm, suppose I had a mapping for L1+R1 (together) and also had R2 mapped to swap.  I start by pressing (and holding) L1, then I press R2 (swapping) and then press R1.  Wouldn't this clear L1 and thus make my L1+R1 press fail?

I guess I'm not really sure what one would expect, though.  If I had L1 in the above example mapped to Up, you'd think it should then release Up an set Analog Y to -1.0, I suppose... not sure what it did before.  I haven't used this feature.

-[Unknown]
