### PR TITLE
Fix a cheat menu crash reported on the forums

### LINKED ISSUE #9804: Hang loading short cwcheat files
Platform: Windows 10
Version: 1.4.2 (x64)

Loading a cwcheat file where the current game is the last one in the file can hang.

Loading the following while running ULES-00850: 
```
_S ULES-00850
_G Final Fantasy Tactics: The War of the Lions [EUR]
_C0 10, 000, 000 Gile
_L 0x20C4B404 0x00989680
```
will hang PPSSPP.

Loading the following
```
_S ULES-00850
_G Final Fantasy Tactics: The War of the Lions [EUR]
_C0 10, 000, 000 Gile
_L 0x20C4B404 0x00989680
_S ULES-99999
_G A Dummy Game
```

will load fine.

Problem is a missing EOF check that causes a loop to go infinite.

Pull Request Inbound

### PR DESCRIPTION
**Pull request by LunaMoo**
Cheat names really shouldn't be empty, even if it wouldn't crash it would look bad.
This also stops lines with # comments from being removed by cheat menu and rising shortest valid "_" lines length to 5.:]

Edit: now also fixes #9804 as the person opening it seems unwilling to open pr.:]
Changed some other substr used in cheat menu as well. I'm guessing it's just safer that way.

### CODE REVIEW

**Comment by hrydgard** [comment]
Instead of str.substr(x, 1) == "y" use str[x] == 'y'. Otherwise looks fine.

File: Core/CwCheat.cpp [hunk 1]
```diff
@@ -87,7 +87,7 @@ bool CheatFileParser::Parse() {
 		getline(file_, line, '\n');
 		line = TrimString(line);
 
-		if (line.length() > 2 && line[0] == '_') {
+		if (line.length() >= 5 && line[0] == '_') {
```
Comment (unknownbrackets) [inline Core/CwCheat.cpp]: Hmm, there's a lot of checks of length inside `ParseLine()`.  If this is needed, it means one of them is buggy, right?

It might be good to add a comment indicating why 5, specifically, was chosen.  I suppose the shortest possible line would be `_G A` or something...

-[Unknown]

File: Core/CwCheat.cpp [hunk 2]
```diff
@@ -340,7 +340,17 @@ std::vector<std::string> CWCheatEngine::GetCodesList() {
 		std::string line;
 		getline(list, line, '\n');
 
-		if (line.length() > 3 && (line.substr(0, 1) == "_" || line.substr(0, 2) == "//")) {
+		bool validCheatLine = false;
+		// This code is used by cheat menu which doesn't support empty names
+		if (line.length() >= 5 && line[0] == '_') {
+			for (int i = 4; i < line.length(); i++) {
```
Comment (unknownbrackets) [inline Core/CwCheat.cpp]: This is safe because we only care about `_C` lines, right?  I mean, `_G Nospaceshere` or `_S ULUS-12345` would otherwise be valid, right?

-[Unknown]

File: Core/CwCheat.cpp (hunk 1 above)
Comment (LunaMoo) [reply Core/CwCheat.cpp]: The game name isn't really used by PPSSPP for anything, but yeah name is the one limiting the shortest part. Shortest name of PSP game has 2 letters(N+) and shortest name to display in UI would have 1 letter so since _C line has extra parameter they end up same at shortest of 5 letters.

 Guess I might add comment clearing that up, but that change wasn't really important here and doesn't do much, I made this change to keep it same with function called by cheat menu below as while it runs later it recreates list and would discard any invalid / too short lines that aren't comments anyway.

File: Core/CwCheat.cpp (hunk 2 above)
Comment (LunaMoo) [reply Core/CwCheat.cpp]: It's safe because all lines that matter will need to have at least at least 1 non space character starting from 5 position.
We basically care about 2 things here:
- lines with name that has something which could be displayed, hence the loop breaks at first non space character and doesn't bother checking any syntax,
- lines which for sure does not have any valid cheat syntax.

 Which means too short, but also all lines that does not start from either:
````
_
//
#
````
all will be discarded whenever any change to the list is made:]. So if we paste a long novel inside cheat file, after that function runs, the cheat file will be cleaned ouf of all unrelated and uncommented text:].
