### PR TITLE
SaveState: Load misaligned wide strings properly

### LINKED ISSUE #14021: [UBSAN] Serializer.cpp:131: load of misaligned address
When loading a save state:

```
/usr/include/c++/10/bits/char_traits.h:715:16: runtime error: load of misaligned address 0x7f2653af6121 for type 'const char_type', which requires 2 byte alignment
0x7f2653af6121: note: pointer points here
 08 00 00  00 31 00 31 00 31 00 00  00 42 00 00 00 50 53 50  44 69 61 6c 6f 67 00 00  00 00 00 00 00
              ^ 
    #0 0x560f14908f1f in std::char_traits<char16_t>::eq(char16_t const&, char16_t const&) /usr/include/c++/10/bits/char_traits.h:715
    #1 0x560f14909028 in std::char_traits<char16_t>::length(char16_t const*) /usr/include/c++/10/bits/char_traits.h:736
    #2 0x560f1490acf7 in std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> >::assign(char16_t const*) /usr/include/c++/10/bits/basic_string.h:1438
    #3 0x560f14909557 in std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> >::operator=(char16_t const*) /usr/include/c++/10/bits/basic_string.h:676
    #4 0x560f14c5e91d in Do(PointerWrap&, std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> >&) ../Common/Serialize/Serializer.cpp:131
    #5 0x560f149086fe in PSPOskDialog::DoState(PointerWrap&) ../Core/Dialog/PSPOskDialog.cpp:1146
    #6 0x560f143b102c in __UtilityDoState(PointerWrap&) ../Core/HLE/sceUtility.cpp:180
    #7 0x560f14130dfa in __KernelDoState(PointerWrap&) ../Core/HLE/sceKernel.cpp:278
    #8 0x560f1451fb50 in SaveState::SaveStart::DoState(PointerWrap&) ../Core/SaveState.cpp:308
    #9 0x560f1452bd2a in CChunkFileReader::Error CChunkFileReader::LoadPtr<SaveState::SaveStart>(unsigned char*, SaveState::SaveStart&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ../Common/Serialize/Serializer.h:140
    #10 0x560f1452e14b in CChunkFileReader::Error CChunkFileReader::Load<SaveState::SaveStart>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, SaveState::SaveStart&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ../Common/Serialize/Serializer.h:184
    #11 0x560f14525485 in SaveState::Process() ../Core/SaveState.cpp:761
    #12 0x560f1453db4b in PSP_RunLoopUntil(unsigned long long) ../Core/System.cpp:548
    #13 0x560f1453dd02 in PSP_RunLoopFor(int) ../Core/System.cpp:561
    #14 0x560f1453dafb in PSP_RunLoopWhileState() ../Core/System.cpp:539
    #15 0x560f13cb11f7 in EmuScreen::render() ../UI/EmuScreen.cpp:1520
    #16 0x560f14e7e28b in ScreenManager::render() ../Common/UI/Screen.cpp:167
    #17 0x560f13c0ff67 in NativeRender(GraphicsContext*) ../UI/NativeApp.cpp:1098
    #18 0x560f13ef6ba0 in UpdateRunLoop() ../Core/Core.cpp:208
    #19 0x560f14f3b137 in main ../SDL/SDLMain.cpp:1084
    #20 0x7f26b3878cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #21 0x560f13c05bad in _start (/home/gleb/repos/glebm/ppsspp/build/PPSSPPSDL+0x21d7bad)
```

### PR DESCRIPTION
**Pull request by unknownbrackets**
Fixes #14021.  I suppose this could've been vectorized, maybe.  It's only really the OSK, though.

-[Unknown]

### CODE REVIEW

File: Common/Serialize/Serializer.cpp [hunk 1]
```diff
@@ -111,14 +111,22 @@ void Do(PointerWrap &p, std::string &x) {
 }
 
 void Do(PointerWrap &p, std::wstring &x) {
-	int stringLen = sizeof(wchar_t)*((int)x.length() + 1);
+	int stringLen = sizeof(wchar_t) * ((int)x.length() + 1);
 	Do(p, stringLen);
 
+	auto read = [&]() {
+		std::wstring r;
```
Comment (glebm) [inline Common/Serialize/Serializer.cpp:118]: Would it be simpler to read into `x` directly, since it already is the right length (from what I can gather)?

So something like:

```c++
memcpy(&x[0], *p.ptr, x.size() * sizeof(wchar_t))
```

Comment (unknownbrackets) [reply Common/Serialize/Serializer.cpp:118]: No, because this is used for the verify path too.  We cannot overwrite x in that case.

-[Unknown]

Comment (glebm) [reply Common/Serialize/Serializer.cpp:118]: Could pass the string as a parameter to avoid an allocation in the read case if this is performance-sensitive but I'm guessing it's not
