### PR TITLE
Less broken behavior with integer scale factor + auto render resolution

### LINKED ISSUE #17355: Integer scaling + Auto render resolution don't work together
Needs fixing before the release.

### PR DESCRIPTION
**Pull request by hrydgard**
Unfortunately these don't make the same decision (integer scale factor tries to make sure the whole image can fit in the window, while auto render resolution is glad to step up a level), but at least the user is not faced with a black screen.

Not sure what's actually the best thing here, possibly this case should be disallowed somehow.

Fixes #17355

### CODE REVIEW

File: GPU/Common/PresentationCommon.h [hunk 1]
```diff
@@ -127,6 +127,7 @@ class PresentationCommon {
 
 	void GetCardboardSettings(CardboardSettings *cardboardSettings) const;
 	void CalculatePostShaderUniforms(int bufferWidth, int bufferHeight, int targetWidth, int targetHeight, const ShaderInfo *shaderInfo, PostShaderUniforms *uniforms) const;
+	int CalculateZoom() const;
```
Comment (unknownbrackets) [inline GPU/Common/PresentationCommon.h:130]: nit: Refactoring that didn't happen?

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]

File: GPU/Common/PresentationCommon.h (hunk 1 above)
Comment (hrydgard) [reply GPU/Common/PresentationCommon.h]: indeed, didn't work out. removing.
