### PR TITLE
Port over the Exynos cacheline size fix from Dolphin. 

### LINKED ISSUE #8908: Crashes on Galaxy S7
Hello 

PPSSPP doesn't run on my Galaxy S7. If I try to load a ROM, it crashes or runs for a few seconds until it does it. I tried to disable JIT, but it doesn't make any difference.

I never used PPSSPP before, so you can call me a noob. It would be really great if someone could help me.

Thx =)

### PR DESCRIPTION
**Pull request by hrydgard**
Thanks to lewurm of the mono project for the discovery and original fix.

Should finally and correctly fix, rather than work around, the crashing issues seen on non-US Galaxy S7 devices (fixes #8908)

See https://github.com/dolphin-emu/dolphin/pull/4204 and https://github.com/mono/mono/pull/3549

Replaces https://github.com/hrydgard/ppsspp/pull/8769 (which was a good effort!)

### CODE REVIEW

File: Common/Arm64Emitter.cpp [hunk 1]
```diff
@@ -313,24 +313,40 @@ void ARM64XEmitter::FlushIcache()
...
+	static size_t icache_line_size = 0xffff, dcache_line_size = 0xffff;
+	size_t isize, dsize;
+
+	__asm__ volatile("mrs %0, ctr_el0" : "=r"(ctr_el0));
+	isize = 4 << ((ctr_el0 >> 0) & 0xf);
+	dsize = 4 << ((ctr_el0 >> 16) & 0xf);
+
+	// use the global minimum cache line size
+	icache_line_size = isize = icache_line_size < isize ? icache_line_size : isize;
+	dcache_line_size = dsize = dcache_line_size < dsize ? dcache_line_size : dsize;
```
Comment (unknownbrackets) [inline Common/Arm64Emitter.cpp]: Hmm, if we're not using the line size we just read, then this can mean a race condition, right?

For example, let's say FlushIcacheSection() is called on BIG cpu, possibly several times.  When it swaps to the LITTLE cpu:
1. If it's before we check the line size, it's fine, we'll get the right one.
2. If it's after we invalidate, then hopefully it's handled correctly.
3. If it's while we're invalidating, we're screwed if it doesn't handle the swap correctly.  We still have the BIG size.

If it's necessary to take the lowest, then we must need to re-read the line size for every iteration of the loop.  It seems to me we shouldn't cache at all?

-[Unknown]

**Comment by unknownbrackets** [comment]
Yeah, I guess I should've looked at gcc's code - I suspected it was invalidating wrong but thought both CPUs had separate icaches that weren't being invalidated on swap, or something.

I think given this, the existing fix is not good enough.  If a jit block is larger than a cache line, the padding won't solve it.. it's just an alignment thing.  It only happens to fix most of the cases by luck.  I definitely agree we should merge this before v1.3.0.

It looks like it's been confirmed in Dolphin that this fixes things there.

-[Unknown]

File: Common/Arm64Emitter.cpp (hunk 1 above)
Comment (lewurm) [inline Common/Arm64Emitter.cpp]: yes, this is correct (it's _unlikely_ though).

The right way would be to iterate over all available cores on startup and figure out the minimum cache line size. I couldn't figure out a reliable way to do that on Android. Or, since you already have infrastructure for device specific quirks, you could hard code it...

Comment (hrydgard) [inline Common/Arm64Emitter.cpp]: But... since we save the minimum, and a core jump will wipe the icache anyway, case 3 can't possibly be an issue?

Comment (hrydgard) [inline Common/Arm64Emitter.cpp]: @lewurm  yeah. I removed it from our copy in a followup commit: 
https://github.com/hrydgard/ppsspp/commit/0b8a3e8c26d2340dc79a5a8e039aef72fd61767d

Comment (hrydgard) [inline Common/Arm64Emitter.cpp]: And, reverted it. Was convinced by some comments in the HN thread - in case the cores are used simultaneously it might still be an issue.
