### PR TITLE
Android: Display measurement fixes

### LINKED ISSUE #8728: [Android - 1.2.2.0] Immersive mode breaks virtual keys
When immersive mode is enabled, due the screen redimension, the virtual keys are repositioned as expected, but the action region remains in its old location

### LINKED ISSUE #9758: Missaligned controls for stretched phone screens?
When using Immersive mode, the whole screen is filled up, but the controls are not in the right position horizontally; for example, the Square and Circle buttons are on the wrong places so that when I tap its missaligned.

I'm using an LG G6, which has an aspect ratio of 18:9.

### LINKED ISSUE #11526: After 1.7.1, on-screen buttons don't work / are misaligned
Samsung Galaxy s8 plus.
PPSSPP 1.7.1.
Game: Monster hunter freedom Unite.
Right buttons doesn't work.

### LINKED ISSUE #11869: Problem with immersive mode enabled on PPSSPP on smartphone
### What happens?
I am having problems with PPSSPP since my smartphone was upgraded to Android Pie. In Android 9 the immersive mode is not working properly. When activated, the image will "cut". When changing the internal resolution in the emulator the main menu returns to normal size, but when exiting the application and entering it again the problem returns. The situation only completely normalizes when the immersive mode is disabled in the emulator settings.

### What *should* happen?
What should happen is that PPSSPP would adjust the screen of the smartphone as it did in the previous version of Android, 8.0.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
My smartphone is the Galaxy Note 8, Exynos version, with Android Pie 9.0, version of PPSSPP v.1.7.5-553-gc77af182a.

### PR DESCRIPTION
**Pull request by rlac**
When the surface is created in immersive mode, it's initial size does not match its final size (seems to be created at the size it would be with immersive mode off then resized). Setting the display size to the created surface size resulted in the bottom of the screen being cut off and touch events being in the wrong location when starting up in immersive mode (toggling it in the settings worked correctly).

In multi-window mode, getRealMetrics returns the screen dimensions, not the window size, so I've changed it to use getMetrics instead in this case. Can now enter/resize/exit multi-window and it resizes on each change.

Added for automation: Fixes #11869, fixes #11526, fixes #8728, fixes #9758.

### CODE REVIEW

File: android/src/org/ppsspp/ppsspp/NativeActivity.java [hunk 1]
```diff
@@ -788,6 +792,14 @@ public void onConfigurationChanged(Configuration newConfig) {
 		}
 	}
 
+	@Override
+	public void onMultiWindowModeChanged(boolean isInMultiWindowMode, Configuration newConfig) {
+		// onConfigurationChanged not called on multi-window change
+		Log.i(TAG, "onMultiWindowModeChanged: isInMultiWindowMode = " + isInMultiWindowMode);
+		super.onMultiWindowModeChanged(isInMultiWindowMode, newConfig);
+		updateDisplayMeasurements();
```
Comment (unknownbrackets) [inline android/src/org/ppsspp/ppsspp/NativeActivity.java]: Hm, in theory we want the `densityDpi` from newConfig, though we don't seem to call `NativeApp.setDisplayParameters` in `onConfigurationChanged` so it's probably already wrong in cases.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]
This definitely seems to fix the issues with immersive on startup for me.  Tried different cases, and everything checked out.

That said, I don't have any older devices to validate against.

-[Unknown]

**Comment by hrydgard** [comment]
I'm gonna go ahead and merge this, and test more on older devices later.

File: android/src/org/ppsspp/ppsspp/NativeActivity.java [hunk 2]
```diff
@@ -568,7 +573,6 @@ public void surfaceCreated(SurfaceHolder holder) {
 		}
 
 		Log.d(TAG, "Surface created. pixelWidth=" + pixelWidth + ", pixelHeight=" + pixelHeight + " holder: " + holder.toString() + " or: " + requestedOr);
-		NativeApp.setDisplayParameters(pixelWidth, pixelHeight, (int) densityDpi, refreshRate);
```
Comment (weihuoya) [inline android/src/org/ppsspp/ppsspp/NativeActivity.java]: there is a issue in latest version, touch zone doesn't match it's display position.
add back this line will fix it.
test on Mi9, Android Q.

Comment (hrydgard) [reply android/src/org/ppsspp/ppsspp/NativeActivity.java]: Thanks! I'll give that a shot, but so far every change we've done in this area has both fixed something and broken something else..
