### PR TITLE
Fix Syphon Filter lens flares by adding compat flag to read back the depth buffer 

### LINKED ISSUE #10229: Syphon Filter Dark Mirror - lights are visible through buildings
What happens?
You can see the sources of lights through buildings (e.g lamps, ground reflections, etc)
It's a minor issue and the game's perfectly playable. I was just wondering if you could improve it.

What *should* happen?
I'm not sure if the game's meant to be like this or not because I don't own an actual PSP. But I think it shouldn't be like this.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
GPU: Adreno 530
PPSSPP Build: 1.5.3

### PR DESCRIPTION
**Pull request by hrydgard**
This fixes the lens flare occlusion in the Syphon Filter games by reading back the depth buffer from the GPU so that the checks that the game performs work, if a compat flag is set, making these games feel way more "solid" and playable - the flares really were quite distracting. Fixes #10229. Fixes one part of #15923.

Unfortunately, it also slows things down quite drastically on mobile, at least, unless you use the speedhack "Skip GPU readbacks" which will turn this off. 

The heuristic about which framebuffer to read from are quite basic too, I have plans to detect that in a safer way, but this does seem to be good enough for these games in particular.

Later I plan to introduce some tricks from #16900 to get the speed back up even with readbacks enabled (though occlusion will be delayed a frame or two, it'll hardly be noticeable).

### CODE REVIEW

**Comment by Danielet89** [comment]
Is possible fix this Aldo for infra ppspp android & windows? So will fix also on multiplayer games ?

**Comment by hrydgard** [comment]
I'm not sure what you mean, this fix is not related to muliplayer functionality in any way

File: GPU/Common/FramebufferManagerCommon.cpp [hunk 1]
```diff
@@ -1015,14 +1010,48 @@ void FramebufferManagerCommon::NotifyRenderFramebufferUpdated(VirtualFramebuffer
...
+	// Download depth buffer for Syphon Filter lens flares
+	if (!PSP_CoreParameter().compat.flags().ReadbackDepth || g_Config.bSkipGPUReadbacks) {
+		return false;
+	}
+	return (vfb->usageFlags & FB_USAGE_RENDER_DEPTH) != 0 && vfb->width >= 480 && vfb->height >= 272;
+}
+
 void FramebufferManagerCommon::NotifyRenderFramebufferSwitched(VirtualFramebuffer *prevVfb, VirtualFramebuffer *vfb, bool isClearingDepth) {
-	if (ShouldDownloadFramebuffer(vfb) && !vfb->memoryUpdated) {
+	// TODO: Isn't this wrong? Shouldn't we download the prevVfb if anything?
```
Comment (unknownbrackets) [inline GPU/Common/FramebufferManagerCommon.cpp:1043]: Probably, I think it didn't have prevVfb as a parameter before and this worked well enough.  Maybe this was a consideration for performance?  Not sure if it's cheaper to download framebuffer B after rendering to A.

For Danganronpa, anyway, it renders its scenemap every frame iirc.

-[Unknown]

File: GPU/Common/FramebufferManagerCommon.cpp [hunk 2]
```diff
@@ -1015,14 +1010,48 @@ void FramebufferManagerCommon::NotifyRenderFramebufferUpdated(VirtualFramebuffer
...
+	if (ShouldDownloadFramebufferColor(vfb) && !vfb->memoryUpdated) {
 		ReadFramebufferToMemory(vfb, 0, 0, vfb->width, vfb->height, RASTER_COLOR);
 		vfb->usageFlags = (vfb->usageFlags | FB_USAGE_DOWNLOAD | FB_USAGE_FIRST_FRAME_SAVED) & ~FB_USAGE_DOWNLOAD_CLEAR;
 	} else {
 		DownloadFramebufferOnSwitch(prevVfb);
 	}
 
+	if (prevVfb && ShouldDownloadFramebufferDepth(prevVfb)) {
```
Comment (unknownbrackets) [inline GPU/Common/FramebufferManagerCommon.cpp:1051]: I guess we could skip this if `isClearingDepth`... not sure if Syphon Filter does that.

-[Unknown]

Comment (hrydgard) [reply GPU/Common/FramebufferManagerCommon.cpp:1051]: Well the point of this is to download the framebuffer *after* it's been renderered to, here we're switching from prevVfb to vfb, so the right check would be if depth has been written during the pass I guess.. Clearing doesn't really enter into the equestion, or am I missing something?

File: GPU/Common/FramebufferManagerCommon.cpp (hunk 1 above)
Comment (hrydgard) [reply GPU/Common/FramebufferManagerCommon.cpp:1043]: But it's really a curious time to download vfb given that this is when we *start* rendering to it, isn't it? Though of course, in a way that's fine, we'll just be one frame behind on the readbacks...

File: GPU/Common/FramebufferManagerCommon.cpp (hunk 2 above)
Comment (unknownbrackets) [reply GPU/Common/FramebufferManagerCommon.cpp:1051]: Oh right sorry, I was mixing in the wrong vfb comment and forgot this is checking prevVfb.

-[Unknown]

File: GPU/Common/FramebufferManagerCommon.cpp (hunk 1 above)
Comment (unknownbrackets) [reply GPU/Common/FramebufferManagerCommon.cpp:1043]: Well, it's only really being used for Danganronpa, which is a game that - at least for these scenemap readbacks - would probably be totally fine with async readbacks.

-[Unknown]
