### PR TITLE
Fix green flashes with Burnout Dominator lens flare

### LINKED ISSUE #16075: Lens flare effect green flash, corrupt FMVs
### Game or games this happens in

Burnout dominator, need for speed shift, maybe more

### What area of the game

During full motion videos before racing, also lens flare has green boxes in it briefly.

### What happens

Full motion videos have digital artifact errors/ random digital error squares, sometimes almost covering complete screen.  Lens flare has momentary green squares in it.  Best seen when viewing car model at car selection screen and rotating car.  I believe the developer said this was caused by not implementing Z-upload.

### What should happen

Videos should play back perfect.  Lens flare effect shouldn't have green boxes in it briefly.

### GE frame capture

_No response_

### Platform

Android 11

### Mobile phone model or graphics card

OnePlus 7t with adreno 640.

### PPSSPP version affected

1.13.2 1091

### Last working version

Dunno

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #16075 

Checking the CLUT-usage flag is a frame too late when the buffer is just created (which does happen quite often, since we aggressively delete unused framebuffers and the lens flare is not always on screen).

Additionally, the color buffer copy to the CLUT buffer causes a resize, where we used to lose the Z buffer, so it would be gone anyway the first frame. This fixes that by copying the depth buffer in this case. Hopefully won't slow anything else down noticeably.

### CODE REVIEW

File: GPU/Common/FramebufferManagerCommon.cpp [hunk 1]
```diff
@@ -547,27 +547,24 @@ void FramebufferManagerCommon::SetDepthFrameBuffer(bool isClearingDepth) {
...
 	// by copying from any overlapping buffers with fresher content.
-	if (!isClearingDepth) {
+	if (!isClearingDepth && useBufferedRendering_) {
 		CopyToDepthFromOverlappingFramebuffers(currentRenderVfb_);
 
-		// Special compatibility trick for Burnout Dominator lens flares. Not sure how to best generalize this. See issue #11100
-		if (PSP_CoreParameter().compat.flags().UploadDepthForCLUTTextures && (currentRenderVfb_->usageFlags & FB_USAGE_CLUT) != 0) {
-			// Set the flag, then upload memory contents to depth channel.
+		// Special compatibility trick for Burnout Dominator lens flares. See issue #11100
+		if (PSP_CoreParameter().compat.flags().UploadDepthForCLUTTextures && currentRenderVfb_->z_address > 0x04110000) {
```
Comment (unknownbrackets) [inline GPU/Common/FramebufferManagerCommon.cpp:559]: What if we did this only when `vfb->lastFrameNewSize == gpuStats.numFlips` rather than based on the z_address?  Would that work?

We do PerformStencilUpload / PerformMemoryUpload when creating a framebuf, I don't think it'd be so awful to also upload depth, and might allow it to be more generic.

-[Unknown]

Comment (hrydgard) [reply GPU/Common/FramebufferManagerCommon.cpp:559]: Hm, I could try that. I guess since the Z buffer is static, only uploading it on create/resize would work. I previously tried uploading it on create and it didn't work, but I didn't realize then that it was because the resize later ruined it...
