### PR TITLE
EGL: Avoid HDR mode. Uses unknownbrackets' changes from #11839.

### LINKED ISSUE #11839: EGL_BAD_MATCH (0x3009) on Mali G52
I've been trying to make PPSSPP run on an Odroid N2, I-ve compiled it and it runs but it gives me this error

```
/SDL/SDLGLGraphicsContext.cpp at line 187: EGL_BAD_MATCH (0x3009)
EGL ERROR: Unable to create EGL surface!
I: gpu_features.cpp:171: GPU Vendor : ARM ; renderer: Mali-G52 version str: OpenGL ES 3.2 git.db77a4c.74502ed16b0fc2da36c811f236840b85 ; GLSL version str: OpenGL ES GLSL ES 3.20
I: gpu_features.cpp:288: OpenGL ES 3.1 support detected!

```
I can hear the game playing in the background but nothing on the screen.
Other emulators seem to run with GLES 2.0 but PPSSPP doesn't even show it on that line.
is there a way to force PPSSPP to use GLES 2.0? so I can test if this is the problem?

Not sure what EGL_BAD_MATCH means but any help will be appreciated. 

### What happens?
Black screen on Mali-G52

### What *should* happen?
Run the game or display the PPSSPP GUI

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
CoreELEC running on Odroid N2 , GPU mali-G52

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #11839 .

### CODE REVIEW

File: SDL/SDLGLGraphicsContext.cpp [hunk 1]
```diff
@@ -120,6 +125,11 @@ EGLConfig EGL_FindConfig(int *contextVersion) {
 		EGLint caveat = readConfig(EGL_CONFIG_CAVEAT);
 		int caveatScore = caveat == EGL_NONE ? 100 : (caveat == EGL_NON_CONFORMANT_CONFIG ? 50 : 0);
 
+#ifndef USING_FBDEV
+		EGLint surfaceType = readConfig(EGL_SURFACE_TYPE);
+		int surfaceScore = (surfaceType & EGL_WINDOW_BIT) ? 100 : (caveat == EGL_NON_CONFORMANT_CONFIG ? 50 : 0);
```
Comment (unknownbrackets) [inline SDL/SDLGLGraphicsContext.cpp]: Hmm, wait, this might accidentally boost non-conformant configs?  Copy/paste mistake?

-[Unknown]

Comment (hrydgard) [reply SDL/SDLGLGraphicsContext.cpp]: Yeah I just took it verbatim from your post :) You're right that this might not be great..
