### PR TITLE
Cache framebuffer copies (for self-texturing) until the next TexFlush GPU instruction

### LINKED ISSUE #17030: Dante's Inferno buffer copy performance problem
Broken out from #16638 .

Dante is doing one of those blooms where it textures from one part of a framebuffer while drawing to another part of the same one, leading to copies. However, a lot of these copies are unnecessary since multiple draws are often executed where the source region does not overlap the destination., still we end up doing separate framebuffer copies per draw, which is very expensive since there are so many.

I believe there are a few other games similarly affected to various degrees.

The framebuffer where this processing happens is located at 110000, and it starts by doing a single draw into it, downscaling the main framebuffer which is located at 44000 or 00000, alternately. Then a sequence of draws start where texaddr = 110000 and framebuffer addr too, which is what we're talking about here, around draw 250-ish in the first scene.

Conveniently, these draws are all done in through mode, making it easy to keep track of texture and vertex coordinates without having to bother with transforms. So concievably, we could do dirty-rectangle tracking here.

Now, it does seem like some of these flushes could be skipped, which would reduce the need for said tracking. I haven't quite tracked down exactly why all of them happen yet.

This is one that gets triggered, for example:

```
	if (prim == GE_PRIM_RECTANGLES && (gstate.getTextureAddress(0) & 0x3FFFFFFF) == (gstate.getFrameBufAddress() & 0x3FFFFFFF)) {
		// Rendertarget == texture? Shouldn't happen. Still, try some mitigations.
		gstate_c.Dirty(DIRTY_TEXTURE_PARAMS);
		DispatchFlush();
	}
```

But, the game actually helpfully does a CB000000 (TexFlush) instruction when this flush actually needs to happen (texturing from a part of the framebuffer that's just been drawn to), so maybe we could rely on that instead - causing a flush directly from that in this case.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #17030 , or at least improves on it - for optimal performance that big framebuffer used for bloom should be split like in Killzone, but it's not trivial. So there's still a bunch of copies happening, just less of them.

The performance regression in Dante's Inferno in 1.14 is fixed with this, at least.

I tried it with a few other games with no issues - it seems games are using TexFlush when needed. But let's see if it really is safe to rely on that...

There might also be other places we should call DiscardFramebufferCopy in.

For these copies, ideally we should look at texture coordinates to figure out the regions to copy, and if the previously copied region was enough. Actually we do that already, in some cases - and I just realized that this isn't necessarily valid in that case. So need a couple more checks. EDIT: Added - works because that path isn't currently active in Dante for some reason.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Hm, this seems slightly dangerous but maybe okay.  I did have reason to believe people's assertions about texsync or texflush were a bit off, but I think it was texsync.

Let me check in a couple games, though.  Especially concerned about Motorstorm for example.

-[Unknown]

File: GPU/Common/FramebufferManagerCommon.cpp [hunk 1]
```diff
@@ -1262,14 +1280,17 @@ bool FramebufferManagerCommon::BindFramebufferAsColorTexture(int stage, VirtualF
...
 	int x = 0;
 	int y = 0;
 	int w = src->drawnWidth;
 	int h = src->drawnHeight;
 
+	*partial = false;
+
 	// If max is not > min, we probably could not detect it.  Skip.
 	// See the vertex decoder, where this is updated.
+	// TODO: We're currently not hitting this path in Dante. See #17032
```
Comment (unknownbrackets) [inline GPU/Common/FramebufferManagerCommon.cpp:1293]: It's probably not using vertex coords that get checked, so maxU probably equals minU.  We don't currently set the range for all vertex types, just 16-bit through iirc.  This has been true forever, initially to avoid any perf impact to vertex decode for the few games this was initially helping.

-[Unknown]

**Review by unknownbrackets — COMMENTED** [review]
I think we need to discard in a few more situations, let me see real quick...

-[Unknown]

File: GPU/Common/FramebufferManagerCommon.cpp (hunk 1 above)
Comment (hrydgard) [reply GPU/Common/FramebufferManagerCommon.cpp:1294]: Ah, right. Possibly it would always be worth it to find the min/max in through mode, although then this change would need more sophistication. So, maybe one day :)

**Comment by hrydgard** [comment]
I'm gonna go for it, easy to revert if it causes problems, but it doesn't really seem to.

As mentioned, future work will include tracking the affected areas more accurately.
