### PR TITLE
Band-Aid for libretro Savestate load

### LINKED ISSUE #11429: RetroArch crashes when loading PPSSPP savestates
RetroArch crashes whenever I load a PPSSPP savestate. The loading state message shows up, stops at 50-70%, and then it crashes without an error message. Happens in all games I tested. Closer to not crashing I've come is Megaman Maverick Hunter, where instead of crashing loading a state shows the background layer and hangs the game.

I'm using RetroArch 1.7.4, PPSSPP core 9c9432e, Win 10 17134.286, and OpenGL render.

### PR DESCRIPTION
**Pull request by m4xw**
Proper would be using PPSSPP's Queue.
This will need frontend extensions to do it sanely.
Fixes #11429 (mitigate for now)

### CODE REVIEW

File: libretro/libretro.cpp [hunk 1]
```diff
@@ -705,19 +714,32 @@ struct SaveStart {
 } // namespace SaveState
 
 size_t retro_serialize_size(void) {
+	// Not pausing the EmuThread here should be somewhat safe, for the time being
```
Comment (hrydgard) [inline libretro/libretro.cpp]: If retro_serialize_size and retro_serialize are called together to find out the size of memory and then serialize, you should try to get them inside the same "EmuThreadPause/EmuThreadStart" block...

Comment (m4xw) [reply libretro/libretro.cpp]: I did consider just pausing it there and then remove the pause from serialize (or just leaving it since it already checks if its paused), but I wouldn't be able to continue there, because it would advance the frames.
It's the same issue in the other serialize functions, EmuThreadPause will advance by a frame, so it's already guaranteed to be out of sync.
The real question is if the Savestate Buffer ever shrinks, since only that should cause actual Issues?
Alternative is a hard crash right now, either way.
But I can look into that after work if you want.

Comment (m4xw) [reply libretro/libretro.cpp]: Now that I think about it, I should probably wrap them in if(useEmuThread) too, since it's only enabled for GL it seems.
It should be required for all renderer`'s anyway, right?

**Comment by unknownbrackets** [comment]
Hmm looking at this again, I'd suggest using Core_EnableStepping.  That would work on all backends.  Stepping is in other words debugging, and while debugging the CPU is paused regardless of thread behavior.

Example:

```c++
static serializeWasStepping = false;

size_t retro_serialize_size(void) {
	serializeWasStepping = Core_IsStepping();
	Core_EnableStepping(true);
	// If we're on the CPU thread actually, this may just stall for 16ms...
	Core_WaitInactive(16);

	// Intentionally leaving in stepping.
	// TODO: Not sure if 0x800000 alignment is necessary (that's 8MB.)
	return CChunkFileReader::MeasurePtr(state);
}

bool retro_serialize(void *data, size_t size) {
	if (Core_IsActive()) {
		ERROR_LOG(SYSTEM, "retro_serialize_size() must be called before retro_serialize()");
		return false;
	}
	if (size < CChunkFileReader::MeasurePtr(state)) {
		ERROR_LOG(SYSTEM, "retro_serialize() called with too small a size");
		return false;
	}

	bool retVal = CChunkFileReader::SavePtr(...);

	if (!serializeWasStepping) {
		Core_EnableStepping(false);
		// No need to wait for active, it'll resume on its own.
	}

	return retVal;
}
```

That said, probably doing this thread pausing stuff will work too, at least for GL.  Would have to save the std::thread id or something and compare to know if `Core_WaitInactive` needs to be called, I suppose.

-[Unknown]

**Comment by hrydgard** [comment]
Merging as-is because the workaround apparently is highly in demand - @m4xw has promised to try and switch to EnableStepping later.

**Comment by orbea** [comment]
@m4xw Thanks a lot for taking time to work on ppsspp issues!

**Comment by NeoNight1986** [comment]
I am pretty confused, what do I need to do to fix the safe state freezing?
