### PR TITLE
NFS speed effect: Improve framebuffer match logging, tighten up stride checks.

### LINKED ISSUE #15940: Need for Speed - Most wanted: Graphics glitch when going fast
There's an apparently depth-dependent screen overlay that appears when you go really fast, it looks like a broken gradient typical of depth->565 or similar. Noticed when trying (and failing) to reproduce #15788 ..

image

### PR DESCRIPTION
**Pull request by hrydgard**
Checking byte strides is a lot more relevant than pixel strides for matching purposes, and thus we can be a bit "harsher" with them.

Fixes #15940 . Tested a bunch of other games with tricky framebuffer effects, still working.

### CODE REVIEW

File: GPU/Common/TextureCacheCommon.cpp [hunk 1]
```diff
@@ -906,9 +922,8 @@ bool TextureCacheCommon::MatchFramebuffer(
 
 	// If they match "exactly", it's non-CLUT and from the top left.
 	if (exactMatch) {
-		// TODO: Better checks for compatible strides here.
-		if (fb_stride != entry.bufw) {
-			WARN_LOG_ONCE(diffStrides1, G3D, "Found matching framebuffer at %08x with different strides %d != %d", fb_address, entry.bufw, (int)fb_stride);
+		if (fb_stride_in_bytes != tex_stride_in_bytes && TextureFormatMatchesBufferFormat(entry.format, fb_format)) {
```
Comment (unknownbrackets) [inline GPU/Common/TextureCacheCommon.cpp:925]: Isn't this impossible?  `exactMatch` will always be false if the byte stride doesn't match, now.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]

File: GPU/Common/TextureCacheCommon.cpp (hunk 1 above)
Comment (hrydgard) [reply GPU/Common/TextureCacheCommon.cpp:925]: Oops, yeah, this whole check can definitely be removed
