### PR TITLE
 Qt: Re-enable Load button to browse for file

### LINKED ISSUE #11721: Mac OS (Qt build) crashes when clicked Load...
### What happens?
When clicked "Load..." on the main screen PPSSPP crashes

### What *should* happen?
It shouldn't crash :P

Here's the crash log ( by Mac OS ):

```
Process:               PPSSPPQt [32123]
Path:                  /Users/USER/Desktop/PPSSPPQt.app/Contents/MacOS/PPSSPPQt
Identifier:            ???
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PPSSPPQt [32123]
User ID:               502

Date/Time:             2019-01-07 14:20:15.145 +0400
OS Version:            Mac OS X 10.14.2 (18C54)
Report Version:        12
Anonymous UUID:        5792B43B-091F-5A78-178C-5DA363EF321C

Sleep/Wake UUID:       6D8970E2-6D8A-48CB-9A17-D565CCBBC091

Time Awake Since Boot: 85000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        3  Emu

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff4bef8ecd __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff77fb4720 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff4bf1295d -[NSException raise] + 9
3   AppKit                              0x00007fff49413c8e -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
4   AppKit                              0x00007fff4941107c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
5   AppKit                              0x00007fff494d195b -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
6   AppKit                              0x00007fff49410aa6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
7   AppKit                              0x00007fff494d1910 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
8   AppKit                              0x00007fff49b0dd8f -[NSSavePanel initWithContentRect:styleMask:backing:defer:] + 587
9   AppKit                              0x00007fff496e8bc0 +[NSSavePanel _crunchyRawUnbonedPanel] + 550
10  libqcocoa.dylib                     0x00000001085618f7 _ZN20QCocoaSystemTrayIcon11showMessageERK7QStringS2_RK5QIconN23QPlatformSystemTrayIcon11MessageIconEi + 94967
11  libqcocoa.dylib                     0x0000000108565ef4 _ZN20QCocoaSystemTrayIcon11showMessageERK7QStringS2_RK5QIconN23QPlatformSystemTrayIcon11MessageIconEi + 112884
12  libqcocoa.dylib                     0x0000000108565d61 _ZN20QCocoaSystemTrayIcon11showMessageERK7QStringS2_RK5QIconN23QPlatformSystemTrayIcon11MessageIconEi + 112481
13  QtWidgets                           0x00000001053fb5c8 _ZN14QDialogPrivate22setNativeDialogVisibleEb + 152
14  QtWidgets                           0x000000010540778e _ZN11QFileDialog10setVisibleEb + 94
15  QtWidgets                           0x00000001053fbf50 _ZN7QDialog4execEv + 240
16  QtWidgets                           0x000000010540c0c7 _ZN11QFileDialog14getOpenFileUrlEP7QWidgetRK7QStringRK4QUrlS4_PS2_6QFlagsINS_6OptionEERK11QStringList + 359
17  QtWidgets                           0x000000010540bea5 _ZN11QFileDialog15getOpenFileNameEP7QWidgetRK7QStringS4_S4_PS2_6QFlagsINS_6OptionEE + 245
18  PPSSPPQt                            0x0000000103a01db5 _ZN10MainScreen10OnLoadFileERN2UI11EventParamsE + 165
19  PPSSPPQt                            0x0000000103dc698c _ZN2UI14DispatchEventsEv + 444
20  PPSSPPQt                            0x0000000103dd8862 _ZN2UI19UpdateViewHierarchyEPNS_9ViewGroupE + 1474
21  PPSSPPQt                            0x0000000103a025ce _ZN10MainScreen6updateEv + 14
22  PPSSPPQt                            0x0000000103db829f _ZN13ScreenManager6updateEv + 63
23  PPSSPPQt                            0x00000001039c15aa _Z12NativeUpdatev + 234
24  PPSSPPQt                            0x0000000103ad9a0a _Z13UpdateRunLoopv + 42
25  PPSSPPQt                            0x000000010399a44d _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN6MainUI14EmuThreadStartEvE3$_0EEEEEPvSA_ + 93
26  libsystem_pthread.dylib             0x00007fff79276305 _pthread_body + 126
27  libsystem_pthread.dylib             0x00007fff7927926f _pthread_start + 70
28  libsystem_pthread.dylib             0x00007fff79275415 thread_start + 13

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff791bc17a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff791bc6d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff4be420c2 __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff4be41611 __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff4be40d48 CFRunLoopRunSpecific + 463
5   com.apple.HIToolbox           	0x00007fff4b0d7ab5 RunCurrentEventLoopInMode + 293
6   com.apple.HIToolbox           	0x00007fff4b0d77eb ReceiveNextEventCommon + 618
7   com.apple.HIToolbox           	0x00007fff4b0d7568 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff49392363 _DPSNextEvent + 997
9   com.apple.AppKit              	0x00007fff49391102 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
10  com.apple.AppKit              	0x00007fff4938b165 -[NSApplication run] + 699
11  libqcocoa.dylib               	0x000000010852d25b 0x108500000 + 184923
12  org.qt-project.QtCore         	0x0000000105eb961f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
13  org.qt-project.QtCore         	0x0000000105ebe5c2 QCoreApplication::exec() + 130
14                                	0x0000000103999d26 main + 1366
15  libdyld.dylib                 	0x00007fff79082ed9 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff792753f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff792753f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 3 Crashed:: Emu
0   libsystem_kernel.dylib        	0x00007fff791c223e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff79278c1c pthread_kill + 285
2   libsystem_c.dylib             	0x00007fff7912b1c9 abort + 127
3   libc++abi.dylib               	0x00007fff767ac231 abort_message + 231
4   libc++abi.dylib               	0x00007fff767ac3cd default_terminate_handler() + 265
5   libobjc.A.dylib               	0x00007fff77fb6c87 _objc_terminate() + 97
6   libc++abi.dylib               	0x00007fff767b7dfe std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff767b7be2 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	0x00007fff767aabb9 __cxa_throw + 113
9   libobjc.A.dylib               	0x00007fff77fb485a objc_exception_throw + 362
10  com.apple.CoreFoundation      	0x00007fff4bf1295d -[NSException raise] + 9
11  com.apple.AppKit              	0x00007fff49413c8e -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
12  com.apple.AppKit              	0x00007fff4941107c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
13  com.apple.AppKit              	0x00007fff494d195b -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
14  com.apple.AppKit              	0x00007fff49410aa6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
15  com.apple.AppKit              	0x00007fff494d1910 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
16  com.apple.AppKit              	0x00007fff49b0dd8f -[NSSavePanel initWithContentRect:styleMask:backing:defer:] + 587
17  com.apple.AppKit              	0x00007fff496e8bc0 +[NSSavePanel _crunchyRawUnbonedPanel] + 550
18  libqcocoa.dylib               	0x00000001085618f7 0x108500000 + 399607
19  libqcocoa.dylib               	0x0000000108565ef4 0x108500000 + 417524
20  libqcocoa.dylib               	0x0000000108565d61 0x108500000 + 417121
21  org.qt-project.QtWidgets      	0x00000001053fb5c8 QDialogPrivate::setNativeDialogVisible(bool) + 152
22  org.qt-project.QtWidgets      	0x000000010540778e QFileDialog::setVisible(bool) + 94
23  org.qt-project.QtWidgets      	0x00000001053fbf50 QDialog::exec() + 240
24  org.qt-project.QtWidgets      	0x000000010540c0c7 QFileDialog::getOpenFileUrl(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) + 359
25  org.qt-project.QtWidgets      	0x000000010540bea5 QFileDialog::getOpenFileName(QWidget*, QString const&, QString const&, QString const&, QString*, QFlags<QFileDialog::Option>) + 245
26                                	0x0000000103a01db5 MainScreen::OnLoadFile(UI::EventParams&) + 165
27                                	0x0000000103dc698c UI::DispatchEvents() + 444
28                                	0x0000000103dd8862 UI::UpdateViewHierarchy(UI::ViewGroup*) + 1474
29                                	0x0000000103a025ce MainScreen::update() + 14
30                                	0x0000000103db829f ScreenManager::update() + 63
31                                	0x00000001039c15aa NativeUpdate() + 234
32                                	0x0000000103ad9a0a UpdateRunLoop() + 42
33                                	0x000000010399a44d void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, MainUI::EmuThreadStart()::$_0> >(void*) + 93
34  libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
35  libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
36  libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 4:: PrioQueue
0   libsystem_kernel.dylib        	0x00007fff791bf7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff79279593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff76758bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3                                 	0x0000000103db602b PrioritizedWorkQueue::Pop() + 187
4                                 	0x0000000103db6431 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ProcessWorkQueueOnThreadWhile(PrioritizedWorkQueue*)::$_0> >(void*) + 81
5   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
7   libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff791bf7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff79279593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff76758d01 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
3                                 	0x0000000104479e7e IoThreadHolder::Start()::'lambda'()::operator()() const + 174
4                                 	0x0000000104479d5d void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, IoThreadHolder::Start()::'lambda'()> >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
7   libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 6:: SDLAudioP1
0   libsystem_kernel.dylib        	0x00007fff791bc17a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff791bc6d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff4be420c2 __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff4be41611 __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff4be40d48 CFRunLoopRunSpecific + 463
5   libSDL2-2.0.0.dylib           	0x0000000105131a40 COREAUDIO_WaitDevice + 73
6   libSDL2-2.0.0.dylib           	0x00000001050908c5 SDL_RunAudio + 415
7   libSDL2-2.0.0.dylib           	0x00000001050d09b5 SDL_RunThread + 60
8   libSDL2-2.0.0.dylib           	0x0000000105130aa7 RunThread + 9
9   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
10  libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
11  libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff791bc17a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff791bc6d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff4be420c2 __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff4be41611 __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff4be40d48 CFRunLoopRunSpecific + 463
5   com.apple.AppKit              	0x00007fff4939af89 _NSEventThread + 160
6   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 8:: AQConverterThread
0   libsystem_kernel.dylib        	0x00007fff791bf7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff79279593 _pthread_cond_wait + 724
2   com.apple.audio.toolbox.AudioToolbox	0x00007fff4a75314b CAGuard::Wait() + 73
3   com.apple.audio.toolbox.AudioToolbox	0x00007fff4a74f16e AQConverterManager::AQConverterThread::Run() + 390
4   com.apple.audio.toolbox.AudioToolbox	0x00007fff4a74efdd AQConverterManager::AQConverterThread::ConverterThreadEntry(void*) + 9
5   com.apple.audio.toolbox.AudioToolbox	0x00007fff4a72c85b CAPThread::Entry(CAPThread*) + 77
6   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 9:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff791bc17a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff791bc6d0 mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff4b89189a HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 124
3   com.apple.audio.CoreAudio     	0x00007fff4b89180d HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff4b88db84 HALC_ProxyIOContext::IOWorkLoop() + 988
5   com.apple.audio.CoreAudio     	0x00007fff4b88d5ee HALC_ProxyIOContext::IOThreadEntry(void*) + 128
6   com.apple.audio.CoreAudio     	0x00007fff4b88d0d6 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
9   libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff792753f8 start_wqthread + 0

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff791bc1ce semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff7903542c _dispatch_sema4_timedwait + 76
2   libdispatch.dylib             	0x00007fff79035b1d _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff79042b66 _dispatch_worker_thread + 328
4   libsystem_pthread.dylib       	0x00007fff79276305 _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff7927926f _pthread_start + 70
6   libsystem_pthread.dylib       	0x00007fff79275415 thread_start + 13

Thread 3 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000ae1c000  rcx: 0x000070000ae19fb8  rdx: 0x0000000000000000
  rdi: 0x0000000000009017  rsi: 0x0000000000000006  rbp: 0x000070000ae19ff0  rsp: 0x000070000ae19fb8
   r8: 0x000070000ae19e78   r9: 0x000070000ae1a050  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000009017  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff791c223e  rfl: 0x0000000000000206  cr2: 0x00007fffabe69188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x103993000 -        0x104922ff7 + (??? - ???) <D2C3119C-ACF2-394F-8F48-9A16C5EE1D3B> /Users/USER/Desktop/PPSSPPQt.app/Contents/MacOS/PPSSPPQt
       0x105086000 -        0x10515bfff +libSDL2-2.0.0.dylib (0) <11AC96F6-27CA-3A86-A0D8-4F255A4BE9F8> /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
       0x105199000 -        0x1051cdfff +org.qt-project.QtOpenGL (5.12 - 5.12.0) <BB69458B-7136-3A8B-98AA-3D3E70DECD99> /usr/local/opt/qt/lib/QtOpenGL.framework/Versions/5/QtOpenGL
       0x1051f0000 -        0x10562cff7 +org.qt-project.QtWidgets (5.12 - 5.12.0) <75936810-FE79-3F53-9013-A0C94ACF28F0> /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets
       0x105790000 -        0x105bceff7 +org.qt-project.QtGui (5.12 - 5.12.0) <3217263A-A322-3A1E-9C45-879E8FF90ABD> /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui
       0x105cd5000 -        0x106203ff7 +org.qt-project.QtCore (5.12 - 5.12.0) <56C531B9-76EF-3D6A-B181-32AF86E8E067> /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore
       0x108500000 -        0x108659fff +libqcocoa.dylib (0) <325894FF-021E-339C-AE13-B56B1E0BABBA> /usr/local/Cellar/qt/5.12.0/plugins/platforms/libqcocoa.dylib
       0x1086a2000 -        0x108700ff3 +org.qt-project.QtDBus (5.12 - 5.12.0) <773D6959-60AB-30E0-8042-8CC13038A2E3> /usr/local/Cellar/qt/5.12.0/lib/QtDBus.framework/Versions/5/QtDBus
       0x108719000 -        0x108742ff7 +org.qt-project.QtPrintSupport (5.12 - 5.12.0) <D9915B6C-0F8D-3C3D-A206-CE5A6EE78FB7> /usr/local/Cellar/qt/5.12.0/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x108e71000 -        0x108eefa67  dyld (640.2) <289AB27E-F09F-3384-A14A-100431139559> /usr/lib/dyld
       0x10ae7c000 -        0x10aea0fff +libqmacstyle.dylib (0) <4ABC2B6E-B7A4-31B0-A7D1-29E86529E62C> /usr/local/Cellar/qt/5.12.0/plugins/styles/libqmacstyle.dylib
       0x10aee1000 -        0x10aee4047  libobjc-trampolines.dylib (750.1) <0D004834-E2EB-3066-8598-6F413521157F> /usr/lib/libobjc-trampolines.dylib
       0x10b32d000 -        0x10b333ff3 +libqgif.dylib (0) <0F7F452C-0B1F-380C-8179-995B5A971A16> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqgif.dylib
       0x10b337000 -        0x10b33effb +libqicns.dylib (0) <F355B873-288A-3084-9C63-AE29206B383E> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqicns.dylib
       0x10b343000 -        0x10b348ff3 +libqico.dylib (0) <85461501-CC30-3EAE-BF61-E9816FDE8822> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqico.dylib
       0x10b34d000 -        0x10b3b0ffb +libqjpeg.dylib (0) <845D482E-E424-3AD8-AE89-3E72898A458F> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqjpeg.dylib
       0x10b3b6000 -        0x10b3baff7 +libqmacheif.dylib (0) <DB53AC3D-8EB1-3E72-81AD-FE62CECC376F> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqmacheif.dylib
       0x10b3be000 -        0x10b3c2ff7 +libqmacjp2.dylib (0) <8E37FE73-FC82-3B94-9A14-C3A047933355> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqmacjp2.dylib
       0x10b3c6000 -        0x10b3cafff +libqsvg.dylib (0) <EAFE3395-BDCC-3A5F-ADD5-C6BA308AA224> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqsvg.dylib
       0x10b3cf000 -        0x10b402ff3 +org.qt-project.QtSvg (5.12 - 5.12.0) <68DF2C7E-B1D0-38C3-B618-28FC22805834> /usr/local/Cellar/qt/5.12.0/lib/QtSvg.framework/Versions/5/QtSvg
       0x10b41e000 -        0x10b422ffb +libqtga.dylib (0) <5C974350-42F8-30EE-A433-30CD2BBFE97C> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqtga.dylib
       0x10b426000 -        0x10b489ff3 +libqtiff.dylib (0) <044FB145-6D8E-3E50-AE7F-33EB12759540> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqtiff.dylib
       0x10b491000 -        0x10b494ff3 +libqwbmp.dylib (0) <7482390B-CE3B-36A0-8FEE-FA8E1CBBFEAF> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqwbmp.dylib
       0x10b498000 -        0x10b52cff3 +libqwebp.dylib (0) <B5F2E2D8-6047-361A-A973-E30E27988B25> /usr/local/Cellar/qt/5.12.0/plugins/imageformats/libqwebp.dylib
       0x10e0f0000 -        0x10e0fdff7  com.apple.iokit.IOHIDLib (2.0.0 - 2.0.0) <BE49E85C-0BF3-36FF-8D63-CFDD20F11C95> /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib
       0x10eb90000 -        0x10eb94fff  com.apple.audio.AppleHDAHALPlugIn (282.10 - 282.10) <8C1742CF-F0B3-3321-9918-F5237B84CF5A> /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
       0x10f00f000 -        0x10f1b4ff7  com.apple.audio.units.Components (1.14 - 1.14) <A7E7DE74-B219-308E-8177-7F1AC561DB93> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
    0x7fff41c5c000 -     0x7fff41c5dff3  libLatin5Converter.dylib (73) <D68A8F7A-99F0-31E9-9B02-68C48A6EC592> /System/Library/CoreServices/Encodings/libLatin5Converter.dylib
    0x7fff41c9d000 -     0x7fff42016fff  com.apple.RawCamera.bundle (8.11.0 - 1031.1.3) <15BB3751-9084-381A-8D25-5C60695C292A> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff4334d000 -     0x7fff43872fff  com.apple.driver.AppleIntelBDWGraphicsGLDriver (12.4.7.1 - 12.0.4) <01DA8E2A-C894-33E8-B27A-1506147E1BA7> /System/Library/Extensions/AppleIntelBDWGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelBDWGraphicsGLDriver
    0x7fff43873000 -     0x7fff43971ff7  com.apple.driver.AppleIntelBDWGraphicsMTLDriver (12.4.7.1 - 12.0.4) <21128297-4983-32C6-B1B7-37C08D033133> /System/Library/Extensions/AppleIntelBDWGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelBDWGraphicsMTLDriver
    0x7fff47d61000 -     0x7fff47d65fff  com.apple.agl (3.3.2 - AGL-3.3.2) <1BA0EF39-F658-316F-B6CD-CE4FD1B925D6> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff48132000 -     0x7fff48132fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <A09CB6D5-3F8A-3E05-B0EB-63878296A059> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff48133000 -     0x7fff48149fef  libCGInterfaces.dylib (506.19.1) <55B9EFFF-6719-381E-B7F3-C3AA07F5D78F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff4814a000 -     0x7fff487eafe3  com.apple.vImage (8.1 - ???) <BDA40EB0-9B20-3ACF-BE37-199578FA84F4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff487eb000 -     0x7fff48a62fd7  libBLAS.dylib (1243.200.4) <0ADBEAE3-6636-33E5-AC9F-11C2249E19D3> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff48a63000 -     0x7fff48ad5fe7  libBNNS.dylib (38.200.5) <CC93B9B5-2A8C-3D42-9234-75DD41EC8C0D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff48ad6000 -     0x7fff48e7cfff  libLAPACK.dylib (1243.200.4) <45722A8A-5788-3C4C-ADD9-1812763FA635> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff48e7d000 -     0x7fff48e92ffb  libLinearAlgebra.dylib (1243.200.4) <3923AB79-213E-32FD-AC87-8B1A1A832336> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff48e93000 -     0x7fff48e98ff3  libQuadrature.dylib (3.200.2) <4FBCAC0A-81A4-3C53-8458-27F3569C809D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff48e99000 -     0x7fff48f16ffb  libSparse.dylib (79.200.5) <2D650C50-E87E-3F24-9BFA-C8EB6DE1A6E9> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff48f17000 -     0x7fff48f2affb  libSparseBLAS.dylib (1243.200.4) <6F8C78BE-A0FD-3507-8A95-541AFC57F1EE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff48f2b000 -     0x7fff4910fff3  libvDSP.dylib (671.220.1) <2F576522-08B1-3C65-8F00-3427E938ADDA> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff49110000 -     0x7fff491c5ff3  libvMisc.dylib (671.220.1) <D7B5F89D-3310-31F4-B8BF-42DA300ABE64> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff491c6000 -     0x7fff491c6fff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <221E4FEF-0431-3316-8281-22B6F8315A09> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff49377000 -     0x7fff4a198ffb  com.apple.AppKit (6.9 - 1671.20.108) <0C441020-D10E-3CE0-B320-527E50EADBEC> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4a1ea000 -     0x7fff4a1eafff  com.apple.ApplicationServices (50.1 - 50.1) <50496459-FFDD-3A78-8D3D-A252BD9B9DA2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4a1eb000 -     0x7fff4a256ff7  com.apple.ApplicationServices.ATS (377 - 453.11) <4080F8BE-F2A2-3707-8754-436FBDB1DAF1> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff4a2ef000 -     0x7fff4a40efff  libFontParser.dylib (228.6) <BBCBEE2C-5B55-3278-B81D-22D72466753E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff4a40f000 -     0x7fff4a45afff  libFontRegistry.dylib (228.12) <1CC4D486-74F8-3459-BBA1-F68A36C5CAF8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff4a4b9000 -     0x7fff4a4ecff7  libTrueTypeScaler.dylib (228.6) <760BF895-3D7A-36E2-B97C-6775C3615A1D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff4a556000 -     0x7fff4a55aff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <4B1238CC-9B77-3AA5-8329-EE3C736F07EA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff4a5f7000 -     0x7fff4a649ff3  com.apple.HIServices (1.22 - 627.14.2) <1F851BF9-AD29-3558-9EA5-AAD9BAAAC823> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff4a64a000 -     0x7fff4a658ff3  com.apple.LangAnalysis (1.7.0 - 1.7.0) <5654723A-7B3B-391F-B9F7-0DE4D5940185> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff4a659000 -     0x7fff4a6a5fff  com.apple.print.framework.PrintCore (14.2 - 503.8) <F1246C9A-2216-3390-8DF1-89304F47CE5D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff4a6a6000 -     0x7fff4a6e1ff7  com.apple.QD (3.12 - 407.2) <F6B648DA-DA39-3EB4-B593-1B7E316661CD> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff4a6e2000 -     0x7fff4a6eeff7  com.apple.speech.synthesis.framework (8.1.0 - 8.1.0) <CF19C8B6-AAD5-3DCF-ABD0-3BABB44D119C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff4a6ef000 -     0x7fff4a98cfff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <5D484151-F269-3D98-B507-0544A6B950AC> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff4a98e000 -     0x7fff4a98efff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <91100E0A-C14D-3E6C-B095-0C4109AC6694> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff4acf2000 -     0x7fff4b0b3fff  com.apple.CFNetwork (976 - 976) <10F464AD-6687-3012-A2AA-0453629CA968> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff4b0c8000 -     0x7fff4b0c8fff  com.apple.Carbon (158 - 158) <D6170F31-7A8A-3D4F-91DA-E11CF33E62B4> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff4b0c9000 -     0x7fff4b0ccffb  com.apple.CommonPanels (1.2.6 - 98) <775C94BE-EC00-315F-96E0-F0C1CD6EE3F4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff4b0cd000 -     0x7fff4b3d4ff7  com.apple.HIToolbox (2.1.1 - 917.3) <B2FEF0F3-CBA0-3FD9-93FC-E3A13DCB8C49> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff4b3d5000 -     0x7fff4b3d8ffb  com.apple.help (1.3.8 - 66) <0C6CC127-A860-30D2-8434-6CC3CAFFB030> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff4b3d9000 -     0x7fff4b3deff7  com.apple.ImageCapture (9.0 - 1530.1) <72ABBF32-531B-3B04-926D-E14B8D9003A8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff4b3df000 -     0x7fff4b473ff3  com.apple.ink.framework (10.9 - 225) <344AACCC-E997-3498-8B1D-2EFD3A889205> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff4b474000 -     0x7fff4b48efff  com.apple.openscripting (1.7 - 179) <A57FC4DB-4C51-3ABB-842F-9578991043E3> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff4b4af000 -     0x7fff4b4b0fff  com.apple.print.framework.Print (14.2 - 267.4) <618D290C-2EA0-3959-A2A8-FB7B61DA92DD> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff4b4b1000 -     0x7fff4b4b3ff7  com.apple.securityhi (9.0 - 55006) <2FE1EB07-F717-3E89-9662-8BA7C17C6AEC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff4b4b4000 -     0x7fff4b4baff7  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <F7E95C56-19E8-30A1-9594-84D4DD89F6D4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff4b5e3000 -     0x7fff4b5e3fff  com.apple.Cocoa (6.11 - 23) <D0BED932-C061-33E9-9F59-ECE0BA9F7EEB> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff4b5f1000 -     0x7fff4b6bdfff  com.apple.ColorSync (4.13.0 - 3340) <2F45EB01-0C51-3D25-9836-18F99222E1C7> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff4b858000 -     0x7fff4b8e8fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <1E7EF105-B843-370D-884E-0A43E1A5800B> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff4b94e000 -     0x7fff4b979ff7  com.apple.CoreBluetooth (1.0 - 1) <F041753E-7709-3FA4-ADA3-6B37296D92FB> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff4b97a000 -     0x7fff4bd1bfef  com.apple.CoreData (120 - 866.1) <18CD58FD-513E-385B-B43C-08EEB909709C> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff4bd1c000 -     0x7fff4be05ff7  com.apple.CoreDisplay (101.3 - 106.2) <EE0D334B-8B71-3A70-9F90-677171D6762F> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff4be06000 -     0x7fff4c253ff7  com.apple.CoreFoundation (6.9 - 1561) <AC90EE38-93D9-35EF-8359-9FE3A42500D4> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4c255000 -     0x7fff4c8e2ff7  com.apple.CoreGraphics (2.0 - 1249.2) <3AC6DEB1-245B-3E3A-B5CF-791A37237775> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff4c8e4000 -     0x7fff4cc0dfff  com.apple.CoreImage (14.2.0 - 720.0.130) <8C8BC619-7084-3F58-BBFC-4A97BD330787> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff4cf5e000 -     0x7fff4d05fff7  com.apple.CoreMedia (1.0 - 2284.9) <4662B44E-F463-3FC8-A643-2195FF10A3E4> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff4d0c3000 -     0x7fff4d0c3fff  com.apple.CoreServices (941 - 941) <950D3EAF-C98E-3BCB-8FD9-43EEA0E48988> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4d0c4000 -     0x7fff4d142ffb  com.apple.AE (771 - 771) <4B009524-699E-3891-98DD-E3B6BB433C8F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff4d143000 -     0x7fff4d41bff7  com.apple.CoreServices.CarbonCore (1178.16 - 1178.16) <17FC2B9E-EB6C-3768-A2D0-6E086F2563D9> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff4d41c000 -     0x7fff4d466ff7  com.apple.DictionaryServices (1.2 - 284.16.3) <1DAC9153-FB5A-3798-8797-CBFEFF227F71> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff4d467000 -     0x7fff4d46fffb  com.apple.CoreServices.FSEvents (1239.200.12 - 1239.200.12) <8E1507EA-F0A8-3845-B32D-4FBC1381E89C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff4d470000 -     0x7fff4d63bfff  com.apple.LaunchServices (941 - 941) <98B7E20E-5D0A-3A71-A019-346A145A1A5E> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff4d63c000 -     0x7fff4d6defff  com.apple.Metadata (10.7.0 - 1191.53) <E4C1B7AB-677B-32B2-918C-CD445A0D0D91> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff4d6df000 -     0x7fff4d72aff7  com.apple.CoreServices.OSServices (941 - 941) <DFA21754-BFE4-367C-9303-739F5D3E9DDE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff4d72b000 -     0x7fff4d799ff7  com.apple.SearchKit (1.4.0 - 1.4.0) <CEC29BB5-D28E-3424-84FE-70756E521F3B> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff4d79a000 -     0x7fff4d7beffb  com.apple.coreservices.SharedFileList (71.27 - 71.27) <6389B59D-DDAC-3C97-A982-137B9B1FB734> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff4db06000 -     0x7fff4dc6bffb  com.apple.CoreText (352.0 - 584.26) <5F61037C-825D-37A4-9091-0047413CC213> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff4dc6c000 -     0x7fff4dca9fff  com.apple.CoreVideo (1.8 - 0.0) <34EC73F1-F0ED-32F5-B96E-7683B1F9A7A2> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff4dcaa000 -     0x7fff4dd40ffb  com.apple.framework.CoreWLAN (13.0 - 1370.8) <32426190-3455-3049-8C09-0EC04D9C1279> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff4dfbd000 -     0x7fff4dfc2fff  com.apple.DiskArbitration (2.7 - 2.7) <97707A79-30E7-3D99-AA20-B992B0900BC4> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff4e188000 -     0x7fff4e18aff7  com.apple.ForceFeedback (1.0.6 - 1.0.6) <42A74696-FDA2-3F33-872A-A452D246B80C> /System/Library/Frameworks/ForceFeedback.framework/Versions/A/ForceFeedback
    0x7fff4e18b000 -     0x7fff4e559fff  com.apple.Foundation (6.9 - 1561) <27FD022F-F0E3-3053-BADA-DF9BF856CA85> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff4e5ca000 -     0x7fff4e5faff3  com.apple.GSS (4.0 - 2.0) <86D07291-5DFC-30C2-9A18-5FCEDB0BE621> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff4e714000 -     0x7fff4e81eff3  com.apple.Bluetooth (6.0.9 - 6.0.9f2) <CD9FA230-8BBB-307C-8FFF-86B1B7078D05> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff4e880000 -     0x7fff4e912ff7  com.apple.framework.IOKit (2.0.2 - 1483.230.1) <AAAF13D1-80E5-3079-98C1-FA3C3FC47B40> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff4e914000 -     0x7fff4e91eff7  com.apple.IOSurface (255.1 - 255.1) <58826B1A-38E8-3C76-8FFC-76C9282DA893> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff4e975000 -     0x7fff4eb13fff  com.apple.ImageIO.framework (3.3.0 - 1822.1) <908907D5-5C29-32F7-ACD9-C6A6D51C4D15> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff4eb14000 -     0x7fff4eb18ffb  libGIF.dylib (1822.1) <35E37B95-1962-3A25-9C9E-CADD161152B3> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff4eb19000 -     0x7fff4ebfefe7  libJP2.dylib (1822.1) <BDBCBF28-12DB-3D63-B6F0-A559D1839F81> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff4ebff000 -     0x7fff4ec24ff7  libJPEG.dylib (1822.1) <D443C754-4AFC-38E1-9E45-D309ACBCE17B> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff4eef7000 -     0x7fff4ef1dfe7  libPng.dylib (1822.1) <28FE6E2C-1A17-3A84-AAF3-76014DEADDD4> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff4ef1e000 -     0x7fff4ef20ff7  libRadiance.dylib (1822.1) <687906E3-4EC2-3CE9-B7EA-34418239EE1B> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff4ef21000 -     0x7fff4ef6fffb  libTIFF.dylib (1822.1) <0A1C083B-CE2F-3A00-8E45-EB58DCA2FF34> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff50019000 -     0x7fff50032fff  com.apple.Kerberos (3.0 - 1) <5D1B0593-3C0E-32D5-AAE5-ABC22A98B639> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff502f0000 -     0x7fff502fafff  com.apple.MediaAccessibility (1.0 - 114.4) <C0584BAA-27BC-30F4-8B0C-5043559995AA> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff503b4000 -     0x7fff50a52fff  com.apple.MediaToolbox (1.0 - 2284.9) <AD1C6882-F6FC-3114-9517-CCF9402A30B1> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff50a54000 -     0x7fff50ae7fff  com.apple.Metal (158.5 - 158.5) <219312CC-0DE5-3E8D-9F62-393D0C35B0FD> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff50b04000 -     0x7fff50b24ff7  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <18281B14-0C6A-38F8-AB80-2D4BB0743C88> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff50b25000 -     0x7fff50ba3ff7  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <BEAF764B-362B-3C45-86F5-2AFBA5FA0F47> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff50ba4000 -     0x7fff50bccfff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <116D6C1A-2FD7-3743-95A0-CDDA3D459529> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff50bcd000 -     0x7fff50cffff7  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <88E80BEE-3D2B-328B-80D4-F4717BDB2E9F> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff50d00000 -     0x7fff50d1bff7  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <E0E652B0-1624-3435-AD60-83A9C4B59852> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff50d1c000 -     0x7fff50d1cff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <1BBA8BC8-49C6-3C9B-B985-7CE4373E3553> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff51f19000 -     0x7fff51f25ffb  com.apple.NetFS (6.0 - 4.0) <918DF6CD-2DB0-36A8-B869-5EF637A06C0D> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff549dc000 -     0x7fff549e4fe7  libcldcpuengine.dylib (2.10.3) <D7BF3AFE-3E48-35FF-B674-6CA33B982D63> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fff549e5000 -     0x7fff54a3dfff  com.apple.opencl (2.15.1 - 2.15.1) <E628D178-3846-373A-9482-CF680BD1E240> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff54a3e000 -     0x7fff54a5aff7  com.apple.CFOpenDirectory (10.14 - 207.200.4) <2CB1F122-2FA0-347C-8454-9CE0FA150832> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff54a5b000 -     0x7fff54a67ffb  com.apple.OpenDirectory (10.14 - 207.200.4) <A3FB0F0C-57F4-3F89-A4B1-63DA1F7C9E8E> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff553ca000 -     0x7fff553ccfff  libCVMSPluginSupport.dylib (17.3.1) <4D6061EC-CFCD-3C0E-90E4-51644DC5F76A> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff553cd000 -     0x7fff553d2ff3  libCoreFSCache.dylib (163.20) <566DB80E-F1D6-3AEC-AF06-08955507AFEE> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff553d3000 -     0x7fff553d7fff  libCoreVMClient.dylib (163.20) <B9A89373-BDCD-3003-9A82-6D73B930A122> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff553d8000 -     0x7fff553e0ffb  libGFXShared.dylib (17.3.1) <902F535E-E411-3C3B-B980-0A7DB40EA5B7> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff553e1000 -     0x7fff553ecfff  libGL.dylib (17.3.1) <87F8CCDB-2D7D-3B01-AA6F-6C7A4B1CA11E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff553ed000 -     0x7fff55427fef  libGLImage.dylib (17.3.1) <B5464F1A-B936-3BEE-97CF-3806AD1A9E68> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff55428000 -     0x7fff5559aff3  libGLProgrammability.dylib (17.3.1) <E3B2318B-5D3C-34E9-AECD-4A2D8E4B0616> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fff5559b000 -     0x7fff555d8fff  libGLU.dylib (17.3.1) <C46D4335-4CE2-3FFB-930D-E48D7A3B5B4F> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff55f88000 -     0x7fff55f97ff3  com.apple.opengl (17.3.1 - 17.3.1) <78BDC7C4-87AD-33CA-BFAC-A9CC5F605B5D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff55f98000 -     0x7fff5612eff7  GLEngine (17.3.1) <538676A2-3E3F-3FC3-97D8-AB7D900F8D4D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fff5612f000 -     0x7fff56157ff7  GLRendererFloat (17.3.1) <A918F8A9-8E0E-37C1-B368-AA4BCB5D5FD1> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fff56df3000 -     0x7fff5704cfff  com.apple.QuartzCore (1.11 - 695.4) <6692906D-9EF7-3EA0-96D3-3766567AE7F2> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff578a0000 -     0x7fff57bc8fff  com.apple.security (7.0 - 58286.230.21) <5ADE179E-87D5-3B90-9172-D183D4665037> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff57bc9000 -     0x7fff57c58fff  com.apple.securityfoundation (6.0 - 55185.200.14) <A57F481C-73B9-33C4-9093-9A06DBBFEDE5> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff57c8a000 -     0x7fff57c8eff3  com.apple.xpc.ServiceManagement (1.0 - 1) <16FA4DAF-A0BE-34C0-B5F1-5C30BE3DCD2D> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff5804b000 -     0x7fff580bbff3  com.apple.SystemConfiguration (1.17 - 1.17) <A8FD596E-C858-397F-836C-978038B97AC0> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff5831c000 -     0x7fff5867efff  com.apple.VideoToolbox (1.0 - 2284.9) <695514F0-08C8-3065-B9A2-DA3B43E6682F> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff5b326000 -     0x7fff5b3cbff7  com.apple.APFS (1.0 - 1) <5CA4B73F-3F5D-3289-9145-520FFDFD6813> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff5be15000 -     0x7fff5be16ff3  com.apple.AggregateDictionary (1.0 - 1) <EBA6443E-6CF0-34F6-B77A-3FCEC57F8F80> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff5c413000 -     0x7fff5c43fff7  com.apple.framework.Apple80211 (13.0 - 1376.2) <A71EADCB-7582-3D1B-9122-356F03E11594> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff5c71b000 -     0x7fff5c72afcf  com.apple.AppleFSCompression (96.200.3 - 1.0) <78D538DD-1D24-34FC-AFB3-10411494870D> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff5c828000 -     0x7fff5c833fff  com.apple.AppleIDAuthSupport (1.0 - 1) <E41452B2-3AFB-3493-BB82-0CE6D04DF424> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff5c874000 -     0x7fff5c8bdff3  com.apple.AppleJPEG (1.0 - 1) <EC4C49F1-C060-3C0F-910F-3620985D4F12> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff5cb10000 -     0x7fff5cb38ff7  com.apple.applesauce (1.0 - ???) <58654BC0-9243-39D1-BC43-B7F2E37A3A44> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff5cc03000 -     0x7fff5cc53fff  com.apple.AppleVAFramework (5.0.44 - 5.0.44) <0338350C-F366-3C0D-B7C1-6E8FFAB92E98> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff5cc9e000 -     0x7fff5ccb4ffb  com.apple.AssertionServices (1.0 - 1) <3F767D20-FE14-35CF-A089-E0445375ECFB> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff5cff0000 -     0x7fff5d293ff7  com.apple.AuthKit (1.0 - 1) <4FF8DA76-2250-39B9-B6A9-0E584C8B988F> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff5d464000 -     0x7fff5d46dff3  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <05CF66F0-9650-3F75-9857-F8D186043866> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff5d46e000 -     0x7fff5d510fff  com.apple.backup.framework (1.10.2 - ???) <7C865F13-12F9-3E38-A4A3-31516EA869B2> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff5d511000 -     0x7fff5d582ffb  com.apple.BaseBoard (360.24 - 360.24) <04AF4372-C5D3-3F0A-A688-68D888D6D138> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff5f136000 -     0x7fff5f13ffff  com.apple.CommonAuth (4.0 - 2.0) <090893E5-BB65-39DA-A174-EAB2C7191EFE> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff5f5fd000 -     0x7fff5f9d4fef  com.apple.CoreAUC (273.0.0 - 273.0.0) <FE2B4D86-2C83-3FE2-A427-54DA2170E980> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff5f9d5000 -     0x7fff5fa06fff  com.apple.CoreAVCHD (6.0.0 - 6000.4.1) <B15A24E4-2A92-3FD7-8F20-C372E4115FA7> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff5fe4f000 -     0x7fff5fe63fff  com.apple.CoreEmoji (1.0 - 69.19.8) <26BC0F82-08C1-3EBD-9299-D3CC5091C467> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff60439000 -     0x7fff604abff7  com.apple.CoreNLP (1.0 - 130.15.22) <D0A3E880-CDEA-360A-9838-220D76BAECC6> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff60774000 -     0x7fff6077cffb  com.apple.CorePhoneNumbers (1.0 - 1) <2D9AF545-ED3C-3EC1-887F-86922652EC57> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff6090b000 -     0x7fff6093cfff  com.apple.CoreServicesInternal (357 - 357) <789E57F4-5A14-3220-93DF-1D4FEE315431> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff60d11000 -     0x7fff60d9fff7  com.apple.CoreSymbolication (10.1 - 64460.6) <133D09A5-39F7-301D-B019-B6685B80A2CB> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff60e2f000 -     0x7fff60f5bfff  com.apple.coreui (2.1 - 498.46) <5EFE2CDC-897C-3A6B-A60B-4E0FB1D1ECA9> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff60f5c000 -     0x7fff610e1fff  com.apple.CoreUtils (5.7.4 - 574.17) <DEF9C8A6-DDF1-37F4-A7F0-7DFAA95E8451> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff61138000 -     0x7fff6119bffb  com.apple.framework.CoreWiFi (13.0 - 1370.8) <818F8915-BA51-3145-9C40-C9B8D7BE2DBD> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff6119c000 -     0x7fff611adffb  com.apple.CrashReporterSupport (10.13 - 938.23) <D8D105F5-B6FB-3E91-A116-7CD92171E5C5> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff61230000 -     0x7fff6123fff3  com.apple.framework.DFRFoundation (1.0 - 211) <B72944ED-E4E8-3479-B832-8D50C4E30386> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff61240000 -     0x7fff61244ff7  com.apple.DSExternalDisplay (3.1 - 380) <76449D22-BA27-3FB1-AD25-A290936E6DEA> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff612c7000 -     0x7fff6133effb  com.apple.datadetectorscore (7.0 - 590.24) <3A49EC90-2081-3031-8CAE-3A6D5F7BFA1E> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff6138c000 -     0x7fff613cdfff  com.apple.DebugSymbols (185 - 185) <64F5F9D6-401D-388B-82AD-A48B56413556> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff613ce000 -     0x7fff61527ff7  com.apple.desktopservices (1.13.1 - ???) <AD61A660-0218-327E-8963-A1A170EC2C20> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff62569000 -     0x7fff62991fff  com.apple.vision.FaceCore (3.3.4 - 3.3.4) <41218EB7-19C9-3813-A793-B0623387CADF> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff662b3000 -     0x7fff662b4fff  libmetal_timestamp.dylib (902.2.2) <55E0B1F2-94F0-3A77-9DB3-152F44848DA5> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3902/Libraries/libmetal_timestamp.dylib
    0x7fff67952000 -     0x7fff6795dff7  libGPUSupportMercury.dylib (17.3.1) <41312897-2629-3BFC-ADD2-BF66926EFE05> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fff6795e000 -     0x7fff67963ff7  com.apple.GPUWrangler (3.28.4 - 3.28.4) <14D6FE7D-38D7-3F6C-9BCE-A228D6697A08> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff687cd000 -     0x7fff687dcfff  com.apple.GraphVisualizer (1.0 - 5) <CAFE626E-9738-3C14-88AA-B6A9182F2C39> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff6892d000 -     0x7fff689a2fff  com.apple.Heimdal (4.0 - 2.0) <D99FF31F-6310-3D80-8AE3-64934385AC11> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff69d92000 -     0x7fff69d99ffb  com.apple.IOAccelerator (404.2.2 - 404.2.2) <7421825E-13D4-3C74-932D-34E8A605C281> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff69d9d000 -     0x7fff69db6fff  com.apple.IOPresentment (1.0 - 42.6) <87D19032-52DB-34A5-A554-23B3464EFC82> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff6a1cb000 -     0x7fff6a1faff7  com.apple.IconServices (379 - 379) <694E17A6-471B-3C57-92D6-ECC4295FB859> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff6a49a000 -     0x7fff6a4adfff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <02ECB210-513F-3BDE-8150-A828E901FA02> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff6a4c8000 -     0x7fff6a5bffff  com.apple.LanguageModeling (1.0 - 159.15.15) <34609F31-4DA1-3881-8947-85BEA7AFC938> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff6a5c0000 -     0x7fff6a601ff7  com.apple.Lexicon-framework (1.0 - 33.15.10) <07E008F3-E823-333B-8B41-A46024AB0561> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff6a608000 -     0x7fff6a60eff7  com.apple.LinguisticData (1.0 - 238.23.4) <37948616-56E6-3758-BEFE-28586FF99E12> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff6ae6d000 -     0x7fff6ae70fff  com.apple.Mangrove (1.0 - 25) <8DF73279-BCEB-38CE-AE83-571C1B3FF45B> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff6b36b000 -     0x7fff6b393ffb  com.apple.spotlight.metadata.utilities (1.0 - 1191.53) <09C6DCF6-F87D-3D03-8BD5-FD1DCF90949F> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff6b394000 -     0x7fff6b426fff  com.apple.gpusw.MetalTools (1.0 - 1) <B77258A5-909F-37F7-8F1A-2085F7916DD4> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff6b43b000 -     0x7fff6b454fff  com.apple.MobileAssets (1.0 - 437.230.2) <73BF5743-F050-3393-AECE-298ADF3960F4> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff6b5d1000 -     0x7fff6b5ecff3  com.apple.MobileKeyBag (2.0 - 1.0) <26347762-AF60-3412-A951-33BF85244D84> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff6b67a000 -     0x7fff6b6a4ff7  com.apple.MultitouchSupport.framework (2410.5 - 2410.5) <3A712911-F672-3BB3-B62B-A2A7BADF3578> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff6b917000 -     0x7fff6b921fff  com.apple.NetAuth (6.2 - 6.2) <E191D736-A442-31BA-B823-EE75DC316D22> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff6c1ee000 -     0x7fff6c244fff  com.apple.OTSVG (1.0 - ???) <F020144A-D840-390D-A87F-29E8095C78AF> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff6d3af000 -     0x7fff6d3beff3  com.apple.PerformanceAnalysis (1.217 - 217) <AA34989F-7E01-303E-8134-5BB37CE82DDF> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff6f37d000 -     0x7fff6f39bff7  com.apple.ProtocolBuffer (1 - 263.1) <D70A1E3D-D2F7-3765-861C-173F5BBC848B> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff6f54a000 -     0x7fff6f5a2f0f  com.apple.ROCKit (24 - 24) <FA6B086A-1841-3A5E-800B-CE7A52C3DAF1> /System/Library/PrivateFrameworks/ROCKit.framework/Versions/A/ROCKit
    0x7fff6f6c6000 -     0x7fff6f6e9ffb  com.apple.RemoteViewServices (2.0 - 128) <55D89BC9-0613-3910-B63E-9A146D35D91A> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff7105e000 -     0x7fff7117cfff  com.apple.Sharing (1214.18 - 1214.18) <E6302F6F-2940-3DDB-ADA7-EE123DD6D027> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff71f36000 -     0x7fff721e8ff3  com.apple.SkyLight (1.600.0 - 337.5) <52BC8AB1-3518-3E4C-B1B1-0A8A8067574F> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff729b9000 -     0x7fff729c6fff  com.apple.SpeechRecognitionCore (5.0.21 - 5.0.21) <FABB97BC-9555-33FE-B6C5-606CC403CE16> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff730ab000 -     0x7fff730eaff3  com.apple.StreamingZip (1.0 - 1) <251128E7-C343-3799-A31B-8B10CEC69F19> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff73827000 -     0x7fff738b4ff7  com.apple.Symbolication (10.1 - 64460.8) <7DDC5C90-947F-34FF-864D-5ED3C2B746A9> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff73dbd000 -     0x7fff73dcaffb  com.apple.TCC (1.0 - 1) <81F88B91-49C1-36E7-8A39-C4BD654EE942> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff7403d000 -     0x7fff74104ff7  com.apple.TextureIO (3.8.4 - 3.8.1) <83CDF659-E5B3-381F-BDA1-FF0BFA17B5EE> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff741be000 -     0x7fff741bffff  com.apple.TrustEvaluationAgent (2.0 - 31.200.1) <5C3E1B2D-40A8-3237-A8D9-4E7B15EEA678> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff741c5000 -     0x7fff7437ffff  com.apple.UIFoundation (1.0 - 551) <65A80450-7A24-3366-B521-4D02C4DB5094> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff7506e000 -     0x7fff75157ff7  com.apple.ViewBridge (401.1 - 401.1) <E76BC854-5B08-3FFF-AA2C-9679754FCAF0> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff7597d000 -     0x7fff75980fff  com.apple.dt.XCTTargetBootstrap (1.0 - 1) <5F779D77-4AB1-3CCD-9AAF-101EC7E4905B> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff75db1000 -     0x7fff75db3ff3  com.apple.loginsupport (1.0 - 1) <67BC49D6-320F-33ED-912E-16E5A342F385> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff75db4000 -     0x7fff75dc9fff  com.apple.login (3.0 - 3.0) <D6486C5A-E644-3F43-AD27-5E14685CD8D6> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff7606e000 -     0x7fff760a6fff  libCRFSuite.dylib (41.15.4) <92752A96-D1CF-3CA1-837A-1E075AE4C642> /usr/lib/libCRFSuite.dylib
    0x7fff760a9000 -     0x7fff760b4ff7  libChineseTokenizer.dylib (28.15.3) <55572692-4918-3C54-AD35-726E03EC47D5> /usr/lib/libChineseTokenizer.dylib
    0x7fff76145000 -     0x7fff76146ff7  libDiagnosticMessagesClient.dylib (107) <15210AC0-61F9-3F9D-A159-A009F62EB537> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff7617d000 -     0x7fff76340ff7  libFosl_dynamic.dylib (18.3.2) <D67B74E9-EB95-38BC-995C-5F4CC044C3F7> /usr/lib/libFosl_dynamic.dylib
    0x7fff76396000 -     0x7fff763b5ff7  libMobileGestalt.dylib (645.220.9) <C2C55511-993B-34D2-9040-902BFDA38141> /usr/lib/libMobileGestalt.dylib
    0x7fff763b6000 -     0x7fff763b6fff  libOpenScriptingUtil.dylib (179) <441A2E60-5D5C-3567-9B00-AA22E6EE5358> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff764f7000 -     0x7fff764f8ffb  libSystem.B.dylib (1252.200.5) <25F4A1F5-6551-312F-B397-C8D45ACC530A> /usr/lib/libSystem.B.dylib
    0x7fff76582000 -     0x7fff76583fff  libThaiTokenizer.dylib (2.15.1) <F09EB0BB-1E8A-3391-BEF5-7D91F0715A62> /usr/lib/libThaiTokenizer.dylib
    0x7fff76596000 -     0x7fff765acffb  libapple_nghttp2.dylib (1.24.1) <71C126C5-D869-3E67-9778-058FA7F3CA74> /usr/lib/libapple_nghttp2.dylib
    0x7fff765ad000 -     0x7fff765d6ffb  libarchive.2.dylib (54.200.3) <32B8634D-E465-3F6D-B254-A20D44504508> /usr/lib/libarchive.2.dylib
    0x7fff765d7000 -     0x7fff76656fef  libate.dylib (1.13.8) <C7F1CEC4-467F-34B2-92FF-6482460A39E1> /usr/lib/libate.dylib
    0x7fff7665a000 -     0x7fff7665aff3  libauto.dylib (187) <003DEF68-0C59-3AFB-A7B7-A1B5ED301AF2> /usr/lib/libauto.dylib
    0x7fff76731000 -     0x7fff76741ff3  libbsm.0.dylib (39.200.18) <58A9ACEC-BF46-3A4E-86F5-3DD9AD7095B4> /usr/lib/libbsm.0.dylib
    0x7fff76742000 -     0x7fff76750fff  libbz2.1.0.dylib (38.200.3) <4DEC3797-087F-3C8D-815B-48E895813251> /usr/lib/libbz2.1.0.dylib
    0x7fff76751000 -     0x7fff767a8ff7  libc++.1.dylib (400.9.4) <B260AC33-EB9A-30C6-8746-D011B3B02B08> /usr/lib/libc++.1.dylib
    0x7fff767a9000 -     0x7fff767befff  libc++abi.dylib (400.17) <446F4748-8A89-3D2E-AE1C-27EEBE93A8AB> /usr/lib/libc++abi.dylib
    0x7fff767bf000 -     0x7fff767bfff3  libcharset.1.dylib (51.200.6) <43F7E100-F5D1-36AB-A26E-CF94196A19C0> /usr/lib/libcharset.1.dylib
    0x7fff767c0000 -     0x7fff767d0ffb  libcmph.dylib (6.15.1) <CEDA6538-C071-3B5A-948E-DF61E2878983> /usr/lib/libcmph.dylib
    0x7fff767d1000 -     0x7fff767e9ffb  libcompression.dylib (52.200.13) <05A2A91B-D24D-39E8-A071-261CBC5BB158> /usr/lib/libcompression.dylib
    0x7fff76a94000 -     0x7fff76aaafff  libcoretls.dylib (155.220.1) <1229F9EA-C070-3D03-9DC6-F548C59F9FD5> /usr/lib/libcoretls.dylib
    0x7fff76aab000 -     0x7fff76aacff3  libcoretls_cfhelpers.dylib (155.220.1) <33661841-3C3B-3608-86AC-C88D1CD6FE98> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff76c4b000 -     0x7fff76ddbff3  libcrypto.35.dylib (22.230.1) <175DFAE2-74B6-3285-BEC5-A849340B4429> /usr/lib/libcrypto.35.dylib
    0x7fff77123000 -     0x7fff7717affb  libcups.2.dylib (462.10) <29B6D106-A5F2-321D-8916-90F595545D88> /usr/lib/libcups.2.dylib
    0x7fff772b2000 -     0x7fff772b2fff  libenergytrace.dylib (17.200.1) <F5BA8134-16F9-31CD-90E1-D1EBEBADA4AE> /usr/lib/libenergytrace.dylib
    0x7fff772e4000 -     0x7fff772e9ff7  libgermantok.dylib (17.15.2) <9381B152-5CFD-3D23-A5A7-4D64EE55B85E> /usr/lib/libgermantok.dylib
    0x7fff772ea000 -     0x7fff772efff7  libheimdal-asn1.dylib (520.220.2) <D851A47D-E162-35F8-B8D4-6ABEA7FFDAD7> /usr/lib/libheimdal-asn1.dylib
    0x7fff7731b000 -     0x7fff7740cff7  libiconv.2.dylib (51.200.6) <9FB95807-7C62-32B7-A19F-946D7FB7CCA6> /usr/lib/libiconv.2.dylib
    0x7fff7740d000 -     0x7fff77670ffb  libicucore.A.dylib (62109.0.1) <FEB89BD3-79C4-3208-A754-7E6BC4D38548> /usr/lib/libicucore.A.dylib
    0x7fff776bd000 -     0x7fff776befff  liblangid.dylib (128.15.1) <663D0A24-7260-31D1-9BFE-74D67B6F72F6> /usr/lib/liblangid.dylib
    0x7fff776bf000 -     0x7fff776d7fff  liblzma.5.dylib (10.200.3) <9A52A949-0CB1-39B6-9244-D079FB609559> /usr/lib/liblzma.5.dylib
    0x7fff776ef000 -     0x7fff7779ffff  libmecab.1.0.0.dylib (779.24.1) <590BC39C-2A3E-368B-9499-C808B84C4955> /usr/lib/libmecab.1.0.0.dylib
    0x7fff777a0000 -     0x7fff779ddff7  libmecabra.dylib (779.24.1) <22BFD5A8-EA42-3DC3-8910-F27DCFB1B631> /usr/lib/libmecabra.dylib
    0x7fff77bb5000 -     0x7fff77f0dffb  libnetwork.dylib (1229.230.4) <B76F8990-85CD-382D-BDF4-58C4AD4CE6C4> /usr/lib/libnetwork.dylib
    0x7fff77f9e000 -     0x7fff78724fe7  libobjc.A.dylib (750.1) <804715F4-F52D-34D0-8FEC-A25DC08513C3> /usr/lib/libobjc.A.dylib
    0x7fff78737000 -     0x7fff7873bffb  libpam.2.dylib (22.200.1) <85253002-89F2-3872-9C8A-1801303A2EBB> /usr/lib/libpam.2.dylib
    0x7fff7873e000 -     0x7fff78774ff7  libpcap.A.dylib (79.200.4) <6D25197A-2F7C-3147-A45A-F6F13E55909F> /usr/lib/libpcap.A.dylib
    0x7fff7888e000 -     0x7fff788a6ffb  libresolv.9.dylib (65.200.2) <A1A77B4E-1AF0-3039-9945-D05440494E00> /usr/lib/libresolv.9.dylib
    0x7fff788f8000 -     0x7fff788f9ff7  libspindump.dylib (267.1) <9DEA015B-410E-3D6E-A3EE-54E046092EA9> /usr/lib/libspindump.dylib
    0x7fff788fa000 -     0x7fff78ad1fe7  libsqlite3.dylib (274.20) <7B202039-5DDF-3140-808C-521E8F11394E> /usr/lib/libsqlite3.dylib
    0x7fff78d5e000 -     0x7fff78d61ffb  libutil.dylib (51.200.4) <10C5E165-0939-363A-9D13-7076F3B513EC> /usr/lib/libutil.dylib
    0x7fff78d62000 -     0x7fff78d6ffff  libxar.1.dylib (404) <16E875B3-CF89-3059-87BB-36D301B32E7B> /usr/lib/libxar.1.dylib
    0x7fff78d74000 -     0x7fff78e57fff  libxml2.2.dylib (32.8) <3E7875AC-3195-3800-AC48-8AA3B7BE51E4> /usr/lib/libxml2.2.dylib
    0x7fff78e58000 -     0x7fff78e80ff3  libxslt.1.dylib (16.1) <D6EBFEBB-F88E-398F-B1B5-66F413C2CD32> /usr/lib/libxslt.1.dylib
    0x7fff78e81000 -     0x7fff78e93ffb  libz.1.dylib (70.200.4) <15F7B40A-424C-33BB-BF2C-7E8195128B78> /usr/lib/libz.1.dylib
    0x7fff78f04000 -     0x7fff78f08ff3  libcache.dylib (81) <704331AC-E43D-343A-8C24-39201142AF27> /usr/lib/system/libcache.dylib
    0x7fff78f09000 -     0x7fff78f13ff3  libcommonCrypto.dylib (60118.220.1) <9C865644-EE9A-3662-AB77-7C8A5E561784> /usr/lib/system/libcommonCrypto.dylib
    0x7fff78f14000 -     0x7fff78f1bfff  libcompiler_rt.dylib (63.4) <817772E3-E836-3FFD-A39B-BDCD1C357221> /usr/lib/system/libcompiler_rt.dylib
    0x7fff78f1c000 -     0x7fff78f25ff3  libcopyfile.dylib (146.200.3) <5C5C4F35-DAB7-3CF1-940F-F47192AB8289> /usr/lib/system/libcopyfile.dylib
    0x7fff78f26000 -     0x7fff78faafdf  libcorecrypto.dylib (602.230.1) <C78D1A87-5543-3561-BEB4-3B480BA94ECB> /usr/lib/system/libcorecrypto.dylib
    0x7fff79031000 -     0x7fff7906bff7  libdispatch.dylib (1008.220.2) <2FDB1401-5119-3DF0-91F5-F4E105F00CD7> /usr/lib/system/libdispatch.dylib
    0x7fff7906c000 -     0x7fff7909bff3  libdyld.dylib (640.2) <376E3F3A-6942-3B0E-AD5E-4B97E8255CF5> /usr/lib/system/libdyld.dylib
    0x7fff7909c000 -     0x7fff7909cffb  libkeymgr.dylib (30) <A4EFD9A4-2EF3-3E18-B325-F527E3821939> /usr/lib/system/libkeymgr.dylib
    0x7fff7909d000 -     0x7fff790a9ff7  libkxld.dylib (4903.231.4) <7275D7AD-54CE-30BF-9459-18EA77E28ACC> /usr/lib/system/libkxld.dylib
    0x7fff790aa000 -     0x7fff790aaff7  liblaunch.dylib (1336.220.5) <8563299C-2493-3DBD-8E88-3FC673DB47DD> /usr/lib/system/liblaunch.dylib
    0x7fff790ab000 -     0x7fff790b0fff  libmacho.dylib (921) <6ADB99F3-D142-3A0A-B3CE-031354766ACC> /usr/lib/system/libmacho.dylib
    0x7fff790b1000 -     0x7fff790b3ffb  libquarantine.dylib (86.220.1) <58524FD7-63C5-38E0-9D90-845A79551C14> /usr/lib/system/libquarantine.dylib
    0x7fff790b4000 -     0x7fff790b5ff3  libremovefile.dylib (45.200.2) <BA53CA8A-9974-3A43-9265-B110B1AE470F> /usr/lib/system/libremovefile.dylib
    0x7fff790b6000 -     0x7fff790cdff3  libsystem_asl.dylib (356.200.4) <33C62769-1242-3BC1-9459-13CBCDECC7FE> /usr/lib/system/libsystem_asl.dylib
    0x7fff790ce000 -     0x7fff790cefff  libsystem_blocks.dylib (73) <152EDADF-7D94-35F2-89B7-E66DCD945BBA> /usr/lib/system/libsystem_blocks.dylib
    0x7fff790cf000 -     0x7fff79157fff  libsystem_c.dylib (1272.200.26) <D6C701A2-9F17-308D-B6AC-9E17EF31B7DF> /usr/lib/system/libsystem_c.dylib
    0x7fff79158000 -     0x7fff7915bff7  libsystem_configuration.dylib (963.200.27) <94898525-ECC8-3CC9-B312-CBEAAC305E32> /usr/lib/system/libsystem_configuration.dylib
    0x7fff7915c000 -     0x7fff7915fff7  libsystem_coreservices.dylib (66) <10818C17-70E1-328E-A3E3-C3EB81AEC590> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff79160000 -     0x7fff79166ffb  libsystem_darwin.dylib (1272.200.26) <07468CF7-982F-37C4-83D0-D5E602A683AA> /usr/lib/system/libsystem_darwin.dylib
    0x7fff79167000 -     0x7fff7916dff7  libsystem_dnssd.dylib (878.230.2) <FF9D5025-F060-334B-B6D8-C5D0BB6A55E3> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff7916e000 -     0x7fff791baff3  libsystem_info.dylib (517.200.9) <54B65F21-2E93-3579-9B72-6637A03245D9> /usr/lib/system/libsystem_info.dylib
    0x7fff791bb000 -     0x7fff791e3ff7  libsystem_kernel.dylib (4903.231.4) <ABDAABCA-C22A-3960-AA4E-E91A9FF34929> /usr/lib/system/libsystem_kernel.dylib
    0x7fff791e4000 -     0x7fff7922fff7  libsystem_m.dylib (3158.200.7) <AF25F8E8-194C-314F-A2D3-A424853EE796> /usr/lib/system/libsystem_m.dylib
    0x7fff79230000 -     0x7fff79254ff7  libsystem_malloc.dylib (166.220.1) <4777DC06-F9C6-356E-82AB-86A1C6D62F3A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff79255000 -     0x7fff79260ff3  libsystem_networkextension.dylib (767.220.1) <74818C3D-9B68-3823-A737-6A4B782618F2> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff79261000 -     0x7fff79268fff  libsystem_notify.dylib (172.200.21) <65B3061D-41D7-3485-B217-A861E05AD50B> /usr/lib/system/libsystem_notify.dylib
    0x7fff79269000 -     0x7fff79272fef  libsystem_platform.dylib (177.200.16) <83DED753-51EC-3B8C-A98D-883A5184086B> /usr/lib/system/libsystem_platform.dylib
    0x7fff79273000 -     0x7fff7927dfff  libsystem_pthread.dylib (330.230.1) <BA382BFC-6A17-3940-B417-D090EF2AF4F4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff7927e000 -     0x7fff79281ff7  libsystem_sandbox.dylib (851.230.3) <4D0CB1CA-160C-3C29-BE5D-131D68D43B1B> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff79282000 -     0x7fff79284ff3  libsystem_secinit.dylib (30.220.1) <5964B6D2-19D4-3CF9-BDBC-4EB1D42348F1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff79285000 -     0x7fff7928cff7  libsystem_symptoms.dylib (820.237.2) <487E1794-4C6E-3B1B-9C55-95B1A5FF9B90> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff7928d000 -     0x7fff792a2ff7  libsystem_trace.dylib (906.220.1) <4D4BA88A-FA32-379D-8860-33838723B35F> /usr/lib/system/libsystem_trace.dylib
    0x7fff792a4000 -     0x7fff792a9ffb  libunwind.dylib (35.4) <EF1A77FD-A86B-39F5-ABEA-6100AB23583A> /usr/lib/system/libunwind.dylib
    0x7fff792aa000 -     0x7fff792dafff  libxpc.dylib (1336.220.5) <DC50F33E-C47D-3256-BFE0-F8E9B5AEBE17> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 75155
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=439.0M resident=0K(0%) swapped_out_or_unallocated=439.0M(100%)
Writable regions: Total=608.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=608.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        2 
Activity Tracing                   256K        2 
CG backing stores                  248K        3 
CG image                            64K       10 
CoreAnimation                      108K       12 
CoreGraphics                         8K        2 
CoreImage                            8K        3 
CoreUI image data                  404K       11 
CoreUI image file                  196K        4 
Foundation                           4K        2 
IOKit                             7940K        2 
Kernel Alloc Once                    8K        2 
MALLOC                           203.5M       34 
MALLOC guard page                   32K        8 
MALLOC_LARGE (reserved)           1536K        2         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        2         reserved VM address space (unallocated)
Memory Tag 242                      12K        2 
OpenGL GLSL                        256K        4 
STACK GUARD                       56.0M       13 
Stack                             13.6M       13 
VM_ALLOCATE                        468K       14 
VM_ALLOCATE (reserved)              36K        2         reserved VM address space (unallocated)
__DATA                            31.4M      290 
__FONT_DATA                          4K        2 
__GLSLBUILTINS                    5176K        2 
__LINKEDIT                       223.3M       29 
__TEXT                           215.7M      286 
__UNICODE                          564K        2 
mapped file                       46.5M       19 
shared memory                      648K       14 
===========                     =======  ======= 
TOTAL                              1.2G      763 
TOTAL, minus reserved VM space   806.1M      763 


```

And here's the terminal output:
```
I: Config.cpp:490: Longest display side: -1 pixels. Choosing scale 1
I: NativeApp.cpp:1259: NativeResized ignored, not initialized
I: QtMain.cpp:417: Initializing GL graphics context
I: gpu_features.cpp:171: GPU Vendor : Intel Inc. ; renderer: Intel(R) HD Graphics 6000 version str: 2.1 INTEL-12.4.7 ; GLSL version str: 1.20
I: QtMain.cpp:419: Using thread, starting emu thread
I: NativeApp.cpp:760: NativeInitGraphics
I: NativeApp.cpp:1259: NativeResized ignored, not initialized
I: NativeApp.cpp:836: NativeInitGraphics completed
QWidget::repaint: Recursive repaint detected
I: GLRenderManager.cpp:191: Running first frame (0)
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
2019-01-07 14:23:37.746 PPSSPPQt[32374:1231239] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4bef8ecd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff77fb4720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4bf1295d -[NSException raise] + 9
	3   AppKit                              0x00007fff49413c8e -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
	4   AppKit                              0x00007fff4941107c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
	5   AppKit                              0x00007fff494d195b -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
	6   AppKit                              0x00007fff49410aa6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	7   AppKit                              0x00007fff494d1910 -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
	8   AppKit                              0x00007fff49b0dd8f -[NSSavePanel initWithContentRect:styleMask:backing:defer:] + 587
	9   AppKit                              0x00007fff496e8bc0 +[NSSavePanel _crunchyRawUnbonedPanel] + 550
	10  libqcocoa.dylib                     0x000000010b0448f7 _ZN20QCocoaSystemTrayIcon11showMessageERK7QStringS2_RK5QIconN23QPlatformSystemTrayIcon11MessageIconEi + 94967
	11  libqcocoa.dylib                     0x000000010b048ef4 _ZN20QCocoaSystemTrayIcon11showMessageERK7QStringS2_RK5QIconN23QPlatformSystemTrayIcon11MessageIconEi + 112884
	12  libqcocoa.dylib                     0x000000010b048d61 _ZN20QCocoaSystemTrayIcon11showMessageERK7QStringS2_RK5QIconN23QPlatformSystemTrayIcon11MessageIconEi + 112481
	13  QtWidgets                           0x00000001076195c8 _ZN14QDialogPrivate22setNativeDialogVisibleEb + 152
	14  QtWidgets                           0x000000010762578e _ZN11QFileDialog10setVisibleEb + 94
	15  QtWidgets                           0x0000000107619f50 _ZN7QDialog4execEv + 240
	16  QtWidgets                           0x000000010762a0c7 _ZN11QFileDialog14getOpenFileUrlEP7QWidgetRK7QStringRK4QUrlS4_PS2_6QFlagsINS_6OptionEERK11QStringList + 359
	17  QtWidgets                           0x0000000107629ea5 _ZN11QFileDialog15getOpenFileNameEP7QWidgetRK7QStringS4_S4_PS2_6QFlagsINS_6OptionEE + 245
	18  PPSSPPQt                            0x0000000105c22db5 _ZN10MainScreen10OnLoadFileERN2UI11EventParamsE + 165
	19  PPSSPPQt                            0x0000000105fe798c _ZN2UI14DispatchEventsEv + 444
	20  PPSSPPQt                            0x0000000105ff9862 _ZN2UI19UpdateViewHierarchyEPNS_9ViewGroupE + 1474
	21  PPSSPPQt                            0x0000000105c235ce _ZN10MainScreen6updateEv + 14
	22  PPSSPPQt                            0x0000000105fd929f _ZN13ScreenManager6updateEv + 63
	23  PPSSPPQt                            0x0000000105be25aa _Z12NativeUpdatev + 234
	24  PPSSPPQt                            0x0000000105cfaa0a _Z13UpdateRunLoopv + 42
	25  PPSSPPQt                            0x0000000105bbb44d _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN6MainUI14EmuThreadStartEvE3$_0EEEEEPvSA_ + 93
	26  libsystem_pthread.dylib             0x00007fff79276305 _pthread_body + 126
	27  libsystem_pthread.dylib             0x00007fff7927926f _pthread_start + 70
	28  libsystem_pthread.dylib             0x00007fff79275415 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

```

### PR DESCRIPTION
**Pull request by unknownbrackets**
This makes it work the same as Windows, and also cleans up the "Browse..." button which was still crashing.

Fixes the browse part of #11721, and #11808 fixes the flicker so this fixes #11721.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Yeah, this is the right way. Sorry for my laziness before....

File: Qt/QtMain.cpp [hunk 1]
```diff
@@ -387,8 +402,27 @@ bool MainUI::event(QEvent *e)
...
+			}
+			break;
+		} else if (e->type() == browseFolderEvent) {
+			I18NCategory *mm = GetI18NCategory("MainMenu");
+			QString fileName = QFileDialog::getExistingDirectory(nullptr, mm->T("Choose folder"), g_Config.currentDirectory.c_str());
+			if (QDir(fileName).exists()) {
+				NativeMessageReceived("browse_folderSelect", fileName.toStdString().c_str());
+			}
+		} else {
+	        return QWidget::event(e);
```
Comment (unknownbrackets) [inline Qt/QtMain.cpp]: Darn it, didn't even notice there were tabs and spaces in this file... sigh.

-[Unknown]
