### PR TITLE
Fix crash in Beats on x86-64, minor other fixes

### LINKED ISSUE #18130: Beats (NPUG80060) regression
Reported by "Saul's Balls" on Discord.

image

Game works in 1.15.4, but this happens in 1.16.

Beats has these IDs: NPEG-00001, NPUG-80060, NPJG-00001.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #18130 , the sc instruction failed to map the destination register.

Only use #18126 in soft-gpu mode (for now)

Add a couple of asserts.

### CODE REVIEW

File: Core/MIPS/x86/CompLoadStore.cpp [hunk 1]
```diff
@@ -429,6 +429,7 @@ namespace MIPSComp {
 			skipStore = J_CC(CC_NE);
 
 			CompITypeMemWrite(op, 32, safeMemFuncs.writeU32);
+			gpr.MapReg(rt, true, true);
```
Comment (unknownbrackets) [inline Core/MIPS/x86/CompLoadStore.cpp:432]: Wait, this looks wrong.  You can't map in a conditional, it could corrupt other regs from the perspective of the other condition.  This needs to happen before the J_CC?

-[Unknown]

Comment (hrydgard) [reply Core/MIPS/x86/CompLoadStore.cpp:432]: Since the reg is only written to in both branches, I actually think it should be fine here?

Comment (hrydgard) [reply Core/MIPS/x86/CompLoadStore.cpp:432]: But hm, I'll clean it up.

Comment (unknownbrackets) [reply Core/MIPS/x86/CompLoadStore.cpp:432]: No, because another reg might spill.  If it only spills in one conditional, then that other reg is corrupted.

-[Unknown]

Comment (hrydgard) [reply Core/MIPS/x86/CompLoadStore.cpp:432]: A problem is that CompITypeMemWrite itself locks and unlocks regs, so I can't reliably do it that way, can I?

Comment (hrydgard) [reply Core/MIPS/x86/CompLoadStore.cpp:432]: Hm, I think the actual bug is in CompITypeMemWrite, in the gpr.R(rt).IsImm() case, since normally we'd end up with rt being mapped coming out of it.

I'll fix that.

Comment (hrydgard) [reply Core/MIPS/x86/CompLoadStore.cpp:432]: Well, not so much a bug as CompITypeMemWrite just not being designed to leave rt writable, fixable with a flag.
