### PR TITLE
Cheats: Split parsing and execution

### LINKED ISSUE #9869: Cwcheat code type not working properly
Hi, the 0xCYYYYYYY 0xZZZZZZZZ (condition code type) has a bug in it, the emulator interprets it differently.

**What it does:** if value @0x0YYYYYYY is not equal to 0xZZZZZZZZ, all the lines after this one will be disabled, including all the codes after this line.

**What it should do:** if value @0x0YYYYYYY is not equal to 0xZZZZZZZZ, all the lines after this one will be disabled, but only up to the next code.

**_Example_:**
```
_C1 DP multiply x2
_L 0xC07008D8 0x0E3C1F11  <------ The condition
_L 0x207008DC 0x02442021  <------ What it should execute or stop
_C1 No banlist
_L 0xC003E454 0x90420002  <------- The first condition affects these lines aswell, which is a bug
_L 0x2003E454 0x34020003
```

### PR DESCRIPTION
**Pull request by unknownbrackets**
I was looking for some harder to find strings in a game, and decided to resort to cheats to have all items, etc., in the hopes of finding those strings.  I ended up looking at the cheat parsing code a little too long, and then this happened.

This adds parsing support (but not UI or file selection support) for a "code database", which seems relatively common.  This just means one file with multiple game ids in it.

It also seems like TempAR could probably be supported by just keeping some "cheat registers" on the CheatEngine class, but my urge to rewrite has now subsided.  I probably won't implement that.

The cheats in the game in question still work, but more types of cheats could probably use more testing.  @LunaMoo not sure if you're a fan of this separation or not, if you think it's a bad change, happy to close or make some adjustments.

-[Unknown]

Fixes #9869

### CODE REVIEW

**Comment by LunaMoo** [comment]
Nice work.
 I'm not exactly a big authority with cheats code types as I end up using only the most basic write and compare myself;], but everything that worked seems to work in fact you fixed one issue I'll edit in to get it auto-closed, looks nicer as well, so feel free to merge whenever you want.

 Actually ~ minor detail - would be nice if you could include '2' in https://github.com/hrydgard/ppsspp/pull/10072/commits/c62a53c223057e51ffbed50f3d280f780ad73b70#diff-8adc5ed2c3593d59136febd952cac349R153 as it was requested for "_C2" to be treated like "_C1" in the past, due to some plugin using it as another "enabled" state.

 As for tempAR format, yeah... lots of work for something which in the end does the same thing - differently.:| Not seeing it attractive either, through I guess 3 basic write code types would be almost a copy paste from cwcheat, if I remember address in TempAR differs by not having the -0x08800000 offset and also code type 0 and 2 are swapped.

**Comment by LunaMoo** [comment]
I had some time and started testing one by one, seems pointer code types got broken, here's a test cheat I made with expected results:

````
_C0 Test code types 6
_L 0x2000103C 0x0880103C // prepare a pointer pointing to itself(we'll use an offset)
_L 0x20001058 0x12345678 // prepare a value for copy type test
// 8 bit write
_L 0x6000103C 0x000000FF //write FF
_L 0x00000001 0x00000004 //with offset 4
//results:
//08801040 000000FF
// 16 bit write
_L 0x6000103C 0x0000FFFF //write FFFF
_L 0x00010001 0x00000008 //with offset 8
//results:
//08801044 0000FFFF
// 32 bit write
_L 0x6000103C 0xFFFFFFFF //write FFFFFFFF
_L 0x00020001 0x0000000C //with offset 0xC
//results:
//08801048 FFFFFFFF
// 8 bit write inverted offset
_L 0x6000103C 0x000000FF //write FF
_L 0x00030001 0xFFFFFFF0 //with offset -0xFFFFFFF0(+0x10)
//results:
//0880104C 000000FF
// 16 bit write inverted offset
_L 0x6000103C 0x0000FFFF //write FFFF
_L 0x00040001 0xFFFFFFEC //with offset -0xFFFFFFEB(+0x14)
//results:
//08801050 0000FFFF
// 32 bit write inverted offset
_L 0x6000103C 0xFFFFFFFF //write FFFFFFFF
_L 0x00050001 0xFFFFFFE8 //with offset -0xFFFFFFE8(+0x18)
//results:
//08801054 FFFFFFFF
// pointer copy
_L 0x6000103C 0x00000004 //copy 4 bytes
_L 0x00000002 0x0000001C //from offset 0x1C
_L 0x10000020 0x00000000 //to offset 0x20
//results:
//0880105C 12345678
````

needs even more cases, but those pointer code types are very confusing, anyway they all seem to fail now.

File: Core/CwCheat.cpp [hunk 1]
```diff
@@ -158,608 +313,709 @@ void CWCheatEngine::CreateCheatFile() {
...
+			op.copyBytesFrom.destAddr = GetAddress(line2.part1 & 0x0FFFFFFF);
+			return op;
+		}
+		return { CheatOp::Invalid };
+
+	case 0x6: // Pointer commands.
+		addr = GetAddress(line1.part1 & 0x0FFFFFFF);
+		if (i < cheat.lines.size()) {
+			const CheatLine &line2 = cheat.lines[i++];
+			const int count = line1.part1 & 0xFFFF;
```
Comment (LunaMoo) [inline Core/CwCheat.cpp]: This is actually taking address part of the pointer code and because of that hitting not enough lines below breaking those annoying 0x6 code types:].

**Comment by LunaMoo** [comment]
I think functionally is same now as it was with addition of one code(0xC) previously affecting all other cheats below fixed, so I'll just merge.
 That whole code looks much better organized now. Thanks.<3
