### PR TITLE
Fix atrac sound loop problem

### LINKED ISSUE #14058: K-On! Houkago Live! main menu music stops playing after first loop
Here's a video for this issue:

https://streamable.com/16tbcy

### LINKED ISSUE #14352: Shinobido - Tales of the Ninja music problems in first level
Hello,

when playing the first level (Prologue) in the game (both European and Japanese versions) the music plays and loops correctly the first two times, then gets all stuttery and choppy the third time. After that it just stops completely. In the next level the music seems to be working and looping correctly.
The bug doesn't seem to happen on youtube playthroughs that I've watched so it might be recent issue.
Tested on pc (standalone & Retroarch) and android (Nvidia SHIELD - Retroarch).

Thanks in advance.

MTR77

### PR DESCRIPTION
**Pull request by sum2012**
Fix #14058 fix #14352
Fix all games loop which use sceAtracGetNextSample
Full of buffer so that no need more atrac data
Modify log:
https://gist.github.com/sum2012/280ebd259a338cbcccbd980caf8bbac0

### CODE REVIEW

**Comment by hrydgard** [comment]
Nice one, this looks really promising - I haven't checked all the logic yet, but it really does look like we were missing that extra offset there.

Will look a little bit closer and then likely merge so this can get wider testing.

File: Core/HLE/sceAtrac.cpp [hunk 1]
```diff
@@ -1629,6 +1629,9 @@ static u32 sceAtracGetNextSample(int atracID, u32 outNAddr) {
 			}
 			if (numSamples > atrac->SamplesPerFrame())
 				numSamples = atrac->SamplesPerFrame();
+			if (atrac->bufferState_ == ATRAC_STATUS_STREAMED_LOOP_FROM_END && numSamples + atrac->currentSample_ > atrac->endSample_) {
+				atrac->bufferState_ = ATRAC_STATUS_ALL_DATA_LOADED;
```
Comment (unknownbrackets) [inline Core/HLE/sceAtrac.cpp:1633]: This doesn't really make sense.

The "loop from end" state basically means that you have a 200 KB music file but have a buffer that is 100 KB.  So it can obviously never fully fit inside that buffer.  `ATRAC_STATUS_ALL_DATA_LOADED` means the entire music file has been fit inside the provided buffer.

What led you to believe it should transition the state here?

-[Unknown]

Comment (sum2012) [reply Core/HLE/sceAtrac.cpp:1633]: It just repeat that play the buffer.it would call sceAtracReleaseAtracID when play another Atrac
