### PR TITLE
HTTP: Ignore failed connects when trying to select

### LINKED ISSUE #18161: PPSSPP's own HTTP client not working at all on Linux
I'm testing on Ubuntu. Went back as far as 1.13, but no version will even open the homebrew store through http??

I don't really understand what's going on, I feel that we should have noticed this before by the homebrew store not working.. Maybe something changed in my network environment, or something.

Strangely, our plain http client does work fine on Windows and Mac, it's just on Linux I'm seeing trouble. Basically when calling send() we just get a broken pipe returned. (I thought connect failed, but it's just that non-blocking sockets are a little confusing). I'm adding more logging now.

This is blocking support for RetroAchievements on Linux (unless we hook up naett and libcurl, but I still want both paths to work).

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #18161 

There's weird stuff going on, we get six results in resolve and three seem to be bad. Currently getting a bunch of these for every time we connect:

15:51:038 Net/HTTPClient.cpp:123 E[HTTP]: connect(66) call failed (101: Network is unreachable)
15:51:038 Net/HTTPClient.cpp:123 E[HTTP]: connect(67) call failed (101: Network is unreachable)
15:51:038 Net/HTTPClient.cpp:123 E[HTTP]: connect(68) call failed (101: Network is unreachable)

Where it seems the first three results succeed in connecting (and then select picks one) and the rest fail with network unreachable. Really not sure what's going on or if it's supposed to be like this, but ignoring the failed connects makes things work, at least.
I'll add more detailed logging to look at those later, first need to get this critical fix in.

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, I guess this will leak the failed-connect sockets as-is. I'll try to fix that.

File: Common/Net/HTTPClient.cpp [hunk 1]
```diff
@@ -117,14 +117,26 @@ bool Connection::Connect(int maxTries, double timeout, bool *cancelConnect) {
...
 			sockets.push_back(sock);
 			FD_SET(sock, &fds);
 			if (maxfd < sock + 1) {
 				maxfd = sock + 1;
 			}
 		}
 
+		if (sockets.empty()) {
+			ERROR_LOG(HTTP, "No resolved address would connect!");
+			// TODO: What do we do here?
```
Comment (unknownbrackets) [inline Common/Net/HTTPClient.cpp:137]: It does retry, so it's fine to let it do that.  Sometimes this will happen for various reasons.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]
Okay, I'd guess your Linux setup has enabled ipv6 but it's broken (maybe at your switch/router) and so the connects are actually failing.  I'm surprised it sounds like these bad sockets were getting marked writable by `select()` for you, though?

-[Unknown]

**Comment by hrydgard** [comment]
Here's the log output I was getting:

37:25:286 Net/HTTPClient.cpp:140 I[HTTP]: connect(56): Ignoring unreachable resolved address a00:50::2606:4700:20:0
37:25:286 Net/HTTPClient.cpp:140 I[HTTP]: connect(57): Ignoring unreachable resolved address a00:50::2606:4700:3031:0
37:25:287 Net/HTTPClient.cpp:140 I[HTTP]: connect(56): Ignoring unreachable resolved address a00:50::2606:4700:20:0
37:25:287 Net/HTTPClient.cpp:140 I[HTTP]: connect(57): Ignoring unreachable resolved address a00:50::2606:4700:3032:0
37:25:287 Net/HTTPClient.cpp:140 I[HTTP]: connect(56): Ignoring unreachable resolved address a00:50::2606:4700:20:0

Indeed seems like broken IPv6 stuff.
