### PR TITLE
Vulkan check for 16bit format support. Fixes running under MoltenVK.

### LINKED ISSUE #12615: MoltenVK: We need to handle texture swizzling not being available
I think we'll just reuse the code used in DX11 on Windows 7 to avoid the 16-bit formats.

See #12583

### PR DESCRIPTION
**Pull request by hrydgard**
MoltenVK, the Vulkan on Metal compatibility layer, lacks support for texturing using the 16-bit formats, so just like we do in D3D11 on Win7 which has the same problem, we now expand such textures to 32-bit color.

Fixes #12615.

Will make finishing #10654 worthwhile.

### CODE REVIEW

**Comment by hrydgard** [comment]
@CarterLi and @Degerz:  here comes the fix.

File: ext/native/thin3d/thin3d_vulkan.cpp [hunk 1]
```diff
@@ -1346,41 +1349,25 @@ std::vector<std::string> VKContext::GetExtensionList() const {
...
-	case DataFormat::R8G8B8A8_UNORM:
-		return FMT_RENDERTARGET | FMT_TEXTURE | FMT_INPUTLAYOUT;
-
-	case DataFormat::R32_FLOAT:
-	case DataFormat::R32G32_FLOAT:
-	case DataFormat::R32G32B32_FLOAT:
-	case DataFormat::R32G32B32A32_FLOAT:
-		return FMT_INPUTLAYOUT;
+	VkFormat vulkan_format = DataFormatToVulkan(fmt);
+	// TODO: Actually do proper check
```
Comment (unknownbrackets) [inline ext/native/thin3d/thin3d_vulkan.cpp]: Still a TODO?

-[Unknown]

File: GPU/Vulkan/TextureCacheVulkan.cpp [hunk 2]
```diff
@@ -1336,7 +1340,8 @@ void TextureCacheVulkan::LoadTextureLevel(TexCacheEntry &entry, uint8_t *writePt
 			decPitch = w * bpp;
 		}
 
-		DecodeTextureLevel((u8 *)pixelData, decPitch, tfmt, clutformat, texaddr, level, bufw, false, false, false);
+		bool expand32 = !gstate_c.Supports(GPU_SUPPORTS_16BIT_FORMATS);
+				DecodeTextureLevel((u8 *)pixelData, decPitch, tfmt, clutformat, texaddr, level, bufw, false, false, expand32);
```
[the remark this answers is not in the document]
Comment (hrydgard) [reply GPU/Vulkan/TextureCacheVulkan.cpp]: I don't know about faux pas, but definitely a silly mistake. Being sloppy after burning a lot of energy on the atlas stuff yesterday...

File: ext/native/thin3d/thin3d_vulkan.cpp (hunk 1 above)
Comment (hrydgard) [reply ext/native/thin3d/thin3d_vulkan.cpp]: Eh, nope.

**Comment by CarterLi** [comment]
Great! Thanks.

It's a pity that Qt port doesn't support Vulkan. Qt port does provide better UI than SDL port.
