### PR TITLE
Allocate memory better  by @unknownbrackets 

### LINKED ISSUE #5638: Grand Theft Auto Vice City Stories Crashed after intro video (Chinese patched version)
Unable to locate the source, but just crashed after video, the only screenshot in crash time is the asm debug as follows: 
crash

0x0000000013D4D9E5 exception (in PPSSPPDebug64.exe): 0xC0000005: access violation in reading location 0x000000007FFFC9E8.

### PR DESCRIPTION
**Pull request by sum2012**
This pick in @unknownbrackets  module branch add 1 crash fix
please note that this pull request also remove the cheat address hack for Gods Eater Burst
Fix #5638

### CODE REVIEW

**Comment by unknownbrackets** [comment]
We should merge this after 1.1.1 imho.  Also might want to double check save states (I can later), been a while since I looked at this branch.

Thanks @sum2012 and @hrydgard for fixing my dumb typo.  Can't believe I missed it...

-[Unknown]

**Comment by hrydgard** [comment]
Yes, let's wait until after 1.1.1 (which I will probably release this weekend, the ARM64 bug that I have now fixed is pretty bad).

**Comment by sum2012** [comment]
Not sure why VS2012 don't raise crash :)

**Comment by unknownbrackets** [comment]
FWIW I made some small tweaks on my branch:
https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:modules

I think that to be accurate, we might want to identify the loaded sceAtrac module, and return the context pointers from there.  They seem to live in user memory allocated with the module prx (e.g. in its data segment or whatever.)

Also, I think they are in fixed places, e.g. id=3 will always be in the same place, even if I deallocate the atrac ID and then reallocate it.  It's possible something might accidentally depend on this...

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets done

File: Core/HLE/sceKernelModule.cpp [hunk 1]
```diff
@@ -1697,27 +1699,19 @@ static u32 sceKernelLoadModule(const char *name, u32 flags, u32 optionAddr)
 	if (!module) {
 		if (magic == 0x46535000) {
 			ERROR_LOG(LOADER, "Game tried to load an SFO as a module. Go figure? Magic = %08x", magic);
-			return -1;
+			// TODO: What's actually going on here?
```
Comment (hrydgard) [inline Core/HLE/sceKernelModule.cpp]: This is Tekken 6 and Soul Calibur being silly and loading all files in a directory as modules, including the SFO file that happens to sit around there, IIRC.

Comment (unknownbrackets) [inline Core/HLE/sceKernelModule.cpp]: Right but I don't believe that the error response on real firmware is -1.  If it is it's probably at least for a larger class of error than just these magic bytes.

-[Unknown]

Comment (hrydgard) [inline Core/HLE/sceKernelModule.cpp]: Hm, right, I remember that..

**Comment by hrydgard** [comment]
OK, time to merge.
