### PR TITLE
More audio buffering fixes (primarily affects SDL)

### LINKED ISSUE #12705: Frequent audio popping and clicking sounds in most games.
### What happens?

In many (Most?) games I experience often frequent minor audio popping and clicking sounds. This is highly distracting and makes it harder to enjoy games.

I have tried most settings and the only one that seems to make any clear impact is disabling `Audio sync (resampling)` which only helps a little. Both `OpenGL` and `Vulkan` are affected as well as both the `SDL` and `Qt` frontends. I also tried PR https://github.com/hrydgard/ppsspp/pull/12602 which did not help.

I tried going back to `v1.0` without finding a good commit.

I can always reproduce it on the title screen for `Lunar Silver Star Harmony` where the FPS and speed counter is a solid 60 and 100% respectively.

Other games I have experienced in are:

* Growlanser: Wayfarer of Time
* Legend of Heroes Ao no Kiseki
* Nayuta: Endless Trails
* Riviera The Promised Land
* Tales of Eternia (Rare)
* Tales of Rebirth
* Tekken 6 (Rare)
* Valkyrie Profile

One game I have not noticed it in is `Guilty Gear XX Accent Core Plus`.

### What *should* happen?

Audio should be smooth and not suffer from popping or clicking sounds.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS: `Slackware64-current`
GPU: `RX Vega 56`
CPU: `AMD FX-6350`
compiler: `clang-10.0.0`, `gcc-9.2.0`
mesa: https://github.com/mesa3d/mesa/commit/461ee852486da724c79c5145fa2e50bdfa54aa55
llvm: `10.0.0`
alsa-lib: `1.2.1.2`
Qt: `5.14.1`
SDL: `2.0.10`
ppsspp: https://github.com/hrydgard/ppsspp/commit/d0e2aa3a4f394cedc956df3df24ce335d3f6d974

### PR DESCRIPTION
**Pull request by hrydgard**
Started with the assumption that something was wrong with the rate adjustment logic, but couldn't find anything, just bad variable names not describing what was going on. Instead it turned out that the target buffer size (which is what lowwatermark really was) simply was lower than the default buffer size in SDL, which can never work reliably, leading to #12705. 

Eventually ended up clamping the target buffer size so it's always larger than the SDL buffer size with some margin, and also reduced the SDL buffer size from 2048 to 1024.

So this change could have been a bit smaller but I want to keep the renaming and minor refactorings I did.

I want to later change to SDL_QueueAudio but really wanted to get this solid first.

Ported the changes to the SDL audio code used by Qt, too (we should really share that...)

Fixes #12705 , hopefully.

### CODE REVIEW

**Comment by hrydgard** [comment]
Just gonna go ahead and merge, I think it's pretty safe.

File: Core/HW/StereoResampler.cpp [hunk 1]
```diff
@@ -248,7 +263,8 @@ unsigned int StereoResampler::Mix(short* samples, unsigned int numSamples, bool
 	// Flush cached variable
 	m_indexR.store(indexR);
 
-	return realSamples / 2;
+	// TODO: What should we actually return here?
```
Comment (unknownbrackets) [inline Core/HW/StereoResampler.cpp:266]: I do think actually produced samples is best, then padding can be decided per platform.

-[Unknown]

**Review by unknownbrackets — COMMENTED** [review]
Nice, this makes sense.  Definitely more readable now...

-[Unknown]
