### PR TITLE
More sizing fixes. I think this will do it for 1.9.3.

### LINKED ISSUE #12381: Touch screen offset issues again
Getting multiple reports of this, and another from @weihuoya in https://github.com/hrydgard/ppsspp/pull/12033 who suggests adding back

``` NativeApp.setDisplayParameters(pixelWidth, pixelHeight, (int) densityDpi, refreshRate);```

to NativeActivity::surfaceCreated.

I'm going to try that and also create a touch test screen for users to check the touch accuracy.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #12381, for good this time.

### CODE REVIEW

File: android/src/org/ppsspp/ppsspp/NativeActivity.java [hunk 1]
```diff
@@ -813,6 +820,27 @@ protected void onResume() {
 		}
 	}
 
+	@Override
+	public void onAttachedToWindow() {
```
Comment (unknownbrackets) [inline android/src/org/ppsspp/ppsspp/NativeActivity.java]: Ah, this seems like also a good place to setup the system UI callback.

-[Unknown]

Comment (hrydgard) [reply android/src/org/ppsspp/ppsspp/NativeActivity.java]: Yup - would happily merge such a change.
