### PR TITLE
Fix "Akaya Akashiya Ayakashi" umd switch

### LINKED ISSUE #9110: Akaya Akashiya Ayakashi UMD switch not possible
I've been playing the game "Akaya Akashiya Ayakashi no" which requires a UMD switch halfway through the game. At the end of Disc 1 the game asks you to change the UMD while it's running. So I pause the emulation, Switch the UMD and resume, but nothing happens.

### PR DESCRIPTION
**Pull request by sum2012**
Also,make "switch umd" menu enable faster,
fix #9110 
modify log:
https://gist.github.com/sum2012/e9557e6879f43361582e6810d0ba79e7

### CODE REVIEW

**Comment by sum2012** [comment]
I forgot said.
Happy new Chinese new year

**Comment by hrydgard** [comment]
Oh yeah. Happy year of the rooster!

File: Core/HLE/sceUmd.cpp [hunk 1]
```diff
@@ -51,6 +55,7 @@ static std::vector<SceUID> umdWaitingThreads;
 static std::map<SceUID, u64> umdPausedWaits;
 
 bool UMDReplacePermit = false;
+bool UMD_insterted = true;
```
Comment (hrydgard) [inline Core/HLE/sceUmd.cpp]: Please rename UMDInserted , simple spelling mistake :)

File: Core/HLE/sceUmd.cpp [hunk 2]
```diff
@@ -495,7 +504,9 @@ void __UmdReplace(std::string filepath) {
 		}
 	}
 	delete currentUMD;
-
+	UMD_insterted = false;
+	sleep_ms(200); // Wait sceUmdCheckMedium call
```
Comment (hrydgard) [inline Core/HLE/sceUmd.cpp]: Hm, this isn't very nice .. on the other hand, this will probably be pretty reliable as long as __UmdReplace is not called from the emulator thread. I fear though that it may be, on Android? Got to check to be sure though.

Comment (hrydgard) [inline Core/HLE/sceUmd.cpp]: A better solution may be to schedule an event (you know, RegisterEvent and so on) that will set UMDInserted back after a little bit.

**Review by hrydgard — CHANGES_REQUESTED** [review]

File: Core/HLE/sceUmd.cpp (hunk 1 above)
Comment (sum2012) [inline Core/HLE/sceUmd.cpp]: Done

**Comment by sum2012** [comment]
@hrydgard Here is my first time to write a event.
It is a good challenge for me :)

**Comment by hrydgard** [comment]
Nice, looks good! It works, too, right? :)

Now the only thing I'm thinking about is savestate support for this, but it would be kind of silly to create a new savestate right when changing discs?

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
Actually we definitely need to save the event number. And that means that yes, you're gonna have to make a little version check in DoState. When loading an old state, you'll probably want to simply not call RestoreRegisterEvent...

**Comment by sum2012** [comment]
Yes,It still work,but it seems UnitTest not to work.
12>Core.lib(sceUmd.obj) : error LNK2019: unresolved external symbol "void __cdecl MainWindow::_ChangeMenu(void)" (?_ChangeMenu@MainWindow@@YAXXZ) referenced in function "void __cdecl __UmdDoState(class PointerWrap &)" (?__UmdDoState@@YAXAEAVPointerWrap@@@Z)
12>F:\Project\test\107\ppsspp\Windows\x64\Debug\UnitTest.exe : fatal error LNK1120: 1 unresolved externals

**Comment by hrydgard** [comment]
Hm, curious. I'll see if I can find a solution tomorrow.

**Comment by sum2012** [comment]
Please don't make change of MainWindowMenu.cpp on master.
I don't want to rebase,I can remove ChangeMenu function on this pull request first.

**Comment by hrydgard** [comment]
I can fix it up on this branch before merging. Don't worry about it, I'll take it from here, later today :)

**Comment by hrydgard** [comment]
Merged and committed a fix on top. Don't know why it didn't end up inside the merge but meh, should be fine now :)

**Comment by sum2012** [comment]
Very Thanks.

**Comment by sum2012** [comment]
@hrydgard A small note:
Some baidu ppsspp forum of people said that when they update their phone 's firmware from 6.0 to 7.0,their phone is faster in playing in ppsspp.

**Comment by hrydgard** [comment]
Probably they got better graphics drivers with the upgrade. Especially on Android, good graphics drivers are very important for PPSSPP's performance.

**Comment by aranypikkely** [comment]
Hi! Sorry, I really don't understand programming. Can you help me? I would like to play Akaaka, but can't switch umd. How can i switch it?

**Comment by sum2012** [comment]
@aranypikkely  Download newest version in http://buildbot.orphis.net/ppsspp/

**Comment by aranypikkely** [comment]
Hi! Thanks! I downloaded it. So: it seems to switch the umd. But if i load the second umd, than switch the first, it plays just the first umd.

**Comment by sum2012** [comment]
Do you mean that cannot switch again second umd ?

**Comment by aranypikkely** [comment]
It went like this: on the end of the 1. umd i saved the game
then on the beginning of the 2. umd i had to load the saved data (you can't avoid it)
then in the menu i choose to begin the game 
and the text appeard: switch first umd
i switched
and not the second but the first part began - not a normal way, but with a high speed
(on the top of the emulator you could see: 2. part)

Maybe i made some mistake?

**Comment by sum2012** [comment]
1:put the save  https://drive.google.com/file/d/0B3OaSdeV0L8kaWgybDlTWVZiUmc/view?usp=sharing into ppsspp 
2:Load disc 2 first,It will tell you load save data. http://i.imgur.com/QnGc02s.jpg 
3:Click resume http://i.imgur.com/5ATxJRX.jpg,it would tell you load again save data http://i.imgur.com/IjkiI7M.jpg ,and confirm it http://i.imgur.com/dkTSPrq.jpg
4:It tells you change disc 1 http://i.imgur.com/tDAajPO.jpg
5:Then it tells you change again disc 2 http://i.imgur.com/52w8fLO.jpg
6:It will continue the story http://i.imgur.com/W6nk5cA.jpg

**Comment by sum2012** [comment]
@aranypikkely The saved data is from https://github.com/hrydgard/ppsspp/issues/9110#issuecomment-257860969

@kurasamesusaya Can you share that your save data that  what path was choosed during the game?

**Comment by sayaaki** [comment]
@sum2012 Can you show a more detailed guide? I'm lost between step 4 and 5. Like, I change to disc 1 like at step 4 but the game just start over again and doesn't show any picture like in step 5. And also can you show me how to change umd? The way I did it, I press Esc - switch umd - disc 1 - continue. Is it the right way?

**Comment by sum2012** [comment]
@sayaaki  The way you chanage umd is right.Maybe you forget save data before end of disc 1.
Anyway,you can try to use my save data https://drive.google.com/file/d/0B3OaSdeV0L8kaWgybDlTWVZiUmc/view?usp=sharing 

umd change video:
https://drive.google.com/file/d/0B3OaSdeV0L8kUXRpM195cHFQdHM/view?usp=sharing

**Comment by sayaaki** [comment]
uhm but if the path I choose was different how can I continue from that path?

**Comment by sayaaki** [comment]
and why can't I do the same thing with my own save instead of the save shared above?

**Comment by sum2012** [comment]
@sayaaki first, give me your save data to me test.
Of course,need to zip your save data folder first.

**Comment by sayaaki** [comment]
https://drive.google.com/file/d/0BzywMW3udB2obHJ5ZWpwWG1wd0E/view?usp=sharing

here

**Comment by sum2012** [comment]
Maybe you need play again to get new story.
I might be try it when I have time.
I need OT this week ,not much time to test.
