### PR TITLE
PSPOskDialog: Add range check on keyboard layouts

### LINKED ISSUE #17313: libretro so crash
### Game or games this happens in

unknow

### What area of the game / PPSSPP

ppsspp\Core\Dialog\PSPOskDialog.cpp

line:  775

void PSPOskDialog::RenderKeyboard()
{
        
	int selectedRow = selectedChar / numKeyCols[currentKeyboard];
	int selectedCol = selectedChar % numKeyCols[currentKeyboard];

	char16_t temp[2];
	temp[1] = '\0';

	std::string buffer;

	static const u32 FIELDDRAWMAX = 16;
	u32 limit = FieldMaxLength();
	u32 drawLimit = std::min(FIELDDRAWMAX, limit);   // Field drew length limit.

	const float keyboardLeftSide = (480.0f - (24.0f * numKeyCols[currentKeyboard])) / 2.0f;
	const float characterWidth = 12.0f;
	float previewLeftSide = (480.0f - (12.0f * drawLimit)) / 2.0f;
	float title = (480.0f - (0.5f * drawLimit)) / 2.0f;

### What should happen

int selectedRow = selectedChar / numKeyCols[currentKeyboard];
	int selectedCol = selectedChar % numKeyCols[currentKeyboard];

these code has crash, Do you need to verify this code before using it？

### Logs

_No response_

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

    motorola hawao (moto g42)

### PPSSPP version affected

39d765186697c3454df85b88bd6789025d6375f0

### Last working version

_No response_

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
Also shrinks some arrays.

Fixes #17313

(We really should somehow get rid of marking this file as binary in .gitattributes).

### CODE REVIEW

File: Core/Dialog/PSPOskDialog.cpp [hunk 1]
```diff
@@ -1173,6 +1178,8 @@ void PSPOskDialog::DoState(PointerWrap &p)
 	if (!s)
 		return;
 
+	// TODO: Should we save currentKeyboard/currentKeyboardLanguage?
```
Comment (unknownbrackets) [inline Core/Dialog/PSPOskDialog.cpp:1181]: Personally, I don't think so.  It's not exposed to the game in any way, and it might change between versions.  Seems safer not to save.

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe we should just change the Unicode in the file to escape sequences entirely, and switch it back to UTF-8.  Or maybe Visual Studio no longer gets completely confused...

-[Unknown]
