### PR TITLE
Camera initialization crash fix

### LINKED ISSUE #13091: Invizimals crash when camera initialized  - 1.10.1
This is my first time writing here,so i will try to help as much as i could,i'm open to anything,GitHub is new to me and PPSSPP as well,i'm veteran in Gameboy Advance emulation on Android with emulator called MyBoy! GBA Emulator.

I got an USA .ISO game Invizimals,and when i tried 1.5.4 back in the day,game showed some bad written **PPSSPP Camera :)**
Since really lot of time passed since that version,i decided i should give it a try and i basically did,and i noticed some new settings that seem to optimize emulation and i was lucky to give it a try,including Invizimals,but when i saw it still crashes,i decided i should report bug to you developers in order for you to fix it

Phone:Honor 9S
GPU:PowerVR GE8320
CPU:Metiatek MT6762R Helio P22
Camera:8 MP, f/2.0, (wide), AF
Phone camera is 
- 0:Back Camera

**Camera permission is enabled in Settings,and Location is too as well**

TIA

Edit:
- 0 is Back Camera,not Front

### PR DESCRIPTION
**Pull request by hrydgard**
The logic for choosing a preview size was entirely broken. Improve it.

Fixes #13091 .

@Florin9doi have a look if you have time :)

### CODE REVIEW

File: android/src/org/ppsspp/ppsspp/CameraHelper.java [hunk 1]
```diff
@@ -166,16 +187,41 @@ void startCamera() {
 			mCamera = Camera.open(cameraId);
 			Camera.Parameters param = mCamera.getParameters();
 
+			List<Integer> supportedPreviewFormats = param.getSupportedPreviewFormats();
+			for (int i = 0; i < supportedPreviewFormats.size(); i++) {
+				Log.i(TAG, "Supported preview format: " + i);
```
Comment (Florin9doi) [inline android/src/org/ppsspp/ppsspp/CameraHelper.java:192]: i or supportedPreviewFormats.get(i) ?

Comment (hrydgard) [reply android/src/org/ppsspp/ppsspp/CameraHelper.java:192]: I'll just get rid of the logging, it was kinda pointless.
