### PR TITLE
Fix regression caused by the new depal code for Vulkan. Fixes #10993

### LINKED ISSUE #10993: Metal Gear Solid Peace Walker Vulkan Rendering
### What happens?
Vulkan rendering is not right.  Too bright with patches

### What *should* happen?
Should look like the OpenGL render.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android Snapdragon 820 ZTE Phone, PPSSPP Dev Ver 1.5.4-947

OpenGL Render:
screenshot_2018-05-01-14-31-37

Vulkan Render:
screenshot_2018-05-01-14-31-10

### PR DESCRIPTION
**Pull request by hrydgard**
Not all of this is actually needed to fix it, but it's right I think :)

The issue was that when first texturing using depal and then without depal from another framebuffer, we forgot to reset the depal state so it would use depal even though it shouldn't.

### CODE REVIEW

File: GPU/Vulkan/TextureCacheVulkan.cpp [hunk 1]
```diff
@@ -344,7 +344,7 @@ void TextureCacheVulkan::ApplyTextureFramebuffer(TexCacheEntry *entry, VirtualFr
 	DepalShaderVulkan *depalShader = nullptr;
 	uint32_t clutMode = gstate.clutformat & 0xFFFFFF;
 
-	bool useShaderDepal = true;
+	bool useShaderDepal = framebufferManager_->GetCurrentRenderVFB() != framebuffer;
```
Comment (unknownbrackets) [inline GPU/Vulkan/TextureCacheVulkan.cpp]: Ah yes.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]
