### PR TITLE
x86-64: Add ability to run without RIP addressing between generated code and global data

### LINKED ISSUE #9741: Loading save state sometimes causes crash on linux x64
Sometimes, loading a save state will cause ppsspp to crash.  It doesn't happen that frequently, but spamming load 20-30 times will generally trigger it.  (Reproduced on ppsspp 1.4.1 and also latest git source)

I did a bit of digging, and the cause seems to be that in the Jit constructor, it allocates a region for the .code pointer with AllocateExecutableMemory.  This provides a hint to mmap aimed at allocating these in close regions of memory, but it looks like in the cases where it can't allocate the region exactly at the hint pointer (presumably where we overlap with some other mapped region), it can actually differ by quite a bit.

Eg. when debugging, an allocation with map_hint=0x40cc0000 returned an address way up in high memory (0x7ff8e08a9000).  This seems to be the cause of the crash, as in OpArg::WriteRest in x86emitter.cpp, it's triggering the error assert about being out of range for RIP addressing.  The crash itself happens later, with a useless call stack (I assume when running the JITted code), but presumably is triggered by the wrong offset that gets provided here.

The mmap manpage does suggest that "addr is taken to be a suggestion of a process address near which the  mapping", but in practice it looks like it can differ quite a bit if it can't get the exact region.  A brief look at the [linux source](http://elixir.free-electrons.com/linux/latest/source/arch/x86/kernel/sys_x86_64.c#L140) seems to indicate that (on x86_64 at least), addr is only used if it can map that exact region.  As such, it doesn't look like that "near the mapping" means much.

### PR DESCRIPTION
**Pull request by hrydgard**
It's fine to run faster if we can arrange things so that the generated code is close to the binary in memory, but if not, we should still be able to run. 

This will make us more resilient to strange ASLR implementations and embedding within other programs like RetroArch.

This should work around but not properly fix #9741.

### CODE REVIEW

**Comment by hrydgard** [comment]
I think this is complete now - it works when I globally disable RIP addressing (though there's still the possibility of some sneaking through somewhere....)

**Comment by hrydgard** [comment]
Alright, now it runs on Linux properly too.

**Comment by hrydgard** [comment]
Actually found a couple more instances of RIP addressing... fixing the last stuff now.

**Comment by hrydgard** [comment]
Finally works :P Will merge when builds come back green.

**Comment by Orphis** [comment]
R.I.P. RIP?

**Comment by hrydgard** [comment]
Not exactly, in many cases we keep the RIP path but add an alternative if it can't reach - but good pun :)

File: Core/MIPS/x86/CompVFPU.cpp [hunk 1]
```diff
@@ -2169,7 +2209,7 @@ void Jit::Comp_VV2Op(MIPSOpcode op) {
 		} else {
 			MOV(32, R(EAX), fpr.V(sreg));
 		}
-		CallProtectedFunction((const void *)sinCosFunc, R(EAX));
+		CallProtectedFunction((const void *)sinCosFunc, R(EAX), Imm32((uint32_t)(uintptr_t)&mips_->sincostemp[0]));
```
Comment (unknownbrackets) [inline Core/MIPS/x86/CompVFPU.cpp]: Why not just `R(RDX)`/`R(RDI)`?  Won't this fail if the pointer isn't in low RAM?  Isn't that the case on iOS or retroarch or something?

-[Unknown]

**Review by unknownbrackets — COMMENTED** [review]
I think this is a necessary evil, but we should still fix the original bug that's causing the "close RAM finder" to wrap incorrectly, right?

-[Unknown]

File: Core/MIPS/x86/CompVFPU.cpp (hunk 1 above)
Comment (hrydgard) [inline Core/MIPS/x86/CompVFPU.cpp]: First, this is in a 32-bit ifdef segment. Second, CallProtectedFunction is one weird wrapper..

**Comment by hrydgard** [comment]
Yes, if possible that bug should also be fixed. Don't really know where to start on that one though.

File: Core/MIPS/x86/CompVFPU.cpp (hunk 1 above)
Comment (unknownbrackets) [inline Core/MIPS/x86/CompVFPU.cpp]: Ah, the ifdefs mislead me, sorry.

-[Unknown]
