### PR TITLE
Android scaling fixes

### LINKED ISSUE #9866: Android split-screen multitasking does not actually works.
If I will open ppsspp with the second application via android's multitasking feature this will happen:
default
default
And controls in this mode are totally messed up.

Maybe you should have a message that your app doesn't support split-screen like other apps do:
default
(camera was a good example)

### PR DESCRIPTION
**Pull request by hrydgard**
This now uses surfaceHolder callbacks to get the pixel width/height for screen sizing, which is more accurate than the old hacky method. This means that we now share the DPI calculations between GL and Vulkan backends (and the EGL setup which is not used) which is good.

This fixes #9866 properly.

Additionally, this splits up dpi scaling in to X and Y components but not really doing anything with that yet. This could be used to support weird pixel ratios but those are not very common these days. Android devices actually do have very slightly different X and Y DPI scaling sometimes but usually too little to really matter, would like to get this right at some point though.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Sounds really cool - will look more thoroughly later.

-[Unknown]

**Comment by hrydgard** [comment]
The sequence of commits ended up a little messy because I first was going to work around the issue where the display gets stretch in immersive mode on some devices with the x/y dpi, but then I figured out how to fix it properly instead. Basically just went by example: https://github.com/google/grafika/blob/master/src/com/android/grafika/HardwareScalerActivity.java#L133

**Comment by hrydgard** [comment]
Last travis error was just travis' apple servers being down again, happens a lot..

File: android/src/org/ppsspp/ppsspp/NativeActivity.java [hunk 1]
```diff
@@ -681,7 +681,7 @@ public void onConfigurationChanged(Configuration newConfig) {
 			Point sz = new Point();
 			getDesiredBackbufferSize(sz);
 			if (sz.x > 0) {
-				mGLSurfaceView.getHolder().setFixedSize(sz.x/2, sz.y/2);
+				mGLSurfaceView.getHolder().setFixedSize(sz.x, sz.y);
```
Comment (unknownbrackets) [inline android/src/org/ppsspp/ppsspp/NativeActivity.java]: Hmm, yeah.  It's been there [for a while](https://github.com/hrydgard/ppsspp/commit/1012f46dee3473376eff2a549c64a7f2356461b0#diff-b466153019b453972ac2157a51b625ebR468).

-[Unknown]

File: UWP/PPSSPP_UWPMain.cpp [hunk 2]
```diff
@@ -281,13 +283,15 @@ bool PPSSPP_UWPMain::OnHardwareButton(HardwareButton button) {
 void PPSSPP_UWPMain::OnTouchEvent(int touchEvent, int touchId, float x, float y, double timestamp) {
 	// We get the coordinate in Windows' device independent pixels already. So let's undo that,
 	// and then apply our own "dpi".
-	float dpiFactor = m_deviceResources->GetActualDpi() / 96.0f;
-	dpiFactor /= pixel_in_dps;
+	float dpiFactor_x = m_deviceResources->GetActualDpi() / 96.0f;
+  float dpiFactor_y = dpiFactor_x;
```
Comment (unknownbrackets) [inline UWP/PPSSPP_UWPMain.cpp]: nit: Indent faux pas.

-[Unknown]

File: Windows/GEDebugger/CtrlDisplayListView.cpp [hunk 3]
```diff
@@ -46,7 +46,7 @@ CtrlDisplayListView::CtrlDisplayListView(HWND _wnd)
 	instructionSize = 4;
 
 	// In small window mode, g_dpi_scal may have been adjusted.
```
Comment (unknownbrackets) [inline Windows/GEDebugger/CtrlDisplayListView.cpp]: Oops, I must've lost the e in scale... sorry.

-[Unknown]

File: android/jni/app-android.cpp [hunk 4]
```diff
@@ -705,21 +705,58 @@ extern "C" void Java_org_ppsspp_ppsspp_NativeRenderer_displayResize(JNIEnv *, jo
...
+
+	dp_xres = display_xres * g_dpi_scale_x;
+	dp_yres = display_yres * g_dpi_scale_y;
+
+	// Touch scaling is from display pixels to dp pixels.
+	dp_xscale = (float)dp_xres / (float)display_xres;
+	dp_yscale = (float)dp_yres / (float)display_yres;
+
+	pixel_in_dps_x = (float)pixel_xres / dp_xres;
+	pixel_in_dps_y = (float)pixel_yres / dp_yres;
```
Comment (unknownbrackets) [inline android/jni/app-android.cpp]: Seems a bit of a shame for the above not to be in a shared function with `displayResize`.  I see it was only moved around, though.

-[Unknown]

File: ext/native/gfx_es2/draw_text.cpp [hunk 5]
```diff
@@ -34,7 +34,7 @@ void TextDrawer::SetFontScale(float xscale, float yscale) {
 }
 
 float TextDrawer::CalculateDPIScale() {
-	float scale = g_dpi_scale;
+	float scale = g_dpi_scale_x;
```
Comment (unknownbrackets) [inline ext/native/gfx_es2/draw_text.cpp]: `CtrlDisplayListView.cpp` used y, I think we should pick one and use it for any text scaling.  I have no strong opinion on which.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]
Cool, LGTM.  A couple nits but nothing really.

-[Unknown]

File: android/jni/app-android.cpp (hunk 4 above)
Comment (hrydgard) [inline android/jni/app-android.cpp]: Oh, displayResize was supposed to be deleted, it's no longer used.

File: ext/native/gfx_es2/draw_text.cpp (hunk 5 above)
Comment (hrydgard) [inline ext/native/gfx_es2/draw_text.cpp]: Let's go for y.
