### PR TITLE
Dispatcher core state fix

### LINKED ISSUE #9398: Midnight Club flickers when using the JIT on OS X
Recent versions of dev-latest and dev-working PPSSPP have constant flickering or just black screen with JIT enabled. Example game: Midnight Club LA Remix. Right after hardware tessellation was introduced, the first build bot version (or two) worked fine, but since, if in-game doesn't flicker, its just black, and can't even get back to PPSSPP settings. Even the dev-working version is doing the same thing. Tried deleting ppsspp.ini, and does not fix. When using IR Interpreter the game loads and works fine, but of course is extremely slow. Can someone at least  post a version of the last PPSSPP version for OS X that isn't broken? Also noticed in-game with PPSSPP for iOS, constant flickering of on-screen controls upside down on screen, and this has also been happening with versions from the past couple months.
I have tried every combination of settings, turning on and off, testing and testing, and nothing.

Macbook Pro, El Capitan 10.11.6, PPSSPP v1.3-807-g150619c
iPhone 7, iOS 10.1.1(JB), PPSSPP (gave up and uninstalled)

### PR DESCRIPTION
**Pull request by hrydgard**
Fix bug where dispatcher would not check core state directly after Advance.

Fixes #9398 properly (it was previously hidden somehow with extra backbuffer binds)

### CODE REVIEW

**Comment by hrydgard** [comment]
@unknownbrackets I really think this is right, but please have a look anyway :)

File: Core/MIPS/x86/Asm.cpp [hunk 1]
```diff
@@ -162,7 +163,6 @@ void Jit::GenerateFixedCode(JitOptions &jo) {
 			// IMPORTANT - We jump on negative, not carry!!!
 			FixupBranch bail = J_CC(CC_S, true);
 
-			SetJumpTarget(skipToRealDispatch);
 			SetJumpTarget(skipToRealDispatch2);
```
Comment (unknownbrackets) [inline Core/MIPS/x86/Asm.cpp]: Well, I guess there's no need to call this `2` now.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]

File: Core/MIPS/x86/Asm.cpp (hunk 1 above)
Comment (hrydgard) [inline Core/MIPS/x86/Asm.cpp]: Well, yeah. I'll change it the next time there's something in the dispatcher to fix :)
