### PR TITLE
Fix Game/Info screen lagginess and crash when moving a window.

### LINKED ISSUE #9004: Constant I/O usage in the game info screen
Since v1.2.2-853-g0924dbf https://github.com/hrydgard/ppsspp/pull/8900
The more saves(not save states)you have,the bigger it will be.

I have 103 and it's around 830kb per second.

### PR DESCRIPTION
**Pull request by LunaMoo**
Fixes crash reported in the forum [here](http://forums.ppsspp.org/showthread.php?tid=22580)

And also getting savedata info on every update was bad idea:P.
Fix #9004

### CODE REVIEW

**Comment by hrydgard** [comment]
Thanks!

File: UI/GameScreen.h [hunk 1]
```diff
@@ -73,4 +73,5 @@ class GameScreen : public UIDialogScreenWithGameBackground {
 	UI::Choice *btnDeleteGameConfig_;
 	UI::Choice *btnDeleteSaveData_;
 	std::vector<UI::Choice *> otherChoices_;
+	std::vector<std::string> saveDirs;
```
Comment (unknownbrackets) [inline UI/GameScreen.h]: This should have a `_` suffix.

-[Unknown]
