### PR TITLE
Control and menu navigation fixes

### LINKED ISSUE #17585: Controller not working properly
As you can see on the video only analog and direction button is working even tho i set up the buttons according to my controller

https://github.com/hrydgard/ppsspp/assets/67460268/f979f1ec-6706-4eb0-bfac-e60cd658c186

Other buttons are not responding

### LINKED ISSUE #17641: Menu navigation regression
Just a reminder to fix. Renan007 reported on Discord:

> I don't know why but when I try to navigate the menu using the controller (GameSir T3s) it doesn't work but in the game it works, before it was working but I don't know from which version it stopped working, my device is Moto G5

> I tested it in this version (https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.15.4-71-gc2fb81572&platform=android) and menu navigation still works but in this version (https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.15.4-80-g4704bc92a&platform=android) it stopped working

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #17641 
Fixes #17585

Didn't test enough after #17514 and later adding the new overlay stuff, oops.

This also reduces redundant processing of axis events.

### CODE REVIEW

File: Common/UI/Root.cpp [hunk 1]
```diff
@@ -249,6 +258,7 @@ KeyEventResult UnsyncKeyEvent(const KeyInput &key, ViewGroup *root) {
 		retval = KeyEventResult::PASS_THROUGH;
 		break;
 	default:
+		retval = KeyEventResult::ACCEPT;
```
Comment (unknownbrackets) [inline Common/UI/Root.cpp:261]: What's the purpose of `KeyEventToFocusMoves()`'s logic then?  For example, `return KeyEventResult::IGNORE_KEY;` would just be ignored, so multiple key repeat systems would indeed overlap, right?

-[Unknown]

Comment (hrydgard) [reply Common/UI/Root.cpp:261]: That's a good question. I think the answer is that we should check for repeats again here..
