### PR TITLE
More misc code cleanup, fix setting softgpu in game-specific settings

### LINKED ISSUE #20923: Setting software rendering in game config doesn't work
When enabling "Software Rendering" in the game config it doesn't actually apply once booting up the game, it's still set to the rendering mode in the global settings.

### PR DESCRIPTION
**Pull request by hrydgard**
- logging perf improvement
- game-specific config can now affect software rendering correctly (fixes #20923)
- minor code cleanup

### CODE REVIEW

File: Core/System.cpp [hunk 1]
```diff
@@ -421,7 +416,9 @@ static bool CPU_Init(FileLoader *fileLoader, IdentifiedFileType type, std::strin
 		g_CoreParameter.mountIsoLoader = ConstructFileLoader(g_CoreParameter.mountIso);
 	}
 
-	// TODO: Check Game INI here for settings, patches and cheats, and modify coreParameter accordingly
+	// Game-specific settings are load from for example Load_PSP_ISO (which calls g_Config.loadGameConfig).
```
Comment (Nemoumbra) [inline Core/System.cpp]: Typo
