### PR TITLE
Use glslang to translate GLSL 1.x postshaders to GLSL 3.0 or later 

### LINKED ISSUE #10362: Postprocessing shaders don't work with GL Core contexts (affects mac, windows, linux?)
What happens?

When you select any postprocessing shader from the graphics options, the shader will not apply and instead spit this error message out to the Terminal:

```
E[FRAMEBUF]: GLES/FramebufferManagerGLES Failed to build post-processing program from shaders/natural.vsh and shaders/natural.fsh!
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:3: 'attribute' : syntax error: syntax error
```

Steps to reproduce:
1. Start a game
2. Go to the pause menu -> settings -> graphics -> post processing shaders -> pick any (I used Natural Colors in this test)

What *should* happen?

The shader should run correctly and change the graphics as desired.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

It's a hackintosh, but the GPU is fully supported by the Nvidia Web Drivers.

CPU: Intel i7 5930k @ 3.5GHz
GPU: Nvidia Geforce GTX 970 4GB
Driver: Nvidia Web Driver 378.10.10.10.20.109
PPSSPP version: 1.5.4-23-g3b7868767

The offending commit appears to be https://github.com/hrydgard/ppsspp/commit/e3eb6d36b16506f8c7cc5c6de613cf246499c4d6. The one prior to that (https://github.com/hrydgard/ppsspp/commit/9a732fe52eb25ce92f0289f08d86bd4ca648fdd2), as well as v1.5.4 release/stable and v1.5.3 stable do not exhibit this behaviour.

### PR DESCRIPTION
**Pull request by hrydgard**
To appease strict GL Core drivers. Should fix #10362

### CODE REVIEW

**Comment by hrydgard** [comment]
No idea why it will only link on Android... hm.

**Comment by hrydgard** [comment]
That doesn't work because we need to switch STL to libc++ first... I'll do that separately.

File: GPU/Common/ShaderTranslation.cpp [hunk 1]
```diff
@@ -307,8 +303,24 @@ bool TranslateShader(std::string *dest, ShaderLanguage destLang, TranslatedShade
...
+	{
+		spirv_cross::CompilerGLSL glsl(std::move(spirv));
+		// The SPIR-V is now parsed, and we can perform reflection on it.
+		spirv_cross::ShaderResources resources = glsl.get_shader_resources();
+		// Set some options.
+		spirv_cross::CompilerGLSL::Options options;
+		if (gl_extensions.ver[0] >= 4) {
+			options.version = 400;
+		} else {
+			options.version = 300;
```
Comment (unknownbrackets) [inline GPU/Common/ShaderTranslation.cpp]: I had an issue on Mac where I had to specify exactly the same version.  Maybe I was mistaken and it was only the major version, but it seemed to need 1:1.

That's what motivated this code:
https://github.com/hrydgard/ppsspp/blob/33e500a6817b7d5dd0daa9c663cde2ac38ca48b9/ext/native/gfx_es2/gpu_features.cpp#L501

I'm also pretty sure 3.1 and 3.2 needed those specific versions too (you can test by hardcoding versions in PCMain iirc.)

-[Unknown]

Comment (hrydgard) [reply GPU/Common/ShaderTranslation.cpp]: Seems odd that it would be that strict about version, especially if we specify just the major version... but maybe worth doing. Should be noted that GLSL language versions are distinct from GL versions although they did synchronize them after 3.0 I think?

Comment (unknownbrackets) [reply GPU/Common/ShaderTranslation.cpp]: Right - this path is only non-ES right?

-[Unknown]

Comment (hrydgard) [reply GPU/Common/ShaderTranslation.cpp]: In practice mostly yeah - it's not used on Android. Though, I guess there's Raspberry Pi and things like that, and iOS...  Should probably tighten it up a little.
