### PR TITLE
Mouse improvements

### LINKED ISSUE #11226: Analog axis keeps tiny values even when there's no input(mouse/gamepad analog)
Following the discussion in the [forum](https://forums.ppsspp.org/showthread.php?tid=24439) about mouse control not working as easily as third party one(glovePIE) only when mapping axis to PSP buttons I made https://github.com/hrydgard/ppsspp/compare/master...LunaMoo:AxisToButtonThreshold however I noticed a separate problem - if too small threshold is allowed, PPSSPP get's input even if there's none.

 It's like something doesn't clear input properly and a tiny value not always, but very commonly "sticks" to emulated analog axis:], I noticed it as well in the past while making right analog patches but I thought back then that my gamepad just is old and missbehaves so I added high deadzone by default to all my patches, but I guess it could just be some issue in PPSSPP itself.

 Steps to reproduce problem, either use right analog patch and reduce it;s deadzone to very small value or any game with the branch linked above,, threshold set to low value (ie 0.5) and mouse axis mapped to anything which is easily observable like camera movement. Possibly could also be the case with standard gamepad when setting deadzone to very small value, but I moved and not sure where my gamepads are so I currently can't test that;p. 

 In case it's platform specific I'm using windows 10 x64.

### PR DESCRIPTION
**Pull request by LunaMoo**
Fixes #11226 at least for the mouse, not sure if similar code is used for gamepad sticks.

 Also reduces threshold when mouse control is used to stop people from complaining that simple remapping 3rd party tools works better than PPSSPP mouse control even after tweaking it's sensitivity/smoothing when mapping mouse axis to psp buttons.

### CODE REVIEW

File: UI/EmuScreen.cpp [hunk 1]
```diff
@@ -884,9 +884,9 @@ void EmuScreen::processAxis(const AxisInput &axis, int direction) {
 	KeyMap::AxisToPspButton(axis.deviceId, axis.axisId, -direction, &resultsOpposite);
 
 	int axisState = 0;
-	if ((direction == 1 && axis.value >= AXIS_BIND_THRESHOLD)) {
+	if (direction == 1 && (axis.value >= AXIS_BIND_THRESHOLD || g_Config.bMouseControl && axis.value >= 0.01)) {
```
Comment (unknownbrackets) [inline UI/EmuScreen.cpp]: Although the parenthesis aren't technically needed here, people tend to misread statements that have mixed `||` and `&&` at the same level.  Normally, extra parenthesis would be best here.

But I'd suggest instead:
```c++
int axisState 0;
float threshold = g_Config.bMouseControl ? 0.01 : AXIS_BIND_THRESHOLD;
if (direction == 1 && axis.value >= threshold) {
```
(or perhaps even a `AXIS_BIND_TRESHOLD_MOUSE`.)

That should be the easiest to read and possibly more optimal anyway.

-[Unknown]

**Review by unknownbrackets — CHANGES_REQUESTED** [review]

File: UI/EmuScreen.cpp (hunk 1 above)
Comment (LunaMoo) [reply UI/EmuScreen.cpp]: Done :3

**Review by unknownbrackets — APPROVED** [review]
Looks okay to me.  I wonder if we ought to be checking `axis.deviceId` too...

-[Unknown]

**Comment by LunaMoo** [comment]
Good idea, I'll just replace the mouse control check for DEVICE_ID_MOUSE check, no need to check for both.
