### PR TITLE
Post-processing: Fix using limited UV ranges when there's a single upscaling filter in the chain.

### LINKED ISSUE #17499: Using a Post processing filter will make the image to stop stretching to the max of the monitor
### Game or games this happens in

ULUS-10005-Darkstalkers Chronicle (usa)

### What area of the game

Anywhere in the game. It happened with other games. This seems to be emulator related.

### What happens

When changing the postprocessing filter the image will stop stretching to the extent of the monitor.

I have tested wtih xbr and other filters and had the same results.

### What should happen

The screen should stretch to fit. Clicking reset does not help. Resizing manually leaves black bars and possibly unevenness.

I also tested on ppsspp core on Retroarch. The result is the same, altough it resizes better (still leaving black bars).

### GE frame capture

_No response_

### Platform

Android

### Mobile phone model or graphics card

nvidia 3080 ti, Windows 11

### PPSSPP version affected

ppsspp-v1.15.4-50-g12106ceb7-windows-amd64

### Last working version

_No response_

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
Can't force the final blit to use the full range if it's the only blit, and that blit needs to use the subrange.

Fixes #17499

Additionally, added checking for post shader changes to softgpu, fixing #17511.

### CODE REVIEW

**Review by unknownbrackets — APPROVED** [review]

File: GPU/Software/SoftGpu.cpp [hunk 1]
```diff
@@ -730,7 +730,18 @@ void SoftGPU::NotifyDisplayResized() {
...
-void SoftGPU::NotifyConfigChanged() {}
+void SoftGPU::NotifyConfigChanged() {
+	configChanged_ = true;
+}
+
+void SoftGPU::CheckConfigChanged() {
+	if (configChanged_) {
+		drawEngineCommon_->NotifyConfigChanged();
+		BuildReportingInfo();
+		presentation_->UpdatePostShader();
```
Comment (unknownbrackets) [inline GPU/Software/SoftGpu.cpp:741]: Should `GPUCommon::CheckConfigChanged()` be moved to GPUCommonHW?  Also, apparently this is crashing from headless now.

-[Unknown]

Comment (hrydgard) [reply GPU/Software/SoftGpu.cpp:741]: Yeah, that might be a good idea.
