### PR TITLE
Try to support Qt keyboard input directly. Fixes #11653

### LINKED ISSUE #11653: Trying to change nickname crashes on Mac?
### What happens?
When clicked "change nickname" the application crashes.

### What *should* happen?
A prompt asking for the new nickname should appear.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
MacBook Air 2017 model, macOS 10.14, v1.7.1-250-ge4b887cc4

[Here's the crash report (generated by MacOS)](https://pastebin.com/cLp2wcRj)

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #11653 by avoiding the native dialog which can't be spawned from the main thread.

### CODE REVIEW

File: UI/GameSettingsScreen.cpp [hunk 1]
```diff
@@ -801,13 +801,14 @@ void GameSettingsScreen::CreateViews() {
 	systemSettings->Add(new PopupMultiChoice(&g_Config.iPSPModel, sy->T("PSP Model"), models, 0, ARRAY_SIZE(models), sy->GetName(), screenManager()))->SetEnabled(!PSP_IsInited());
 	// TODO: Come up with a way to display a keyboard for mobile users,
 	// so until then, this is Windows/Desktop only.
-#if !defined(MOBILE_DEVICE) && !defined(USING_QT_UI)  // TODO: Add all platforms where KEY_CHAR support is added
+#if !defined(MOBILE_DEVICE)  // TODO: Add all platforms where KEY_CHAR support is added
 	systemSettings->Add(new PopupTextInputChoice(&g_Config.sNickName, sy->T("Change Nickname"), "", 32, screenManager()));
-#elif defined(USING_QT_UI)
-	systemSettings->Add(new Choice(sy->T("Change Nickname")))->OnClick.Handle(this, &GameSettingsScreen::OnChangeNickname);
+// #elif defined(USING_QT_UI)
+// systemSettings->Add(new Choice(sy->T("Change Nickname")))->OnClick.Handle(this, &GameSettingsScreen::OnChangeNickname);
```
Comment (unknownbrackets) [inline UI/GameSettingsScreen.cpp]: We should just delete rather than leaving in commented code, git remembers forever after all.

-[Unknown]

File: Qt/QtMain.cpp [hunk 2]
```diff
@@ -354,7 +355,30 @@ bool MainUI::event(QEvent *e)
         NativeKey(KeyInput(DEVICE_ID_MOUSE, ((QWheelEvent*)e)->delta()<0 ? NKCODE_EXT_MOUSEWHEEL_DOWN : NKCODE_EXT_MOUSEWHEEL_UP, KEY_DOWN));
         break;
     case QEvent::KeyPress:
-        NativeKey(KeyInput(DEVICE_ID_KEYBOARD, KeyMapRawQttoNative.find(((QKeyEvent*)e)->key())->second, KEY_DOWN));
+				{
+					auto qtKeycode = ((QKeyEvent*)e)->key();
+					int nativeKeycode = KeyMapRawQttoNative.find(qtKeycode)->second;
```
Comment (unknownbrackets) [inline Qt/QtMain.cpp]: Hm, another tab/space battleground.

I realize this was here before, but I wonder now: is `KeyMapRawQttoNative` guaranteed to have all keys in it?

-[Unknown]

File: Qt/QtMain.cpp [hunk 3]
```diff
@@ -354,7 +355,30 @@ bool MainUI::event(QEvent *e)
...
+					NativeKey(KeyInput(DEVICE_ID_KEYBOARD, nativeKeycode, KEY_DOWN));
+					// Also get the unicode value.
+					QString text = ((QKeyEvent*)e)->text();
+					std::string str = text.toStdString();
+
+					// Now, we don't want CHAR events for non-printable characters. Not quite sure how we'll best
+					// do that, but here's one attempt....
```
Comment (unknownbrackets) [inline Qt/QtMain.cpp]: Hopefully `str.size()` is false in most non-printable cases...

-[Unknown]

**Review by unknownbrackets — CHANGES_REQUESTED** [review]
Just the commented code, not really concerned about the spaces or unchecked map lookup...

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]
