### PR TITLE
In D3D11, force block compressed textures to have dimensions divisible by 4

### LINKED ISSUE #17745: KTX2: Crash in D3D11
Reported by VeryMelon on discord:

It work well with OpenGL & Vulkan & D3D9 but when using D3D11 is got crash.

KTX2 texture pack.
https://forums.ppsspp.org/showthread.php?tid=29011

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/12104956/ppsspplog.zip)

Still crash in latest git build v1.15.4-571-g16ee5a50c.

### PR DESCRIPTION
**Pull request by hrydgard**
This of course applies to texture replacement only.

Fixes #17745 (crash when loading certain texture packs in D3D11)

This is an old unfortunate limitation. Only applies to the top mip level, which makes it obvious that it's kinda unnecessary for the hardware and indeed, Vulkan and OpenGL don't have this limitation.

### CODE REVIEW

File: GPU/Common/TextureReplacer.cpp [hunk 1]
```diff
@@ -337,6 +337,9 @@ bool TextureReplacer::LoadIniValues(IniFile &ini, VFSBackend *dir, bool isOverri
 		}
 	}
 
+	auto gr = GetI18NCategory(I18NCat::GRAPHICS);
+
+	g_OSD.Show(OSDType::MESSAGE_SUCCESS, gr->T("Texture replacement pack activated"));
```
Comment (unknownbrackets) [inline GPU/Common/TextureReplacer.cpp:342]: I forget if this can cause duplicates.  It should be at the end of LoadIni(), since LoadIniValues() can be called multiple times for region overrides.

-[Unknown]
