### PR TITLE
Apply integer math narrowing before VFPU sin/cos

### LINKED ISSUE #12900: ULJS00218 - Hitman Reborn Battle Arena 2 - Player 2 side broken/reversed/broken kick animation
What happens?

In-Game/Fights, particle effects and physics only applying correctly on Player 1 side during fights. On Player 2 side, properties operate as if they are being performed from P1 side. This leads to reversed effects and physics being applied to everything from P2 side. This effectively makes the game unstable/unplayable, since only one player side functions correctly.

What *should* happen?

Here is the direct comparison with the same variables on both hardware and emulation.
https://youtu.be/q1YjrLXTq7c

What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues: 

This was most recently tested with the UMD directly, to ensure there wasn't an issue with the source file being tested.

Win10 / Android (unknown config for android, was tested on two devices in the past and not working)
PPSSPP v1.9.3
Direct3D11/9, OpenGL, Vulkan
Nvidia 2080 Max-Q and Nvidia 970m tested with current build. Many other configs have been tested with previous builds over multiple years.

### PR DESCRIPTION
**Pull request by unknownbrackets**
There's a speed penalty for this but it's not that significant (about 30% of the sin/cos instruction time, looks like.)

This seems to do a better job of narrowing than fmod/fmodf and gives results that match the PSP much better.  It also handles some NAN/INF/zero cases carefully.  I had to special case +1/-1 on cosine though, to make sure it's properly calculated.

Could use some help testing if this has negative effects.  I don't have Cho Aniki Zero (@sum2012), Hajime no Ippo (@Saramagrean), or Hitman Reborn (@somepunkid).  I'm hoping all three games still work with this.  You can test by going to the Checks tab of this pull request and downloading a build from the Artifacts button.

FF3 does still work fine from my tests.  It does not help Ridge Racer of course.

If it works well, I'll probably remove the old single float code entirely.

I might still try to figure out more exact calculation (still suspect it uses CORDIC from the vrot instruction), but it's much closer with this change.

Fixes #12900.

-[Unknown]

### CODE REVIEW

File: Core/MIPS/MIPSVFPUUtils.cpp [hunk 1]
```diff
@@ -946,34 +936,182 @@ void vfpu_sincos_single(float angle, float &sine, float &cosine) {
 	}
 }
 
-float vfpu_sin_double(float angle) {
-	return (float)sin((double)angle * M_PI_2);
+float vfpu_sin_mod2(float a) {
```
Comment (hrydgard) [inline Core/MIPS/MIPSVFPUUtils.cpp:939]: wouldn't mod4 be a more accurate name?

File: Core/MIPS/MIPSVFPUUtils.cpp [hunk 2]
```diff
@@ -946,34 +936,182 @@ void vfpu_sincos_single(float angle, float &sine, float &cosine) {
...
+	if (k > 0x80) {
+		const uint8_t over = k & 0x1F;
+		mantissa = (mantissa << over) & 0x00FFFFFF;
+		k = 0x80;
+	}
+	// This subtracts off the 2.  If we do, flip sign to inverse the wave.
+	if (k == 0x80 && mantissa >= (1 << 23)) {
+		val.i ^= 0x80000000;
+		mantissa -= 1 << 23;
+	}
```
Comment (hrydgard) [inline Core/MIPS/MIPSVFPUUtils.cpp:965]: Couldn't we just add a phase shift here for one of [sin, cos], and share the rest of the code between them?

**Review by hrydgard — COMMENTED** [review]
Just nits, feel free to address or skip.

**Comment by somepunkid** [comment]
Tested Reborn BA2. Tested multiple characters and multiplayer. Tested broken kick animation from https://github.com/hrydgard/ppsspp/issues/12900

It is DONE! The game is 100%. Everything is working. Did some direct tests with hardware as well just to be sure but yes, this seems great!

**Comment by hrydgard** [comment]
Awesome, thanks for testing!

**Comment by sum2012** [comment]
>
> I lost my password , "Verify your account" to send new password to email
> did not work

I tried 2 times to get "number 14" from 9 pictures of 15 times.... but
still fail

>

**Comment by hrydgard** [comment]
@sum2012 did you post in the wrong thread? That doesn't seem relevant here.

**Comment by LunaMoo** [comment]
Check the mail icon near his nick:
github


 Seems he's having some captcha problems when resetting password, through with the email reply I guess he can reply/contribute even without logging on the site.

**Comment by Saramagrean** [comment]
Hajime no Ippo work fine with this.

File: Core/MIPS/MIPSVFPUUtils.cpp (hunk 2 above)
Comment (unknownbrackets) [reply Core/MIPS/MIPSVFPUUtils.cpp:965]: I almost had it shared, and still waffling on it.  But the NAN handling is a bit different and I was worried about the -0 cases making it messy.

-[Unknown]

Comment (unknownbrackets) [reply Core/MIPS/MIPSVFPUUtils.cpp:965]: We definitely can swap sin/cos and negative though (and have to for CORDIC), I was just trying to minimize perf impact here.

-[Unknown]

File: Core/MIPS/MIPSVFPUUtils.cpp (hunk 1 above)
Comment (unknownbrackets) [reply Core/MIPS/MIPSVFPUUtils.cpp:939]: First step is mod by 4 (since it has a repeating pattern by 4), but then it mods by 2 right below that (which may negate the result or negate the input.)  Ultimately, as in the other note, I may want to mod by 1 and swap sin/cos (which I was already doing in my CORDIC test code), but that part adds unnecessary extra instructions without much accuracy benefit at this point.

-[Unknown]

**Comment by hrydgard** [comment]
Alright. Let's merge this and see how it goes!

**Comment by unknownbrackets** [comment]
I'm starting to think the raspberry pi has a completely broken sin() / cos() implementation or something, because there are strange reports of crazy brokenness that only seem to be coming from raspberry pi users and seem new since this was merged.

Might try forcing rpi to use sinf/cosf/sincosf, but haven't confirmed this is the problem...

-[Unknown]

**Comment by hrydgard** [comment]
Huh, sounds strange :( 

We could also maybe just replace sin/cos entirely with an cubic-interpolated lookup table after range reduction, we should be able to get close enough...

**Comment by unknownbrackets** [comment]
Seems like it is not that, per #14456...

-[Unknown]
