### PR TITLE
Workaround for sin/cos issue in GTA on Mac (and maybe others)

### LINKED ISSUE #15149: GTA : LCS - All character and vehicle models are invisible on M1 Mac
### Game or games this happens in

ULUS-10041 GTA:Liberty City Stories

### What area of the game / PPSSPP

One minute into the game when one watches the intro, it becomes clear that all characters and vehicles are invisible most of the time, and only partly "flash" into existence for very brief periods.
Broken Models

I also tested OpenEmu which uses 1.10.3. And that version is not affected and shows all characters and vehicles correctly. But in OpenEmu one cannot even access any of PPSSPP's settings, so using that "frontend" is rather pointless.

Also you guys do not provide 1.10.3 readily compiled for M1.
Brew provides PPSSPP 1.10.3, too, but crashes during installation of PPSSPP. See [#72631].(https://github.com/Homebrew/homebrew-core/issues/72631)
And RetroArch for M1 is missing the PPSSPP core entirely.

So the only way to play this game is OpenEmu, which is not configurable and uses 1x-PSP-resolution -.-

### What should happen

Characters and vehicles should be clearly visible, when they are on screen.

### Logs

_No response_

### Platform

macOS

### Mobile phone model or graphics card

M1

### PPSSPP version affected

1.12.3

### Last working version

1.10.3

### Graphics backend (3D API)

OpenGL / GLES and Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #15149 

Turns out the game is hyper sensitive to the shape of the sin curve, so while we tried making its precision a bit more accurate to the hardware by reducing the precision, this resulted in something going slightly over one threshold or another due to the sin curve shape not being bit identical on all platforms. This just works around it by lowering the threshold for when we flush the angle to zero.

### CODE REVIEW

File: Core/MIPS/MIPSVFPUUtils.cpp [hunk 1]
```diff
@@ -29,6 +29,13 @@
 #define V(i)   (currentMIPS->v[voffset[i]])
 #define VI(i)  (currentMIPS->vi[voffset[i]])
 
+// Flushes the angle to 0 if exponent smaller than this in vfpu_sin/vfpu_cos/vfpu_sincos.
+// Was measured to be around 0x68, but GTA on Mac is somehow super sensitive
```
Comment (unknownbrackets) [inline Core/MIPS/MIPSVFPUUtils.cpp:33]: Well, it's not "about zero", the PSP doesn't return any non-zero value with an exponent below 0x68 (based on an exhaustive analysis of all possible input values that don't wrap.)  I'm not arguing with this change, though, as clearly macOS/iOS are returning values with lower exponents than that for values the PSP returns an exponent >= 0x68.

-[Unknown]
