### PR TITLE
Remove the old style multithreading

### LINKED ISSUE #5127: Final Fantasy Type 0 - Character artifacts after death (Multi-threading issue)
So far I narrowed it down to a multi-threading option, after turning it off the problem is still existing but it repairs itself after few slashes with weapon, when it is ON, the problem is permanent.

Any possible fixes for that issue in the future ? The translation patch is coming :dancers: so time is of the essence !

Best Regards !

### LINKED ISSUE #5632: Tokyo Mono Harashi wrong FPS in singlethread mode
singlethread

multithread

debuglog
singlethread
https://gist.github.com/daniel229/9482775

multithread
https://gist.github.com/daniel229/9482781

### LINKED ISSUE #5989: Tactics Ogre flickering and crashes with Multithreading on
Get 3 different stack traces in vs 2013

debug log
https://gist.github.com/daniel229/11398097

### LINKED ISSUE #6096: Multithreaded option enabled crashes ppsspp
On Windows XP and Android with Multithreaded option enabled, games keep on crashing - tested with Assassin's Creed, Justice Hero League and 3rd birthday (this last one only on WinXP) on ppsspp 9.8.691 (XP) and 9.8.685 (Android):
On Android: games "close to Android desktop" without an error message
On Windows XP: games crash with a memory could not be read error
As soon as possible I'll try to find the revision that caused the issue

Assassin's Creed - WinXP

image

### LINKED ISSUE #6331: FF Crisis Core - Crash at the beginning with Fast Memory and Multithreaded On
Crisis Core crashes at the beginning with Fast Memory On since v0.9.8-558-g9164e70.

The game crashes at the following scene as soon as the damage number is supposed to appear:

ulus10336_00003

### LINKED ISSUE #6441: Project Diva Extend: Multithreading eats frames
For some reason When Multithreaded is on and force real clock sync is off the game frames are being eaten.
The speed is same but frames drop to 20 and lower.(In menu,in game, almost everywhere)
Revision i'm using 0.9.8-1429-96916ffb

EDIT: And game in general got worse, the timing is way off. Gonna post a video later.

EDIT: As the song goes on the input is worse and worse

https://www.youtube.com/watch?v=tIU45f4MENY&feature=youtu.be

Its like the notes go faster than they should.

### LINKED ISSUE #6612: FPS at half speed when Multithread is enable
Today I detect while playing Virtua Tennis: World Tour, if multithread option is enable game goes at exactly half speed when the match is ready:

Multithread disable:
image

Multithread enable:
image

### LINKED ISSUE #6874: Recent development version, open multithreading, all game slows down
GEB_AE, SAO, Toukiden ...... slows down！The 0.98 version of the game, when open multithreaded significantly enhance the speed.
My English is not good, do not know if you can understand it.

### LINKED ISSUE #7494: Final Fantasy Type 0 crash in-game
Load save status
https://drive.google.com/file/d/0B3OaSdeV0L8kaXpEUmRBYzdsOE0/view?usp=sharing

Request to investigate the story of a detonation device, immediately after the investigation calculus animation, and then raise crash

v1.0-77-g1d7b0ae debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcjgzSFA3MTlacG8/view?usp=sharing

No useful crash strace (I have turned off fast memory)

Seem this problem
56:12:908 user_main    D[G3D]: GPUCommon.cpp:690 Okay, starting DL execution at 0907c66c - stall = 0907c988
56:12:908 user_main    D[G3D]: Common\VertexDecoderCommon.cpp:856 VTYPE with morph used: THRU=0 TC=3 COL=1 POS=0 NRM=1 WT=3 NW=5 IDX=3 MC=4
56:12:908 user_main    E[G3D]: Common\VertexDecoderCommon.cpp:1009 Vertices without position found
56:12:908 user_main    D[G3D]: Common\VertexDecoderCommon.cpp:1040 SVT : size = 32, aligned to biggest 4
56:12:908 user_main    W[G3D]: Common\VertexDecoderCommon.cpp:1046 Vertex decoder JIT failed! fmt = 000f1e27

### LINKED ISSUE #7774: Problem with 'Multithreaded' feature + workaround
I run PPSSPP on my Galaxy S2 (I9100).

Multithreaded option doesn't have any effect if it's enabled before you start the game.

The only way to get it working:
1. disable multithreaded,
2. start the game
3. then enable multithreaded.

So enable it only after you started the game. You have to do this everytime when you want to play (disable, start game, enable).
The only work-around is to create a PPSSPP save file after you got it working.

For example you can test this bug with Colin McRae Rally 2005, because the Multithreaded feature makes noticeable difference with this game (on my Galaxy S2 it gives about 20% improvement in speed, combined with my other settings).

### LINKED ISSUE #7877: Blazblue Continuum Shift 2 (ULUS10579) black screen in-game with buffered rendering.
In battle screen (for sample, tutorial) if I set rendering to Buffered, I got black screen with 60 FPS (music still playing, game still running). If I set it to "Skip buffer effects", I got proper game screen back.

### LINKED ISSUE #8895: Kirin 950 multthread issue
My freind said that PPSSPP only use Kirin' s two weak core in multthread.
Other CPU such as Qualcomm 801 ,MediaTek 6592 , MediaTek  6752 are stronger in multthread.
Any possible to solve it ? Thanks

### LINKED ISSUE #9712: Multithreading issues
When i'm playing Persona 3 , when i run at single core mode and enable multithreading , it's improvement speed , but when i start game after enable multithreading , it slower speed , and disable multithread ( single core mode ) it normal

### PR DESCRIPTION
**Pull request by hrydgard**
Running the display list interpreter asynchronously is too dangerous, as has been discussed, and at least for Vulkan we now have a much better alternative, which will soon be turned on by default.

The old stuff does work for some games and there might be some people out there relying on it, but the benefit was never huge and the cost in code complexity and synchronization wasn't worth it.

So bye bye, "Multithreading (experimental)". Vulkan with the new multithreading outperforms the other backends so much it's not even funny sometimes.

Following fixes are by making them obsolete. The new multithreading implementation for Vulkan and the planned one for GL will not have these issues.

Fixes #9712
Fixes #8895 
Fixes #7877
Fixes #7774
Fixes #7494
Fixes #6874
Fixes #6612
Fixes #6441
Fixes #6331
Fixes #6096
Fixes #5989
Fixes #5632
Fixes #5127

### CODE REVIEW

File: Core/System.cpp [hunk 1]
```diff
@@ -392,10 +392,10 @@ void System_Wake() {
 // Ugly!
 static bool pspIsInited = false;
 static bool pspIsIniting = false;
-static bool pspIsQuiting = false;
+static bool pspIsQuitting = false;
```
Comment (unknownbrackets) [inline Core/System.cpp]: Derp, this is my typo.  Thanks.

-[Unknown]

File: Core/HLE/sceGe.cpp [hunk 2]
```diff
@@ -193,13 +193,12 @@ static void __GeExecuteInterrupt(u64 userdata, int cyclesLate) {
 	__TriggerInterrupt(PSP_INTR_IMMEDIATE, PSP_GE_INTR, PSP_INTR_SUB_NONE);
 }
 
+// Should we still do this?
```
Comment (unknownbrackets) [inline Core/HLE/sceGe.cpp]: No - even if we wanted to try to sync CPU cycles with GPU cycles, I think we'd need to do it very differently.  I think `__GeCheckCycles` can be removed entirely.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]
Cathartic.  Thanks.

-[Unknown]

**Comment by unknownbrackets** [comment]
We can also move `CoreTiming::ScheduleEvent_Threadsafe` to `CoreTiming::ScheduleEvent` (same with `UnscheduleThreadsafeEvent`) in sceGe.cpp, and remove the nearby comments in sceGe.  I can PR later though.

-[Unknown]

**Comment by hrydgard** [comment]
I'll just go ahead and do it. Gonna do a little more testing too later before I merge this.

There are, by the way, no other active users of threadsafe events anywhere, except for some commented-out code in adhoc. But I think I'll keep around the functions for now.

**Comment by zminhquanz** [comment]
How about for the old device ? what are you doing with this for without multithreading

**Comment by unknownbrackets** [comment]
We may eventually try to apply the Vulkan threading approach to GLES as well.

The current multithreading is very buggy, and causes a lot of glitches and crashes.  Worse, it depends on GPU/driver speed/other factors for what bugs will happen, meaning it can seem to work for some or in some scenes of the game, and then break for unexpected reasons elsewhere.

-[Unknown]

**Comment by NotUnknownbrackets** [comment]
> may

**Comment by LunaMoo** [comment]
Removing MT will fix all of [those](https://github.com/hrydgard/ppsspp/issues?utf8=%E2%9C%93&q=label%3AMultithreading%20is%3Aopen%20is%3Aissue) and lots more unreported cases where people keep it enabled ignoring the warnings or had it activated all the time from before the warnings were added and breaking their experience.
 Few games being able to work faster on some outdated device or accidently improving other issues is not worth the amount of hardware dependant BS this option currently causes.

 Seeing some trolling/account created for the sake of being against this PR just hours after it was opened, I think it'll be healthy to limit the discussion here. Removal of existing options in any emulator has always people against it, but in the long run, it's necessary.
