### PR TITLE
CWC improvements/fixes

### LINKED ISSUE #7375: Cheat engine issues and "locking interval"
Got this in a PM on the forum. Let's see if we can break this down into actual fixes.

"
We need code locking interval option for the codes part.

This option is A MUST HAVE for the Cheats menu.
It will allow us to change code locking interval "cheat hz" so games can not change values by themselves once a code is activated.

Currently PPSSPP Cheat's engine doesn't freeze the codes the way it should be and the game changes values itself even if a code is activated thus leading to crashes/not working codes.

Please ADD this function.
Add the ability for users to set cheat hx in Micro Seconds (Code Locking Interval) 

Second:

JIT causes freezes when going to cheats menu. For example just when JIT is on Going to Cheats menu and going back to game causes a freeze with or without enabling/disabling any of the codes.

Third:

Soul Calibur Broken Destiny has broken texture colors for the projectiles. The projectiles color for most of the attacks is WHITE which isn't what it should be. You can see a video from psp and see one on PPSSPP to ensure what I am telling.

But my main problems are the first two.
I need a code locking interval option for the cheats. This will be a great service and huge upgrade to the emu. Thank you. Many people ask for this and I personally want this as I am a game mods dev too. 

Thank you in advance.
"

### LINKED ISSUE #8023: Expand #7997 (save states files naming) to cheat files
I know this came at a really bad time, right after release. To be honest I didn't expect it to be today.
But without this #7997 looks like only half done and is a missed opportunity.

### LINKED ISSUE #8448: Trying to import cheats from cheat.db while playing a homebrew game causes the emulator to crash
If while playing a homebrew game (Cave Story, Trig Wars), the user attempts to import cheats from cheat.db, the emulator will crash with a Unhandled Exception.

The emulator also makes a ini file for the homebrew in the cheats folder but doesnt name it anything, simply leaving it at .ini
capture

1, Launch homebrew
2. Open menu
3. Try to import cheat from db, emulator will crash
capture

### LINKED ISSUE #8658: Request: Add "Cheat" option to games before launching it
Found out that there's no way to disable cheats before launching games and its kinda annoying to launch the game, hit the option menu, get inside the Cheat menu and disable it.
There's probably a way to add the cheat menu for all games before launching them.
Eg. Right click on the game> Cheats
Mockup concept

### PR DESCRIPTION
**Pull request by LunaMoo**
This solves #8658 althrough I would be lazy to do it just because of the argument mentioned there about someone being lazy to restart emulation when it's required by cheat, my own argument for adding it is for cases where broken cheats crash PPSSPP on boot which might suck on non windows platforms currently.

 It additionally fixes a small problem where first line was removed from newly created files, it could remove first cheat if someone opened automatically created file and added cheats without _S/_G lines that we usually add as PSP legacy, but not actually use them.

 Also invalidates JIT for reading values via 0xE/0xD multi-line skip codes, in some cases where code is moved around/loaded in modules those codes can't read original values otherwise. I don't think that's particulary common issue since people rarely ever used those cheats that way on psp, I do it all the time since they're great to stop long scripts from being written constantly as well as for safety checks.

 Saying so I can't really find any more issues with CWC, people will continue to have problems with PSP cheats where address differs and we can't do much about it, so I guess #7375 could also be closed.

Edit: sorry for pushing it like few times in a row;p I'm quite literally on drugs(well eye drops count as drugs I guess;p) and my vision is quite blurry. Should be fine now.
## 

Fixes #8448, fixes #8658, fixes #8023.  Fixes #7375 (remaining jit invalidations.)

### CODE REVIEW

File: UI/CwCheatScreen.cpp [hunk 1]
```diff
@@ -40,10 +41,69 @@ static bool enableAll = false;
 static std::vector<std::string> cheatList;
 static CWCheatEngine *cheatEngine2;
 static std::deque<bool> bEnableCheat;
+std::string gamePath_;
```
Comment (unknownbrackets) [inline UI/CwCheatScreen.cpp]: This should be a class member of `CwCheatScreen` probably, or otherwise it should be `static`.

For non-class members, `static` means that other cpp files can't see it (e.g. if two files had `std::string gamePath_` in them without `static`, they would conflict, or be the same variable.)

-[Unknown]

File: UI/CwCheatScreen.cpp [hunk 2]
```diff
@@ -40,10 +41,69 @@ static bool enableAll = false;
...
+	std::string discID;
+	if (info && info->paramSFOLoaded) {
+		
+		discID = info->paramSFO.GetValueString("DISC_ID");
+	}
+
+	activeCheatFile = GetSysDirectory(DIRECTORY_CHEATS) + discID + ".ini";
+	File::CreateFullPath(GetSysDirectory(DIRECTORY_CHEATS));
+
+	if (!File::Exists(activeCheatFile)) {
```
Comment (unknownbrackets) [inline UI/CwCheatScreen.cpp]: Hmm, instead of abusing a global `activeCheatFile`, can we make `GetCodesList` take an optional path argument?  I'm thinking:

```c++
class CWCheatEngine ... {
    std::vector<std::string> GetCodesList(std::string file = "");
};

//

std::vector<std::string> CWCheatEngine::GetCodesList(std::string file) {
    if (file.empty()) {
        file = activeCheatFile;
    }
...
```

That way we don't need to duplicate this code, I think?

-[Unknown]

Comment (LunaMoo) [inline UI/CwCheatScreen.cpp]: Will that work for headless? I tried to avoid duplicating this code, but I couldn't make it without making build dependant on UI. Will look at it again.

Comment (unknownbrackets) [inline UI/CwCheatScreen.cpp]: Yes, since UI would be passing more params into Core, rather than Core trying to get things from UI (which is what you want to avoid.)

-[Unknown]

Comment (LunaMoo) [inline UI/CwCheatScreen.cpp]: Thanks, I was doing it completely wrong earlier:3.

**Comment by LunaMoo** [comment]
Cool, since with this cheat file creation is handled better passing info from UI - #8448 was also fixed.

 The only thing it still generates nameless ini file anyway since we generate them on boot as well, I'll just disable it for homebrew. Those files are created when opening cheat menu anyway.

**Comment by LunaMoo** [comment]
I think everything is done here now, or at least I hope so, to sum it up - this now fixes:
 #8023 - Expand (save states files naming) to cheat files
 #8448 - Trying to import cheats from cheat.db while playing a homebrew game causes the emulator to crash
 #8658 - Request: Add "Cheat" option to games before launching it

 Potentially
 #7375 - Cheat engine issues and "locking interval"
 could also be closed since it's far too generic, we already have the feature it requested for a while, from my experience used cheats for a long time without issues until noticing 0xE/0xD code types also need invalidate JIT which this PR deals with.

 Cheat related issues which people report are commonly caused by either:
 - memory differences between ppsspp vs psp,
 - not cwcheats or at least not following it's original syntax, CWC is easily the most popular and best documented one, unfortunately not the only format in existence.

**Comment by LunaMoo** [comment]
Blah, I thought we generate ID's using filename for homebrew, but we do use filename, just for some reason homebrew like to display a legit ID, except all of them use same one? :C
 Tried "Cave Story" and "Chuckie Egg" both UCJS10041, and actually not using that for anything else but to show on gameScreen? Any ideas?

**Comment by hrydgard** [comment]
I don't know of any reliable way to generate IDs for homebrew, unfortunately. Hashing the executable might come close but the filenames won't exactly be legible.

If you want to do something about it before merge, that's fine - I'm happy to merge this as is, too, looks good.

**Comment by LunaMoo** [comment]
I'll try to set homebrew through filename as well, just need to test how it works.

**Comment by LunaMoo** [comment]
filenames
Seems to work fine now, also checks for extensions assuming commercial games can only be iso/cso/pbp to avoid use of that incorrect ID some homebrew had.

File: Core/CwCheat.cpp [hunk 3]
```diff
@@ -263,7 +269,10 @@ inline void trim2(std::string& str) {
 	else str.erase(str.begin(), str.end());
 }
 
-std::vector<std::string> CWCheatEngine::GetCodesList() { //Reads the entire cheat list from the appropriate .ini.
+std::vector<std::string> CWCheatEngine::GetCodesList(std::string file) { //Reads the entire cheat list from the appropriate .ini.
+	if (file.empty()) {
+		file = activeCheatFile;
```
Comment (unknownbrackets) [inline Core/CwCheat.cpp]: Well, I suppose this isn't doing anything since `activeCheatFile` is being set otherwise.

-[Unknown]

**Comment by unknownbrackets** [comment]
Yeah, looks okay to me.  I think we have similar logic for savestates.

-[Unknown]

**Comment by LunaMoo** [comment]
Oh yeah, I ended setting it up during cheat file creation and never used that one;c. Thanks for edit as well, I don't know most of git power.
