### PR TITLE
Fix a bunch of emu features for Homebrew by better identification.

### LINKED ISSUE #9724: Remaining problems with identifying homebrew
Just a list of things that would be nice to handle better in some potentially distant future:
 - per game settings,
 - texture replacement,
 - compatibility settings,
 - normal screenshots.

 Maybe also for cosmetic stuff like:
 - window titlebar,
 - game info screen(replacing the common Loco Roco ID).

 Potentially forgetting about something.

 Kind of wonder if those could be reduced together with savestates and cheats(which handle it separately) into one common function as those features are spread all around:].

### PR DESCRIPTION
**Pull request by LunaMoo**
Searched where g_paramSFO.GetValueString("DISC_ID") was used and added FakeID function whenever that returns an empty string or UCJS10041 which is ID that homebrew abuse(it's just a demo of japanese Loco Roco, felt worth giving it a fakeID to fix much more stuff;p) ~ to the following:
- Title,
- TextureReplacement,
- shader cache,
- compatibility,
- decrypted eboot dump,
- screenshots,
- FramebufferManagerCommon(Guessing it's also for compat.ini hacks?),
- per game settings.

 Also for same case changed region to "Homebrew" on game screen.

 No changes:
- reporting(maybe should change?),
- remaster extdata(no sense?).

 I also changed cwcheats and savestates now, it should not be a big deal for cwc since those practically don't exist for homebrew since plugins had same problem and homebrew ofter came with cheats built-in. As for savestates, I added automatic translation which might be removed after some later release like 1.6 which I noted in the code. It only checks homebrew savestate files on boot and renames them from old to new format.
 Doesn't include elf as that's also not worth bothering renaming, many homebrew are simple elf's, but they were all detected as pbp in directory for savestates, since basically EBOOT.PBP in directory = bootable directory and the file has to be named that way for real PSP anyway, so all normal homebrew were given folder name never just "elf":].

 I think everything's working fine, but a review would be nice, it looks big, but there's actually not that much code changed, the biggest part is the generateFakeID function which is pretty simple.

Fixes #9724

Some example ID's this generates based on the following folder names:
- CAVE00992 (cavestory),
- KOSM01172 (Kosmodrones),
- CHUC00975 (ChuckieEgg),
- QUAK00649 (QuakeII),
- WOLF00622 (Wolf_3D),
- FRON00918 (FRONTIER_1337).

### CODE REVIEW

**Comment by hrydgard** [comment]
std::to_string is unfortunately not working on Android so you'll have to use StringFromFormat() from Common/StringUtils.h instead.

**Comment by LunaMoo** [comment]
Thanks:3, android build fixed.

**Comment by hrydgard** [comment]
Thanks, will merge once 1.4.2 is out.

File: UI/GameInfoCache.cpp [hunk 1]
```diff
@@ -405,6 +405,10 @@ class GameInfoWorkItem : public PrioritizedWorkQueueItem {
 					std::lock_guard<std::mutex> lock(info_->lock);
 					info_->paramSFO.ReadSFO(sfoData);
 					info_->ParseParamSFO();
+					if (info_->id.empty() || info_->id == "UCJS10041") {
+						info_->id = g_paramSFO.generateFakeID(gamePath_);
```
Comment (unknownbrackets) [inline UI/GameInfoCache.cpp]: Some places use the `id_version`.  Does this need to update that too?

-[Unknown]

File: Core/PSPLoaders.cpp [hunk 2]
```diff
@@ -322,5 +323,14 @@ bool Load_PSP_ELF_PBP(FileLoader *fileLoader, std::string *error_string) {
 	pspFileSystem.Mount("umd0:", fs);
 
 	std::string finalName = ms_path + file + extension;
+
+	std::string homebrewName = PSP_CoreParameter().fileToStart;
```
Comment (unknownbrackets) [inline Core/PSPLoaders.cpp]: What if this is a PBP, like an official demo or PSN game?  It seems like this would still run?

-[Unknown]

File: Core/PSPLoaders.cpp [hunk 3]
```diff
@@ -296,6 +296,7 @@ bool Load_PSP_ELF_PBP(FileLoader *fileLoader, std::string *error_string) {
 	// Turn the slashes back to the Windows way.
 	path = ReplaceAll(path, "/", "\\");
 #endif
+	char title[1024];
```
Comment (unknownbrackets) [inline Core/PSPLoaders.cpp]: This shouldn't be all the way up here if it's not used until much later.

-[Unknown]

File: Core/ELF/ParamSFO.cpp [hunk 4]
```diff
@@ -276,3 +280,34 @@ void ParamSFOData::ValueData::SetData(const u8* data, int size)
 	u_size = size;
 }
 
+std::string ParamSFOData::generateFakeID(std::string filename)
```
Comment (unknownbrackets) [inline Core/ELF/ParamSFO.cpp]: Convention is for Capital first letters, and new functions to have curly on the same line.

-[Unknown]

File: Core/ELF/ParamSFO.cpp [hunk 5]
```diff
@@ -276,3 +280,34 @@ void ParamSFOData::ValueData::SetData(const u8* data, int size)
...
+	// Generates fake gameID for homebrew based on it's folder name.
+	// Should probably not be a part of ParamSFO, but it'll be called in same places.
+	std::string file = PSP_CoreParameter().fileToStart;
+	if (filename != "")
+		file = filename;
+
+	std::size_t lslash = file.find_last_of("/");
+	file = file.substr(lslash + 1);
+
+	int letter, sumOfAllLetters = 0;
```
Comment (unknownbrackets) [inline Core/ELF/ParamSFO.cpp]: Letter isn't used outside the loop, clearer to define it within the loop.

-[Unknown]

File: Core/ELF/ParamSFO.cpp [hunk 6]
```diff
@@ -276,3 +280,34 @@ void ParamSFOData::ValueData::SetData(const u8* data, int size)
...
+	for (int i = 0; i < file.size(); i++) {
+		letter = file[i];
+		sumOfAllLetters += letter;
+	}
+	
+	size_t j;
```
Comment (unknownbrackets) [inline Core/ELF/ParamSFO.cpp]: Here also, `j` is not used outside.  Although this might be clearer:

```c++
int sumOfAllLetters = 0;
for (char &c : file) {
    c = toupper(c);
    sumOfAllLetters += c;
}
```

-[Unknown]

File: Core/ELF/ParamSFO.cpp [hunk 7]
```diff
@@ -276,3 +280,34 @@ void ParamSFOData::ValueData::SetData(const u8* data, int size)
...
+	for (j = 0; j < file.size(); j++) {
+		file[j] = toupper(file[j]);
+	}
+	if (file.size() < 4) {
+		file += "HOME";
+	}
+	file = file.substr(0, 4);
+
+	std::stringstream s;
+	s << std::setfill('0') << std::setw(5) << StringFromFormat("%i", sumOfAllLetters);
```
Comment (unknownbrackets) [inline Core/ELF/ParamSFO.cpp]: I'm not sure this works, and even if it does, why not just use the format directly?

```c++
std::string fakeID = file + StringFromFormat("%05i", sumOfAllLetters);
```

-[unknown]

**Review by unknownbrackets — CHANGES_REQUESTED** [review]

File: UI/PauseScreen.cpp [hunk 8]
```diff
@@ -321,6 +321,9 @@ void GamePauseScreen::CreateViews() {
 	continueChoice->OnClick.Handle<UIScreen>(this, &UIScreen::OnBack);
 
 	std::string gameId = g_paramSFO.GetValueString("DISC_ID");
+	if (gameId.empty() || gameId == "UCJS10041") {
```
Comment (LunaMoo) [inline UI/PauseScreen.cpp]: UCJS10041 as mentioned at the top of this pr is a real game - demo version of japanese Loco Roco, I think creating fakeID for one demo which doesn't need such treatment to fix a lot of homebrew is worth doing. I also never saw any homebrew with different ID, they either have none at all, or use that one, probably due to use of same tools/sdk's or whatever add's that ID.

 As for do we want it, thinking about it, I think it might not be needed everywhere, maybe even it's only needed in places that are called before running the game. I'll check and remove it from places I find.

File: UI/GameInfoCache.cpp (hunk 1 above)
Comment (LunaMoo) [inline UI/GameInfoCache.cpp]: Any place actually requires it and isn't fine with empty string? There's really nothing to base it on in homebrew, so that would be completely hardcoded and made up number.

File: Core/PSPLoaders.cpp (hunk 3 above)
Comment (LunaMoo) [inline Core/PSPLoaders.cpp]: Ok, I think I started it there and forgot to move it;p.

File: Core/PSPLoaders.cpp (hunk 2 above)
Comment (LunaMoo) [inline Core/PSPLoaders.cpp]: Demos in pbp format doesn't use that code, PBP for homebrew is basically elf + param.sfo + some icons in it's own directory, demo's of commercial games doesn't differ from full games in PBP format and have same structure as iso.

File: Core/ELF/ParamSFO.cpp (hunk 4 above)
Comment (LunaMoo) [inline Core/ELF/ParamSFO.cpp]: Sorry about capital letter, will correct, I knew about curly, but this whole file uses it on newline so I just based it on what I saw.

File: Core/ELF/ParamSFO.cpp (hunk 5 above)
Comment (LunaMoo) [inline Core/ELF/ParamSFO.cpp]: ok;3

File: Core/ELF/ParamSFO.cpp (hunk 7 above)
Comment (LunaMoo) [inline Core/ELF/ParamSFO.cpp]: Yeah I didn't really know how to do that at all before starting:P, neither saw StringFromFormat earlier, I guess that'll be better.

File: Core/ELF/ParamSFO.cpp (hunk 6 above)
Comment (LunaMoo) [inline Core/ELF/ParamSFO.cpp]: I think I will move c = toupper(c); under the sum to keep case sensitive sum, but I like it, much nicer than my ugly code.

**Comment by LunaMoo** [comment]
Cool, the LocoRoco demo ID was only returning in GameInfoCache, so I could remove the check for it from everywhere else where homebrew only returns empty string:].

 Also noticed dumping decrypted eboot doesn't really work either way for homebrew so removed that, not worth fixing since only decrypted homebrew work in ppsspp anyway due to encrypted ones using keys we don't have(or at least that's the common truth:P, never actually checked signed homebrew myself since I know we don't have some other keys).

 Finally, corrected all new functions curly brackets in that file to same line:].

**Comment by Orphis** [comment]
Well, if you switch to libc++, then std::to_string() will be available.

File: UI/PauseScreen.cpp (hunk 8 above)
Comment (unknownbrackets) [inline UI/PauseScreen.cpp]: There are actually a lot of IDs used by homebrew, including `HBRW00000`.  Some also have no disc ID, but have a version.  I've also sometimes seen wrong game titles or screenshots reported under http://report.ppsspp.org/games, because some homebrew reused a game's ID.

I'm not sure how often it's been English homebrew, though.  Of course, there are also patched games, but that's a separate problem.

Not sure if we do or don't want reporting data for homebrew, though we do currently get some.

-[Unknown]

File: UI/GameInfoCache.cpp (hunk 1 above)
Comment (unknownbrackets) [inline UI/GameInfoCache.cpp]: Not sure, I just mean that if we're changing `id`, maybe we should set `id_version` to match.  Even if it's not used now, it might be in the future.  That's why we have this code for ELFs:

```c++
				std::lock_guard<std::mutex> lock(info_->lock);
				info_->id = "ELF000000";
				info_->id_version = "ELF000000_1.00";
				info_->paramSFOLoaded = true;
```

-[Unknown]

File: Core/PSPLoaders.cpp (hunk 2 above)
Comment (unknownbrackets) [inline Core/PSPLoaders.cpp]: Hmm, okay.  I've always assumed that this format is supported by the PSP because some games were released in this format (even if they stopped doing it after 1.50 or something.)  I mean, otherwise wouldn't they have dropped support for it in 6.61 or w/e just to reduce the things that would run on OFW?

-[Unknown]

File: UI/PauseScreen.cpp (hunk 8 above)
Comment (LunaMoo) [inline UI/PauseScreen.cpp]: Hmmm if they use made up gameID, then they shouldn't have problem with per-game config to begin with and that ID detection is now only a requirement for that one feature, it's unfortunately the most important one considering how bad can some homebrew work.
 I could change ID check to non iso/cso/pbp stored in memstick\PSP\GAME as cheats do now as it works fine in practice, I mean sure someone could throw full games in separate folders inside that place, but meh that would be worst case scenario and even then it would just cause their per-game config to use fake ID without affecting anything else.

 Fun fact ~ I checked that loco roco demo, and it's encrypted by keys we don't have. Guess it's exact reason why popular homebrew which are commonly signed as loco roco also have that problem.:]

File: Core/PSPLoaders.cpp (hunk 2 above)
Comment (LunaMoo) [inline Core/PSPLoaders.cpp]: PBP seems to be just generic container, so it can store just the elf, like eboot.pbp on game disc, or be a disc on it's own, homebrew pbp file structure reminds me of update files pbp :|, maybe it's based on it.

**Comment by LunaMoo** [comment]
Cleaned the history a bit, the only "tradeoff" change here is assumption that bootable folders inside "/PSP/GAME/" are homebrew which might not be the case if someone actually stores a full game or demo with original filename(EBOOT.PBP) stored inside "/PSP/GAME/subfolder/":].
 But that's unlikely and doing it that way avoids ID check for demo, which helps when other homebrew might use different ID's, also at worst if someone would store games that way it wouldn't break anything, it would just generate fakeID for per-game config and for game info screen, so hopefully that's an acceptable solution since homebrew without per game config are really kind of bad.:]

 Also taken care of loose elf in /PSP/GAME/ folder since I noticed homebrew from the store - Trygonometry Wars - fits that case.

**Comment by LunaMoo** [comment]
I checked many full games and demos and noticed they all have APP_VER, probably requirement for PS Store or whatever, on the other hand I couldn't find a single homebrew which uses it thanks to people being lazy, so I changed homebrew detection on that value existence(only for previously troublesome case ~ before running the game), works great soo far.:]

**Comment by hrydgard** [comment]
@Orphis  yes, I've tried that, but you run into other issues. libc++ in the NDK is not considered stable. They're working on it so and by r16 we should be switch, but right now we can't. Try it and you'll see.

**Comment by LunaMoo** [comment]
Oops, I think I messed something with that screenshot as icon;p, locks without screenshots.

File: UI/GameInfoCache.cpp (hunk 1 above)
Comment (LunaMoo) [inline UI/GameInfoCache.cpp]: Forgot to note, but I added the id_version.
 I didn't saw it used anywhere, but it doesn't hurt, I think it's currently only used for savestates maybe also for reporting, but we this pr doesn't mess with those.

**Comment by LunaMoo** [comment]
Added fakeID to savestates and cwcheats as noted in first post. I think it's worth having a temporary rename code to avoid confusion, but unify the homebrew format once and for all:].

**Comment by LunaMoo** [comment]
I don't think I'll find anything else to add here unless requested. So a review of the added code would be nice:3.

 This handles now all cases I could think of, including standalone bootable files with random names, as well as bootable folders aka folders containing bootable file named exactly "EBOOT.PBP", doesn't mess up commercial games nor demos including extracted discs and does not depend on any hardcoded ID's anymore.

**Comment by hrydgard** [comment]
Please rebase, there's a conflict now. I'm going to review soon.

**Comment by LunaMoo** [comment]
Done:3.

File: Core/ELF/ParamSFO.cpp [hunk 9]
```diff
@@ -276,3 +267,27 @@ void ParamSFOData::ValueData::SetData(const u8* data, int size)
 	u_size = size;
 }
 
+std::string ParamSFOData::GenerateFakeID(std::string filename) {
+	// Generates fake gameID for homebrew based on it's folder name.
+	// Should probably not be a part of ParamSFO, but it'll be called in same places.
```
Comment (hrydgard) [inline Core/ELF/ParamSFO.cpp]: Yeah, I think this is acceptable.

File: Core/ELF/ParamSFO.cpp [hunk 10]
```diff
@@ -276,3 +267,27 @@ void ParamSFOData::ValueData::SetData(const u8* data, int size)
...
+		sumOfAllLetters += c;
+		c = toupper(c);
+	}
+
+	if (file.size() < 4) {
+		file += "HOME";
+	}
+	file = file.substr(0, 4);
+
+	std::string fakeID = file + StringFromFormat("%05i", sumOfAllLetters);
```
Comment (hrydgard) [inline Core/ELF/ParamSFO.cpp]: Nitpicking: I'm trying to consistently use %d for integers in format strings, as %i is a little scary in sscanf and better to be consistent. There are bunch more of these but I'm not gonna comment on each one.

File: Core/PSPLoaders.cpp [hunk 11]
```diff
@@ -322,5 +323,41 @@ bool Load_PSP_ELF_PBP(FileLoader *fileLoader, std::string *error_string) {
 	pspFileSystem.Mount("umd0:", fs);
 
 	std::string finalName = ms_path + file + extension;
+
+	std::string homebrewName = PSP_CoreParameter().fileToStart;
+	std::size_t lslash = homebrewName.find_last_of("/");
+	homebrewName = homebrewName.substr(lslash +1);
```
Comment (hrydgard) [inline Core/PSPLoaders.cpp]: Weird spacing around the +

File: Core/PSPLoaders.cpp [hunk 12]
```diff
@@ -322,5 +323,41 @@ bool Load_PSP_ELF_PBP(FileLoader *fileLoader, std::string *error_string) {
...
+	std::string madeUpID = g_paramSFO.GenerateFakeID();
+
+	char title[1024];
+	sprintf(title, "%s : %s", madeUpID.c_str(), homebrewName.c_str());
```
Comment (hrydgard) [inline Core/PSPLoaders.cpp]: snprintf(title, sizeof(title), ....)

I know it's not gonna overflow but this one is also for consistency so you can search for sprintf to find potential overflow bugs...

Alternatively just go ahead and use StringFromFormat.

File: Core/SaveState.cpp [hunk 13]
```diff
@@ -621,7 +604,14 @@ namespace SaveState
 
 			case SAVESTATE_SAVE:
 				INFO_LOG(SAVESTATE, "Saving state to %s", op.filename.c_str());
-				result = CChunkFileReader::Save(op.filename, g_paramSFO.GetValueString("TITLE"), PPSSPP_GIT_VERSION, state);
+				title = g_paramSFO.GetValueString("TITLE");
+				if (title.empty()) {
+					// Homebrew title
+					title = PSP_CoreParameter().fileToStart;
+					std::size_t lslash = title.find_last_of("/");
```
Comment (hrydgard) [inline Core/SaveState.cpp]: Hm, I guess the path is always normalized here so we don't have to care about '\\'..

**Review by hrydgard — APPROVED** [review]
Concept and implementation is good! Just a few nitpicks you can fix if you like.

File: Core/ELF/ParamSFO.cpp (hunk 10 above)
Comment (LunaMoo) [inline Core/ELF/ParamSFO.cpp]: Should I correct all %i to %d in StringFromFormat? A quick search reveals a bit more already in master.

File: Core/PSPLoaders.cpp (hunk 12 above)
Comment (LunaMoo) [inline Core/PSPLoaders.cpp]: Not sure how to do the other, so StringFromFormat there is.:3 BTW that line was mostly a copy paste of code used in full games/demos already. Should I change that as well?

File: Core/SaveState.cpp (hunk 13 above)
Comment (LunaMoo) [inline Core/SaveState.cpp]: I'm checking here for the last "/" to get what's after it - folder name or filename(in case of standalone elf that's not a bootable folder). :) See one line above and under.
 Althrough that part as a whole is just cosmetic - title for homebrew ss which can be seen in ss manager.

File: Core/PSPLoaders.cpp [hunk 14]
```diff
@@ -322,5 +322,40 @@ bool Load_PSP_ELF_PBP(FileLoader *fileLoader, std::string *error_string) {
...
+
+	std::string title = StringFromFormat("%s : %s", madeUpID.c_str(), homebrewName.c_str());
+	INFO_LOG(LOADER, "%s", title.c_str());
+	host->SetWindowTitle(title.c_str());
+
+	// Temporary code
+	// TODO: Remove this after ~ 1.6
+	// It checks for old filenames for homebrew savestates(folder name) and rename them to new fakeID format
+	std::string savestateDir = GetSysDirectory(DIRECTORY_SAVESTATE);
+	savestateDir = ReplaceAll(savestateDir, "\\", "/");
```
Comment (unknownbrackets) [inline Core/PSPLoaders.cpp]: Not a big fan of ruining `\` characters on Linux/Unix, even if they'd be uncommon.  Someone might use a name like `Games \ Stuff` (totally valid on Linux) and wonder why it doesn't work.

-[Unknown]

Comment (hrydgard) [inline Core/PSPLoaders.cpp]: I'll ifdef it Windows-only.

Comment (LunaMoo) [inline Core/PSPLoaders.cpp]: Don't know linux, but if that's a problem, then the affected homebrew would have other problems if it even could load, since code existing earlier which I based this on did same thing.:| Is there any reason/platform we would be doing that in the first place? I think even mixed / \ in path is fine on windows.

Comment (unknownbrackets) [inline Core/PSPLoaders.cpp]: Hmm, well, anywhere that does this on non-Windows is probably wrong.  However, it sometimes makes sense to do this on Windows because both `\` and `/` work.  If it's anywhere, it's to make sure we don't have mixed paths - because it causes duplicates in Recent lists.

-[Unknown]
