### PR TITLE
several patches to fix recent regressions with CPUDetect && FileUtils

### LINKED ISSUE #14450: Trying to run the latest PPSSPP dev build on Linux will yield a "Floating Point exception"
### What happens?

PPSSPP shows this error : "Floating point exception (core dumped)"
### What *should* happen?
PPSSPP should run fine.

#### What hardware / device and operating system?
OS:Linux Pop OS latest LTS distro
#### What graphics card (GPU) or mobile phone model?
Radeon 530 and Intel UHD 620
#### What PPSSPP version (standalone/official), and did it work before?
Latest stable PPSSPP should work fine.
#### Which game or games?

not relevant

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Note: Used the Github Actions binary and didnt compile it from source.**

### PR DESCRIPTION
**Pull request by SeanMcG**

### CODE REVIEW

File: Common/File/FileUtil.cpp [hunk 1]
```diff
@@ -896,7 +896,8 @@ bool ReadFileToString(bool text_file, const char *filename, std::string &str) {
 		success = true;
 	} else {
 		str.resize(len);
-		success = fread(&str[0], 1, len, f) == len;
+		int read = fread(&str[0], 1, len, f);
+		success = read <= len && !ferror(f);
```
Comment (unknownbrackets) [inline Common/File/FileUtil.cpp:900]: We should resize to the actual size read as well.  I'll fixup.

-[Unknown]
