### PR TITLE
Various libretro fixes

### LINKED ISSUE #14783: [Libretro] Frozen image when frameskip is set to anything above 0 or 1 (depending on game framerate)
### Game or games this happens in

All

### What area of the game / PPSSPP

So with the libretro core, frameskip only works if it's set to 0 or 1 for 30fps games and only if set to 0 for 60fps games, anything above will just give you a frozen image. The game keeps running in the background, you can still hear the audio and your can move. As soon as you set frameskip back to 0/1 everything goes back to normal.

After bisecting, it looks like it started happening with b41d20dd8265b82352a760a56336459dc06ce43f, so this is not something new but I've never noticed it before because I don't use frameskip.

This is happening with Vulkan/D3D11/GLcore. Tested on Windows but a Linux user confirmed it was happening for him too.

### What should happen

Game should display properly no matter what's the current frameskip value.

### Logs

Nothing helpful in logs.

### Platform

Windows

### Mobile phone model or graphics card

GTX 970

### PPSSPP version affected

6fbc73e

### Last working version

93d8bbc

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by stuken**
This change addresses a few outstanding niggles with the libreto port.

1. Fixes old issue where the Config.load() call was never uses leaving many settings in a potentially inconsistent state. retro_init and retro_load_game code has been rearranged to allow the Config.Load() call to succeed. 
2. Exposed g_Config.iInflightFrames as a core option. Hopefully this should reduce some input lag.
3. Removed the skipDrawReason gating in SwapBuffers(). Fixes #14783
4. Disable the default ppsspp fast forward frame throttle setting. This is now controlled by a frontend check and only enables it if the frontend is explicilty fast forwarding.
5. Proper capitalization in the core options and a bunch dead code removals.

### CODE REVIEW

File: libretro/libretro.cpp [hunk 1]
```diff
@@ -397,6 +400,16 @@ static void check_variables(CoreParameter &coreParam)
...
 
+   bool isFastForwarding = environ_cb(RETRO_ENVIRONMENT_GET_FASTFORWARDING, &isFastForwarding);
+   if (isFastForwarding)
+   {
+      coreParam.fastForward = true;
+   }
+   else
+   {
+      coreParam.fastForward = false;
+   }
```
Comment (hrydgard) [inline libretro/libretro.cpp:411]: Just replace this with coreParam.fastForward = isFastForwarding;

File: libretro/libretro.cpp [hunk 2]
```diff
@@ -411,58 +424,78 @@ void retro_set_input_state(retro_input_state_t cb) { input_state_cb = cb; }
...
+
+   g_Config.currentDirectory = retro_base_dir;
+   g_Config.defaultCurrentDirectory = retro_base_dir;
+   g_Config.memStickDirectory = retro_save_dir;
+   g_Config.flash0Directory = retro_base_dir / "flash0";
+   g_Config.internalDataDirectory = retro_base_dir;
+
+   VFSRegister("", new DirectoryAssetReader(retro_base_dir));
+
+   host = new LibretroHost;
```
Comment (hrydgard) [inline libretro/libretro.cpp:493]: Code style and safety thing - when using the new operator, always include the parenthesis.

`host = new LibretroHost();`

**Review by hrydgard — COMMENTED** [review]
Looks ok to me, I trust that it's tested. 

Couple of minor style nits.

File: libretro/libretro.cpp (hunk 1 above)
Comment (stuken) [reply libretro/libretro.cpp]: Done.

File: libretro/libretro.cpp (hunk 2 above)
Comment (stuken) [reply libretro/libretro.cpp]: And done.

**Comment by bslenul** [comment]
Thanks for the frameskip fix! 👍 

2 things however: default for "Texture Scaling Level" has been "OFF" for years now, I'm not sure it's a good idea to make "Auto" the new default. But I might be biased, I really dislike the xBRZ stuff, etc. :p 

And I'm not familiar with the "Inflight Frames" setting so I'm a bit confused, standalone says "Buffer graphics commands (faster, input lag)" and is set to "Up to 2" by default (at least on Windows, idk if it varies depending on the device used). Libretro core says "Buffered frames (Slower, less lag, restart)" and is set to "No buffer" by default. So is it faster with "No buffer" or with "Up to 2"? And do we want "No buffer" as default if it's the slowest?

**Comment by hrydgard** [comment]
Oh, I missed that. Texture Scaling should absolutely not default to Auto, it's a terrible choice for that setting that we should probably remove.
