### PR TITLE
Win32 handle leak fix

### LINKED ISSUE #11698: Can't download any file
PPSSPP was open in background and i was downloading a software, i was getting a error again and again, i tried using idm but it didn't work after that i realized PPSSPP was using that folder, can something be done about it, if not is it possible to add error message?

        8 GB Ram
        i5 8400
        GTX 1060
        Windows 10 1809
        PPSSPP 1.7.4 latest stable version at the moment.

### LINKED ISSUE #11841: Handle leak on Windows
Looking at PPSSPP in Process Explorer, there's a strange issue where handles to games appears as open files unexpectedly. It repros the easiest by just rightclicking on a game in the menu.

Really not sure where these are coming from, but they have the annoying side effect that you can't fully delete a homebrew game that you just played, and it's never good to leak handles so this needs to be fixed.

Possibly Windows-specific.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #11841 and likely fixes #11698.

Additionally, minor code cleanups.

### CODE REVIEW

File: UI/GameInfoCache.cpp [hunk 1]
```diff
@@ -229,6 +229,11 @@ bool GameInfo::LoadFromPath(const std::string &gamePath) {
 }
 
 std::shared_ptr<FileLoader> GameInfo::GetFileLoader() {
+	if (filePath_.empty()) {
+		// Happens when workqueue tries to figure out priorities in PrioritizedWorkQueue::Pop(),
+		// because priority() calls GetFileLoader()... gnarly.
+		return fileLoader;
```
Comment (unknownbrackets) [inline UI/GameInfoCache.cpp]: Just remember that for some loaders, e.g. ones that involve memory caching or http access, the cost of tossing this in the bin and getting a new one a couple times is much higher.  Ideally we shouldn't recreate just because that's easiest.

-[Unknown]

Comment (unknownbrackets) [reply UI/GameInfoCache.cpp]: Oops, put this comment in the wrong place somehow - was meant for the lifetime comment.

-[Unknown]
