### PR TITLE
Pre-scan the root of texture packs for hash-named files.

### LINKED ISSUE #17365: DDS format reported not to work
Reported by Sul on discord, could be DDSs produced by some specfic tool (it's only been tested with Compressionator). Here are some samples:

[UCUS98633.zip](https://github.com/hrydgard/ppsspp/files/11362250/UCUS98633.zip)

Software used to generate the files:  https://github.com/chaiNNer-org/chaiNNer

It was also reported by AetheralMeowstic that multiple texture packs weren't loading. I've been unable to reproduce this as well.

### PR DESCRIPTION
**Pull request by hrydgard**
Since it only happens on startup, shouldn't be too crazy-slow even on Android with scoped storage.

This allows finding files like 040cc000000007086a89188c.ktx2 without adding entries to the ini file, even though its extension doesn't match the default extension of ".png".

Also fixes broken-ness when doing dir listings in zip files.

Fixes #17365 .

### CODE REVIEW

File: Common/File/VFS/ZipFileReader.cpp [hunk 1]
```diff
@@ -132,26 +132,29 @@ bool ZipFileReader::GetFileListing(const char *orig_path, std::vector<File::File
...
+				int offset = pathlen;
+				std::string dirName = std::string(name + offset, slashPos - (name + offset));
 				directories.insert(dirName);
-			} else if (name[pathlen] == '/') {
-				const char *fn = name + pathlen + 1;
+			} else {
+				// It's a file.
+				const char *fn = name + pathlen;
 				files.insert(std::string(fn));
-			}  // else, it was a file with the same prefix as the path. like langregion.ini next to lang/.
```
Comment (unknownbrackets) [inline Common/File/VFS/ZipFileReader.cpp:154]: How do we protect against this case now?

So let's say `path` is "assets/lang".  We did check it starts with "assets/lang", so that's good.  But "assets/langregion" matches that and does not have a /.  So won't we match it and add it to the list as "egion" or something?

I might also be missing something about `name + pathlen`.  In my above scenario, "assets/lang/foo.ini" would not find a slash after `name + pathlen + 1` (which is "foo.ini") but wouldn't `fn` become "/foo.ini"?  Seems confusing.

It feels like this new logic might only be something that works when path == ""?  Which does look like it was broken before.

-[Unknown]

File: GPU/Common/TextureReplacer.cpp [hunk 2]
```diff
@@ -256,31 +257,57 @@ bool TextureReplacer::LoadIniValues(IniFile &ini, bool isOverride) {
...
+			continue;
+		Path path(file.name);
+		std::string ext = path.GetFileExtension();
+
+		std::string hash = file.name.substr(0, file.name.size() - ext.size());
+		if (!((hash.size() >= 26 && hash.size() <= 27 && hash[24] == '_') || hash.size() == 24)) {
+			continue;
+		}
+		// OK, it's hash-like enough to try to parse it into the map.
+		if (equalsNoCase(ext, ".ktx2") || equalsNoCase(ext, ".png") || equalsNoCase(ext, ".dds")) {
```
Comment (unknownbrackets) [inline GPU/Common/TextureReplacer.cpp:278]: Well, I guess we might as well add ".zim"?

-[Unknown]

Comment (hrydgard) [reply GPU/Common/TextureReplacer.cpp:278]: late night coding, oops.

File: Common/File/VFS/ZipFileReader.cpp (hunk 1 above)
Comment (hrydgard) [reply Common/File/VFS/ZipFileReader.cpp:154]: I somehow convinced myself that since all directories in a zip file always end wih '/', they'd be caught in the first case anyway - but that doesn't even make sense. Don't know what I was thinking.

I'll make a unit test for this today to really make sure all cases comes out right.

Comment (hrydgard) [reply Common/File/VFS/ZipFileReader.cpp:154]: Actually this does work - just gotta follow the convention of directory paths ending with "/" consistently throughout.

The unit test revealed a number of bugs, but I've fixed it and it's working now.

**Comment by hrydgard** [comment]
I've solved the above comments, so I'll just get it in for 1.15.1.

File: Common/File/VFS/ZipFileReader.cpp (hunk 1 above)
Comment (unknownbrackets) [reply Common/File/VFS/ZipFileReader.cpp:154]: Okay, yeah, making `GetFileListing()` add `/` makes sense.

But oops, now there's a source_assets/ziptest.zip.

-[Unknown]

Comment (hrydgard) [reply Common/File/VFS/ZipFileReader.cpp:154]: Yeah, we don't have a designated directory for testdata, at least not that I found. Though I suppose could have put the zip in /unittest too.
