### PR TITLE
Enable the FakeMipmapChange flag for US/EU Tactics Ogre, fixing replacement problem.

### LINKED ISSUE #17491: Tactics Ogre LUCT Text/Font no longer dump or replace on newer versions
### Game or games this happens in

ULUS-10565 Tactics Ogre: Let Us Cling Together

### What area of the game

I recently made a texture pack for Tactics Ogre LUCT and for some reason the text refuses to dump or upscale on newer versions of ppsspp. On 1.13.2 my pack works in its entirety. I tried to pinpoint the earliest version this started happening in and it is as early as the oldest build on the old build list here: https://buildbot.orphis.net/ppsspp/index.php?m=fulllist (v1.13.2-1353-g35dfd85ce)

This is the pack in case anyone would like to check on it themselves: https://forums.ppsspp.org/showthread.php?tid=26100

Upon posting about this in the ppsspp discord I was told to make an issue here on github. I have tried changing graphics api's, and nearly all forms of graphics settings already. The pack simply works perfect on 1.13.2 and simply does not upscale any of the text at all in any version after.

### What happens

The text does not dump/replace at all

### What should happen

the text should dump/replace

### GE frame capture

_No response_

### Platform

Windows

### Mobile phone model or graphics card

RTX 3070TI

### PPSSPP version affected

v1.13.2-1353-g35dfd85ce and later

### Last working version

1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

### LINKED ISSUE #17980: Tactics Ogre texture pack only working on 1.13.2 - needs investigation
Reported by CoffeePotatio on Discord.

"
This is the mod in question: https://forums.ppsspp.org/showthread.php?tid=26100 . When used in the latest, which I think is 1.15.4 on Steam Deck, most of the textures don't work. 

It will replace the cursor, as well as some text, but also turn any wavy effects into really blocky looking ones, and plain not replace the portraits, map tiles, equippable item text, most effect icons,  or background art. 

I have videos of it working and not working under the same settings on both versions, if that helps.

When I dropped 1.13.2 files into the same settings, it worked fine.
"

### PR DESCRIPTION
**Pull request by hrydgard**
For correct lookups, without our texture replacement actually supporting volume textures, we need to use this mechanism even in the non-JP versions.

The game actually uses two 512x512 mipmaps, but they're identical and point to the same memory, so also add a tweak to treat them as a regular 2D texture instead for purposes of replacement (and also texturing). This is presumably legacy from the initial Japanese version that needs to use multiple texture layers, in pairs, presumably to avoid mip filtering (which is kinda silly, could've just turned that off).

This does actually not fully fix texture replacement for the Japanese version, unfortunately. For that we need more proper support for these weird textures in the texture replacement code - when I refactored it before for more natural and efficient handling of regular mipmapping, this kinda got lost. I will fix that separately.

Also better logging of invalid replacement lines in the [hashes] section of textures.ini.

Fixes #17980 
Fixes #17491

### CODE REVIEW

File: GPU/Common/TextureReplacer.cpp [hunk 1]
```diff
@@ -226,31 +226,50 @@ bool TextureReplacer::LoadIniValues(IniFile &ini, VFSBackend *dir, bool isOverri
...
 
 		for (const auto &item : hashes) {
 			ReplacementCacheKey key(0, 0);
-			int level = 0;  // sscanf might fail to pluck the level, but that's ok, we default to 0. sscanf doesn't write to non-matched outputs.
+			// sscanf might fail to pluck the level if omitted from the line, but that's ok, we default level to 0.
+			// sscanf doesn't write to non-matched outputs.
+			int level = 0;
 			if (sscanf(item.first.c_str(), "%16llx%8x_%d", &key.cachekey, &key.hash, &level) >= 1) {
+				if (item.second.empty()) {
+					WARN_LOG(G3D, "Texture replacement: Ignoring hash mapping to empty filename: '%s ='", item.first.c_str());
```
Comment (unknownbrackets) [inline GPU/Common/TextureReplacer.cpp:246]: This isn't really an error, at least it used to be documented as an intentional way to disable saving a texture which you've decided it's not useful to upscale (example: solid color texture.)  Seems annoying to logspam it.

-[Unknown]

File: GPU/Common/TextureReplacer.cpp [hunk 2]
```diff
@@ -226,31 +226,50 @@ bool TextureReplacer::LoadIniValues(IniFile &ini, VFSBackend *dir, bool isOverri
...
 
-	bool filenameWarning = false;
+	int badFileNameCount = 0;
 
 	std::map<ReplacementCacheKey, std::map<int, std::string>> filenameMap;
+	std::string badFilenames;
 
 	if (ini.HasSection("hashes")) {
-		auto hashes = ini.GetOrCreateSection("hashes")->ToMap();
+		auto hashes = ini.GetOrCreateSection("hashes")->ToVec();
```
Comment (unknownbrackets) [inline GPU/Common/TextureReplacer.cpp:235]: When will it make sense to map the same hash to two different filenames?  The level is still part of the key, so this would just overwrite those duplicates silently anyway?

Not sure I understand what the intent would be for:

1234567890abcdef_0 = image1.png
1234567890abcdef_0 = image2.png
1234567890abcdef_0 = image3.png

-[Unknown]

Comment (hrydgard) [reply GPU/Common/TextureReplacer.cpp:235]: The map was deduplicating the empty keys which were confusing my logging, which I added because of a theory that turned out to be wrong.

File: assets/compat.ini [hunk 3]
```diff
@@ -265,11 +265,16 @@ ULJM06365 = true
...
 # For example this requires games like Tactics Ogre(Japanese) to display multi bytes fonts stored in mipmaps.
 # See issue #5350.
-# Tactics Ogre(Japanese)
+# Tactics Ogre (Japanese)
 ULJM05753 = true
 NPJH50348 = true
 ULJM06009 = true
 
+# Tactics Ogre (US, EU). See #17491 / #17980
+# Required for texture replacement to work correctly, though unlike JP, only one layer is actually used (two duplicates, really)
```
[the remark this answers is not in the document]
Comment (hrydgard) [reply assets/compat.ini:274]: Yes, it's not ideal. I will try to rectify this flaw, but I'm trying to get a release ready and the change I'm planning is a bit too big.

Though in reality we've only seen this in three or four games.

**Comment by kikumarogaming** [comment]
Nice to meet you. I am making a HDMOD for the Japanese version of Tactics Ouga. However, I have a mipmap set up for the text image, but I can't make that part HD. how should I describe the ini file? Or do I have to update PPSSPP itself? I can only use Japanese and I am using a translator. Therefore, please understand that we cannot give you a quick answer.
I searched Tactics Ooga and it seems that the problem with the English version has been fixed. Could you please fix the Japanese version so that the text is readable?
I tried it and it works in version 1.13.2.

**Comment by hrydgard** [comment]
Thanks for reporting @kikumarogaming , created an issue report, will take a look: #19623
