### PR TITLE
Texture dumping fix

### LINKED ISSUE #15831: Texture dumping glitch.
### Game or games this happens in

ULJM06097 - Musou Orochi 2 Special (Japan)

### What area of the game

In-gameplay.

### What happens

Texture in-gameplay and GE debugger is look correct. but when enabled "Save new textures" is always dump (weapon)texture glitch. (show green color only), it happem on all backends.

GE0

### What should happen

Can dump (weapon)texture without glitch.

GE1

### GE frame capture

Texture in-game is look fine, It happen when dump textures.

### Platform

Windows

### Mobile phone model or graphics card

Intel HD Graphic 520.

### PPSSPP version affected

v1.13.1-17-g7d4d925a3.

### Last working version

v1.13.1-12-g512382c4d.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes textures saved with bad colors.

Also now logs out full image paths when saving.

Fixes #15831

### CODE REVIEW

File: GPU/Vulkan/TextureCacheVulkan.cpp [hunk 1]
```diff
@@ -499,12 +499,16 @@ void TextureCacheVulkan::BuildTexture(TexCacheEntry *const entry) {
...
+		actualFmt = VULKAN_8888_FORMAT;
+	}
+
 	char texName[128]{};
 	snprintf(texName, sizeof(texName), "tex_%08x_%s", entry->addr, GeTextureFormatToString((GETextureFormat)entry->format, gstate.getClutPaletteFormat()));
 	image->SetTag(texName);
 
 	bool allocSuccess = image->CreateDirect(cmdInit, plan.createW, plan.createH, plan.depth, plan.levelsToCreate, actualFmt, imageLayout, usage, mapping);
-	if (!allocSuccess && !lowMemoryMode_) {
+	if (!allocSuccess && !lowMemoryMode_ && !replacer_.Enabled()) {
```
Comment (unknownbrackets) [inline GPU/Vulkan/TextureCacheVulkan.cpp:511]: Low memory actually happens a lot because of replacements on an underpowered device - why disable the check here?

A user may have replacements + scaling enabled, and this at least makes it decimate more aggressively.

-[Unknown]

File: GPU/Common/TextureCacheCommon.cpp [hunk 2]
```diff
@@ -2397,6 +2398,18 @@ bool TextureCacheCommon::PrepareBuildTexture(BuildTexturePlan &plan, TexCacheEnt
 		// But, we still need to create the texture at a larger size.
 		plan.replaced->GetSize(0, plan.createW, plan.createH);
 	} else {
+		if (replacer_.Enabled() && !plan.replaceValid && plan.depth == 1) {
+			ReplacedTextureDecodeInfo replacedInfo;
+			// TODO: Do we handle the race where a replacement becomes valid AFTER this but before we save?
```
Comment (unknownbrackets) [inline GPU/Common/TextureCacheCommon.cpp:2403]: No, not anymore.  It before checked `IsInvalid()` (which is, importantly, not the same as `!IsValid()` - when the state is yet indeterminate) before saving.  Because that was removed, it will presumably overwrite or resave things while loading.

-[Unknown]
