### PR TITLE
Fix sceKernelExitThread

### LINKED ISSUE #9523: Namco Museum - Battle Collection - ULUS100035 loading problem
using ppsspp 1.4
any game you choose from the left hand side (originals) it just sits on the now loading screen and nothing else
if you choose any game from the arrangement side they all load 
here is a debug log 
rename txt to zip
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/887379/ppsspplog.txt)

### LINKED ISSUE #13297: Namco Museum Vol. 2 - ULJS00047 infinite loading in some game
No known version
(In fact test jpcsp first, then ppsspp)

The game only can load pacman,Moto
It is infinite loading in King & Balloon,Mappy,Dragon Spirit
The log below load pacman,Moto then King & Balloon.
v1.10.3-436-gc2c2ba7eb log: https://gist.github.com/sum2012/d6a86dca0fece099bc141d4480eb2544
debug log: 
[ppsspplog-v1.10.3-436-gc2c2ba7eb-debug.txt.zip](https://github.com/hrydgard/ppsspp/files/5084658/ppsspplog-v1.10.3-436-gc2c2ba7eb-debug.txt.zip)

From info log,It seem
42:36:539 Thread for L I[SCEKERNEL]: hle\scekernelthread.cpp:2155 sceKernelExitThread(-2147352152)
is wrong, should be https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules/ThreadManForUser.java#L3924

### PR DESCRIPTION
**Pull request by sum2012**
fix #13297 fix #9523
According from
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules/ThreadManForUser.java#L3924

edit:
v1.10.3-436-gc2c2ba7eb log: https://gist.github.com/sum2012/d6a86dca0fece099bc141d4480eb2544
modify log: https://gist.github.com/sum2012/61db54d9719b97cc52ff2c97f077afe5

### CODE REVIEW

**Comment by hrydgard** [comment]
Nice find!

We already have the error codes declared in sceKernel.h though, no need to redeclare them. Please change to use:

SCE_KERNEL_ERROR_CAN_NOT_WAIT
SCE_KERNEL_ERROR_ILLEGAL_ARGUMENT

File: Core/HLE/sceKernelThread.h [hunk 1]
```diff
@@ -77,6 +77,8 @@ struct SceKernelSysClock {
 	u32_le hi;
 };
 
+static const int ERROR_KERNEL_WAIT_CAN_NOT_WAIT = 0x800201a7;
```
Comment (unknownbrackets) [inline Core/HLE/sceKernelThread.h:80]: We have `SCE_KERNEL_ERROR_CAN_NOT_WAIT` already - we shouldn't define a new value here.

`SCE_KERNEL_ERROR_ILLEGAL_ARGUMENT` for the other.

-[Unknown]

File: Core/HLE/sceKernelThread.cpp [hunk 2]
```diff
@@ -2148,11 +2148,16 @@ void __KernelReturnFromThread()
 	// The stack will be deallocated when the thread is deleted.
 }
 
-void sceKernelExitThread(int exitStatus) {
+int sceKernelExitThread(int exitStatus) {
+	if (!__KernelIsDispatchEnabled() && sceKernelGetCompiledSdkVersion() > 0x0307FFFF)
+		return ERROR_KERNEL_WAIT_CAN_NOT_WAIT;
```
Comment (unknownbrackets) [inline Core/HLE/sceKernelThread.cpp:2153]: Let's use `return hleLogError(SCEKERNEL, ERROR_KERNEL_WAIT_CAN_NOT_WAIT);`.  This way it will show in the log and we won't get confused if this breaks another game.

-[Unknown]

**Review by unknownbrackets — COMMENTED** [review]
Makes sense.

Oops, should've read @hrydgard's reply first.

-[Unknown]

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets done

**Comment by hrydgard** [comment]
Thanks, looks good! Will merge when the build is green.
