### PR TITLE
Font:alloc/free memory for font file and char bitmap.

### LINKED ISSUE #8853: Lumines 2 JP ULJM05232 not work after "now loading"
ppsspp forum link: http://forums.ppsspp.org/showthread.php?tid=15525

It never work , however USA version work.

v1.2.2-763-gdddb3c3
JP log (not work): https://gist.github.com/sum2012/1db7a93b247cb1e3bd15677c9d62243c
USA log (work): https://gist.githubusercontent.com/sum2012/c1b7ea2ed7a9bfc9868c056b7f5cf910/raw/7dc01057af387b2f528ace4bb826545fc50e2257/gistfile1.txt

disassum

### PR DESCRIPTION
**Pull request by shenweip**
Fixes #8853. Following the guide of JPCSP as the tips mentioned in #8853.

### CODE REVIEW

File: Core/HLE/sceFont.cpp [hunk 1]
```diff
@@ -747,6 +915,12 @@ void __FontDoState(PointerWrap &p) {
 	__KernelRestoreActionType(actionPostAllocCallback, PostAllocCallback::Create);
 	p.Do(actionPostOpenCallback);
 	__KernelRestoreActionType(actionPostOpenCallback, PostOpenCallback::Create);
+	p.Do(actionPostOpenAllocCallback);
```
Comment (unknownbrackets) [inline Core/HLE/sceFont.cpp]: Need to update `auto s = p.Section("sceFont", 1);` to `1, 2` and check that `s >= 2`.

In the other case, it gets trickier.  The simplest thing would be to have a flag like `static bool useAllocCallbacks = true;` and set it to false if the save state is old.  Then we'd keep not using those callbacks, and wouldn't need to worry about restoring them safely.

-[Unknown]

File: Core/HLE/sceFont.cpp [hunk 2]
```diff
@@ -1100,6 +1272,24 @@ static int sceFontGetCharInfo(u32 fontHandle, u32 charCode, u32 charInfoPtr) {
 	auto charInfo = PSPPointer<PGFCharInfo>::Create(charInfoPtr);
 	font->GetCharInfo(charCode, charInfo);
 
+	u32 allocSize = charInfo->bitmapWidth * charInfo->bitmapHeight;
+	if (charInfo->sfp26AdvanceH != 0 || charInfo->sfp26AdvanceV != 0) {
+		if (font->GetFontLib()->GetCharInfoBitmapAddress() != 0) {
```
Comment (unknownbrackets) [inline Core/HLE/sceFont.cpp]: Hm, so in theory this alternates between allocating and freeing each call?  That seems like odd behavior.

-[Unknown]

**Comment by unknownbrackets** [comment]
Sorry, #12710 will have introduced some minor conflicts - just rename Action -> PSPAction, mainly.

-[Unknown]

File: Core/HLE/sceFont.cpp [hunk 3]
```diff
@@ -427,11 +498,13 @@ class FontLib {
...
 
 	void Done() {
+		bool needPending = false;
 		for (size_t i = 0; i < fonts_.size(); i++) {
 			if (isfontopen_[i] == FONT_IS_OPEN) {
-				fontMap[fonts_[i]]->Close();
+				CloseFont(fontMap[fonts_[i]]);
 				delete fontMap[fonts_[i]];
 				fontMap.erase(fonts_[i]);
+				needPending = true; // Pending all the next mipcalls.
```
[the remark this answers is not in the document]
Comment (shenweip) [reply Core/HLE/sceFont.cpp]: Because the callback may be called mutipletimes in a syscall, and the former will be covered by the latter, so put the latter calls to the pending list.

File: Core/HLE/sceFont.cpp (hunk 2 above)
Comment (shenweip) [reply Core/HLE/sceFont.cpp]: The alloc size will always be different if the char is different, so this behavior seems reasonable?

File: Core/HLE/sceFont.cpp [hunk 4]
```diff
@@ -524,21 +602,55 @@ class FontLib {
...
+
+		flushFont();
+
 		for (size_t i = 0; i < fonts_.size(); i++) {
 			if (fonts_[i] == font->Handle()) {
 				isfontopen_[i] = 0;
-
+				if (openAllocatedAddresses_[i] != 0) {
+					u32 args[2] = { userDataAddr(), openAllocatedAddresses_[i] };
+					__KernelDirectMipsCall(freeFuncAddr(), 0, args, 2, true, needPending);
```
[the remark this answers is not in the document]
Comment (shenweip) [reply Core/HLE/sceFont.cpp]: This also want to prevent the fomer callback from being covered by the latter callbacks.

File: Core/HLE/sceFont.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (unknownbrackets) [reply Core/HLE/sceFont.cpp]: Okay, what if we just change this:

```c++
static bool __CanExecuteCallbackNow(Thread *thread) {
	return g_inCbCount == 0;
}
```

To:

```c++
static bool __CanExecuteCallbackNow(Thread *thread) {
	return currentCallbackThreadID == 0 && g_inCbCount == 0;
}
```

Does that also make it work?  I think I'd rather avoid the syscall having to decide whether it should be pending or not.

-[Unknown]

File: Core/HLE/sceFont.cpp (hunk 2 above)
Comment (unknownbrackets) [reply Core/HLE/sceFont.cpp]: Well, that part makes sense, but I'd expect it to likely allocate AND deallocate for each call?  I guess would have to test to see what it does.  But this:

sceFontGetCharInfo('A'); // calls allocate, keeps A allocated
sceFontGetCharInfo('B'); // calls free on A, nothing allocated now
sceFontGetCharInfo('C'); // calls allocate, keeps C allocated

Seems like strange behavior - you'd think it'd be more like:

sceFontGetCharInfo('A'); // calls allocate, keeps A allocated
sceFontGetCharInfo('B'); // calls free on A, calls alloc on B
sceFontGetCharInfo('C'); // calls free on B, calls alloc on C

Or:

sceFontGetCharInfo('A'); // calls alloc on A, then free on A
sceFontGetCharInfo('B'); // calls alloc on B, then free on B
sceFontGetCharInfo('C'); // calls alloc on C, then free on C

-[Unknown]

File: Core/HLE/sceFont.cpp [hunk 5]
```diff
@@ -601,6 +735,36 @@ void PostOpenCallback::run(MipsCall &call) {
...
+void PostCharInfoFreeCallback::run(MipsCall &call) {
+	FontLib *fontLib = fontLibList[fontLibID_];
+	fontLib->SetCharInfoBitmapAddress(0);
+
+	u32 allocSize = charInfo_->bitmapWidth * charInfo_->bitmapHeight;
+	PostCharInfoAllocCallback *action = (PostCharInfoAllocCallback *)__KernelCreateAction(actionPostCharInfoAllocCallback);
+	action->SetFontLib(fontLibID_);
+
+	u32 args[2] = { fontLib->userDataAddr(), allocSize };
+	__KernelDirectMipsCall(fontLib->allocFuncAddr(), action, args, 2, true);
```
Comment (shenweip) [inline Core/HLE/sceFont.cpp]: @unknownbrackets , Alloc for the new char after free old here, matches the second case you point out, I mean:
sceFontGetCharInfo('A'); // calls allocate, keeps A allocated
sceFontGetCharInfo('B'); // calls free on A, calls alloc on B
sceFontGetCharInfo('C'); // calls free on B, calls alloc on C

**Comment by shenweip** [comment]
Thanks @unknownbrackets for helps.

File: Core/HLE/sceFont.cpp [hunk 6]
```diff
@@ -35,9 +35,15 @@ enum {
 	FONT_IS_OPEN   = 1,
 };
 
+// For the save states.
+static bool useAllocCallbacks = true;
```
Comment (unknownbrackets) [inline Core/HLE/sceFont.cpp]: We also need to reset it to `true` in `__FontInit()`.  This way, if you load an old save state, and then reset, we'll start using them again.

-[Unknown]

File: Core/HLE/sceFont.cpp (hunk 5 above)
Comment (unknownbrackets) [reply Core/HLE/sceFont.cpp]: Oh, I thought it just alternated.  I missed indeed that this also allocates.

-[Unknown]

**Review by unknownbrackets — CHANGES_REQUESTED** [review]
Sorry just one value to reset on init.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]

**Comment by unknownbrackets** [comment]
This seems to make Jeanne d'Arc hang on startup.

-[Unknown]

**Comment by shenweip** [comment]
Oh, it's not good, I have this game and will test it later.

**Comment by hrydgard** [comment]
This also broke LocoRoco 2, unfortunately (text glitches, crash on pause).
